---
layout: base.njk
title: 制約と自由度
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]

TODO: UNDER CONSTRUCTION

== 制約と自由度

カメラの位置、モチーフの位置、大きさ、形状がすべて定まっていれば、像は一通りに定まるので、「好きに」決めていい部分は一切ありません。そのような場合にも、透視図法の知識を使えば、すでに定まっている設計図のような情報からたくさんの手順を踏むことで、その一通りの像を作図することができます。

が、そこまでガチガチに状況を定めてから絵を描くことは稀です（その必要があれば3DCGを使った方がいいかもしれません）。

定まっていない要素がある場合には、制約が緩くなるように見えて、どこの部分を「好きに」決めていいのか、どこは「好きに」決めてはいけないのか、が複雑に絡み合うことになり、意外と難しいです。


例えばモチーフに対するカメラの位置が定まっていない場合でも、カメラを動かしても普遍的に成り立つ性質は守る必要があります。

しかし、モチーフを「好きに」一つ書いたことで、カメラの位置が逆算的に定まってしまうような場合もあり、そうすると二個目のモチーフからはより強い制約が加わることもあります。

どのように条件が絡み合っていて、どうすれば正確な形に見えるのかは、複雑に条件が絡み合うので、結構応用的な知識の使い方になります。
それが分かるようになれば、応用的な場面までマスターしたといえるでしょう。

また、逆に、その知識を使うことで、フリーハンドで描かれた絵に対してもどこが歪んでいるかを予想することができます。例えばフリーハンドで書いた立方体が歪んで見えるときは、いずれかの条件が崩れているのだろうと考えられます。立方体はすべての辺の長さが等しく、すべての角が直角という強い制約のある図形なので、その像としてあり得る形にも強い制約があります。

このような知識を運用するため、まずは図形の像とその性質について熟知する必要があります。


== 自由度

簡単な例から始めます。「三角形ABCが与えられたとして、平面上にそれと合同な三角形A'B'C'を描いてください」と言われたら、どのようにすればいいでしょうか。（合同条件については学校でもう習っているものとします。AB=A'B'、BC=B'C'、CA=C'A'を満たすとき、三角形は合同です）

点A'とB'が与えられたとき、点C'はAC=A'C'、BC=B'C'となるようにコンパスを二回使えば、定まります（裏返しを含めて2つだけありますが、2択しかありません。）。しかし、点A'とB'は好きに決めて良いでしょうか。

点A'はどこに描いてもいいです。白紙の上のどこに点A'を置いても、三角形ABCと合同になるような、三角形A'B'C'を描くことができます。

では点B'はどうでしょう。点A'が決まったとき、点B'を本当に好きに決めてしまうと、AB=A'B'が成り立たない可能性があります。点A'を決めた後、点B'はAB=A'B'となるようにする必要があります。その際、コンパスでA'中心として、半径ABの円を描く必要があります。しかし。その円上に点B'を置く必要があります。つまり、点A'は好きに決めていいですが、点B'はそうではありません。つまり、BはAよりは決め方が不自由で、Cよりは決め方が自由ですね。

このように、どこを好きに決めていいのか、どこはそうではないのか、を定めるのが「自由度」です。

== 自由度

この「好きに決めて良いか」の度合いを数値化すると面白いことが起きます。

平面上に自由に点を置いていいとき、その点の自由度を2と考えます。これは平面上の点はx座標とy座標の二つの数値で表すことに対応しています。先ほどの例でいう点A'は自由度2です。

直線や円周上に点を置くとき、その点の自由度を1と考えます。直線であれば数直線上の座標で、円周上であれば角度で表すことができます。直線や円に限らず、「線」のようなものの上に点を取るときは、自由度1と考えます。先ほどの例でいう点B'は自由度1です。

そして、点が定まっているときや、有限個の点から選ぶときには、その点の自由度を0と考えます。さっきの例のC'の選び方は2択だったので、自由度は0です。

== 図形の自由度

自由度を足したり引いたりすることを考えることで面白いことが分かります。

先ほどの例では、三角形A'B'C'を描く過程で、合計3つの自由度について、それぞれ「好きに」選んで決めたことで、三角形A'B'C'を一つに決めることができました。これは、点A'の自由度2、点B'の自由度1、点C'の自由度0の合計を数えています。

そして、なんとこれは三角形の作図方法に関係なく、三角形A'B'C'を描くときに決める必要のある自由度は常に3になることが分かります。先ほどはAB=A'B'、BC=B'C'、CA=C'A'の3つの合同条件から定めましたが、例えばAB=A'B'、AC=A'C'、∠BAC=∠B'A'C'、の3つの合同条件から定めても、同様に自由度は3になります。

これをもって、平面上の形と大きさが決まった三角形には、合計3の自由度があると考えることができます。三角形を回す、上下に動かす、左右に動かす、の三つの自由度に対応しています。

同様に、合同な四角形の場合はどうでしょうか、ABCDに対して、四角形A'B'C'D'を描くときには、点A'の自由度2、点B'の自由度1、点C'の自由度0、までは三角形と同じです。点D'を決める時には、A'B'C'との位置関係でもう確定しているので、自由度0なので、自由度は合計3です。5角形でも、5個目の点は一通りにしか選べないので同様です。結局、向きのある平面図形であれば、形と大きさが定まっていれば、どんな図形でも自由度は3になります。

しかし、円の場合は話が違います。大きさが定まっている円の場合は、中心を描いた時点で確定するため、自由度は2になります。回転しても同じ円になるからです。


== 自由度と制約

平面上に、無関係に3つの点を取ると、2+2+2の合計6の自由度があります。しかし、三角形を描く際には、3つの合同条件によって、自由度が3減ります。つまり、6-3=3の自由度が残ることになります。

四角形を描くときには、4点を取るときの自由度は2+2+2+2=8ですが、合同条件が5つあるので、8-5=3の自由度が残ります。五角形を描くときには、5点を取るときの自由度は2+2+2+2+2=10ですが、合同条件が7つあるので、10-7=3の自由度が残ります。

三角形ABCに対して、それと合同な三角形A'B'C'は自由度3の図形であるといえます。


点A'は自由度2、点B'は自由度1、点C'は自由度0でした。つまり、三角形A'B'C'を描くために、2+1+0=3の自由度を下げたことになります。

AB=A'B'、BC=B'C'、CA=C'A'の3つの合同条件から定めました。


単純な平面図形の作図で例えます。例えば長方形はすべての角が直角という条件がある一方、正方形はそれに加えてすべての辺が同じ長さという条件があります。「好きな長方形」を描くのであれば、すべての角が直角になるように描けばよいですが、「好きな正方形」であれば、さらにすべての辺の長さも同じになるように描く必要があります。さらに、「5cmの正方形」であれば、その長さを5cmにする必要があります。いくつ条件があって、いくつ好きに決めていいのかは図形によってまちまちです。



== 作図への応用
実際に透視図を描くときには、*すべての点について半直線と投影面の交点を求めるようなことはほとんどなく*、いくつかの分かっている点や、自分で「好きに」決めた点を基準にもとに、投影面上で作図していくことが多いです。

どのようなときに「好きに」決めてよいかを知るには、図形と像の性質を熟知する必要があります。


