---
layout: base.njk
title: 初等幾何と解析幾何
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]


== 初等幾何と解析幾何

ここまでお膳立てしたことで、ようやく数学的、幾何学的な方法論を適用することができるようになりました。

幾何学とは形を扱う数学の一分野ですが、その方法論には大きく分けて二つのアプローチがあります。初等幾何学と解析幾何学です。

理想カメラによる像を求める方法も、大きく分けて初等幾何学的な方法と、解析幾何学的な方法の二つがあります。

== 解析幾何

解析幾何は、点に座標やベクトルなどを割り当て、その計算によって形を求める方法です。例えば平面上の点を、直交座標系を使って(x,y)のような変数の組で表してしまえば、それらの間の関係を式で表して計算（式変形）することで、図形問題を解くことができます。解析幾何の歴史は比較的新しく、17世紀のフランスの数学者ルネ・デカルトが座標の概念を発見したことによって創始されました。

解析幾何は問題を作図ではなく計算に落とし込むことができるので、初等幾何よりも本質的に強力なツールです。初等幾何で解ける *すべての* 問題は、解析幾何を使うことで必ず（場合によっては非常に簡単に）解くことができます。逆に、初等幾何では絶対に解けない問題があることも知られています。

一方で解析幾何を使う場合は、対象上の点をすべて座標で管理します。例えば視点を原点(0, 0, 0)の位置に置き、投影面をz=dの平面とします。このとき、点(x,y,z)の像は、(dx/z, dy/z)となります。このようにして点の座標をたくさん集めることで、像の形を数式で表すことができます。これは、コンピュータを使った数値計算との相性がよく、3DCGで広く使われています。実は3DCGによって得られる形は、理想カメラによる形と全く同じものになっています（レンズ歪みを再現するなどの特殊な効果をかけている場合は例外です）。

現代においては、複雑な状況を正確に作図する必要が生じた場合は3DCGを下書きに使うことが多いでしょう。手書きと3GCG、初等幾何と解析幾何でアプローチは全く違いますが、方法が違うだけで、3DCGでも手で作図するのと同じ（あるいはより正確な）像を得ることができます。

== 初等幾何

一方、初等幾何学は、点や線や図形の性質を公理によって定め、それを組み合わせて演繹的に様々な定理を生み出すものです。初等幾何の歴史は古く、紀元前300年頃のユークリッド幾何学の『原論』にまで遡ります。その後、数学、論理学の発達に従ってさらなる形式化が進み、現代はヒルベルトによって1899年に公理化したヒルベルト幾何学などが、扱いやすい初等幾何の基礎とされています。

NOTE: この「初等」は簡単という意味ではなく、解析（計算）を使わない、歴史的に古いといった意味と考えてください。合成幾何と呼ばれることもあります。

本質的に、初等幾何は解析幾何よりも不自由なツールです。初等幾何における「定規とコンパスで作図可能な点」は、代数で言う連立2次方程式の解で表される点に限られます。つまり、 *それ以上の複雑性を有する問題は、どんなに工夫しても作図では解けない* ことがわかっています。例えば、三次方程式の解や円周率πは二次方程式を組み合わせても表せない数なので、そのような値を座標に含む点は作図では表すことができません。

しかし、初等幾何は解析幾何よりも、*図形の性質をより視覚的、直観的に理解する* のに適しています。特に「*絵を描くために紙の上で作図をする*」「*結局どのような形になるのかを理解する*」という点においては、解析幾何を使わず、初等幾何の方法を使うことが非常に有益です。

先ほど定義した「理想カメラ」による像の取り方は、半直線と投影面の交点を求めるものでした。これ自体、初等幾何的な定義です。初等幾何を使って進める場合、ここを出発点に様々な初等幾何の定理を適用していくことで、像の形や性質を浮き彫りにしていくことができます。さらに、うまい工夫を重ねることで、像の形を一枚の紙の上で作図することも可能です。これは人間が手で絵を描くにあたって十分実用的であるため、深く考察されてきました。これが初等幾何を使ったアプローチです。

== 本書の立ち位置

「3DCGを使えば楽に同じものが得られるのなら、手書きの、初等幾何での、透視図法を学ぶ価値などないんじゃないか」、と思われるかもしれません。しかし、*手で作図すること、像の性質を理解すること* 自体に大きな価値があります。3DCGを使えば複雑な形の像でも簡単に得ることができますが、なぜそのような形になるのか、欲しい形を描くためにどのようなツールを使えばよいか、どこは正確に書く必要があってどこは適当に決めてよいか、そもそも3Dを使う必要があったのか、などを知らないままになってしまいます。

そのため、本テキストでは、極力初等幾何的な理解に落とし込むことを目標として進めます。

しかし、一部の分野で、どうしても計算が必要な場合には、解析幾何的な方法も使います。

また、3DCGは解析幾何的な方法で正確に「ガラス板をなぞる方法」の像を得ることができるので、積極的に記事中に3Dの図を挿入し、理解の補助とします。

== 幾何の公理と定理

初等幾何は点や線などの性質を公理によって定め、その演繹によって結論を導出します。

ヒルベルト幾何学の公理は、点、線、面の三種類の存在と、包含、中間、合同という三種類の関係を合わせた六つの原子概念が存在することを認めることから始まり、これらの関係を規定する一連の公理から構成されています。

以下のぺージを参照してください。
https://ja.wikibooks.org/wiki/%E5%B9%BE%E4%BD%95%E5%AD%A6%E5%9F%BA%E7%A4%8E%E8%AB%96/%E5%85%AC%E7%90%86

実は、公理系から平行線公理などを取り除くことで無限遠点の存在が認められる射影幾何学が構築できることが知られています。実は透視図法と射影幾何学はかなり相性がよいのですが、いきなりに理解するのが困難であるため、しばらくは射影幾何学でない普通の幾何学（ユークリッド幾何学）に基づいて透視図法を考えていきます。射影幾何学については、2-6ページから触れています。
