---
layout: base.njk
title: 「理想カメラ」の定義
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]

== 理想カメラの定義

ここからは、「ガラス板になぞる方法」を幾何学的に扱うために、前回の話をシンプルな、幾何学的なものに置き換えていきます。

「ガラス板になぞる方法」では、まずガラス板と視点を固定するのでした。幾何学的に言えば、ガラスは平面で、視点は（大きさを持たない数学的な意味での）点です。これを踏まえて、以下のように「理想カメラ」を定義します。なお、ここでいう「理想的」とは「最高の」とか「完全な」のような価値判断を含むものではなく、「想像上の」「もしそういうものがあったら話が簡単になってうれしいなぁ」程度の意味です。物理における「理想気体」と同じ「理想」と思ってください。

[.definition]
.定義（理想カメラ）
--
. 三次元空間中に平面を置き、投影面と呼ぶ。投影面上にない点を取って視点と呼ぶ。視点と投影面の組を「理想カメラ」と呼ぶ。
. 視点から投影面に向かって下ろした垂線を視軸と呼ぶ。視軸と投影面との交点を視心と呼ぶ。また、視点と投影面の距離、つまり視点と視心の距離を視距離と呼ぶ。
--

1は視点とガラス板を固定するための定義で、視点と投影面が定まれば「理想カメラ」が一意に定まることを意味しています。2は「理想カメラ」に対して定まる部分に対して便宜上の名前を与えているだけです。*図では便宜上、投影面を長方形で表していますが、実際は無限に広がる平面です。*

{% sketch "sketches/ideal-camera1" %}

なお、*ここで使っている呼称や記号は、あくまでもここで採用しているだけなので注意してください*。

////
.従来の命名との比較
[%collapsible]
====
図学における点や線の命名は、英単語を省略した2～3文字のアルファベットを採用するのが一般的です。例えば、視点は一般的にはeye pointを略したEPまたは、Station Pointを略したSPなどと書かれ、投影面はpicture planeを略したPPと書かれます。まだ登場していないものも含め、使われている記号を以下に列挙します。

[.table style="border-collapse: collapse; width: 100%; border: 1px solid black;"]
|===
| 日本語 | ここでの記号 | 図学 | 英語 | 日本産業規格

| 視点 | E | EP / SP | eye point / station point | O
| 投影面 | 投影面 | PP | picture plane | T
| 視心 | O | VC | visual center | C
| 消失点 | V | VP | vanishing point | V 
| 立点 | - | SP | station point | Sp
| 地平線 | - | EL | eye level | h
|===

どうでしょうか。これは偶然によるものですが、図学における記号体系では、Vの由来がvisualだったりvanishingだったり、Pがpointだったりplaneだったり、Sがstationだったりと、同じ文字の登場頻度が高くややこしいことになっています。また、異なる概念である視点と立点に両方SPが割り当てられる場合があるのは明らかに混乱のもととなります。特に、点であることを表すための「P」などはほとんど省略しても不便が無いため、ここでは削ることにしました。

また、このように1文字で表す最大のメリットは、一般的な幾何学の記法を使って直線や三角形を表記するときに現れます。幾何学では、点AとBを通る直線を「直線AB」、点A、B、Cからなる三角形を「△ABC」などと書きますが、このような記法をするにあたって、点や平面の名前が2文字だと不便です。

「視軸」は一般的には「光軸」と呼ぶことが多いですが、「光軸」は本来レンズカメラに対して使う用語であるため、ここでは「視軸」と呼ぶことにします。

逆に、地面の端を表す「地平線」や観測者の足元を表す「立点」の概念は、「地面」や「観測者」といった具体的なものを扱って初めて必要になるものです。これらはいずれも重力方向、つまり「下」を定めてしまうものであり、これに特別の名前を置くことは後述する「回転対称性」の理解の妨げとなるため、ここでは特別な記号を置かないことにしました。

投影面は重要な概念ですが、文字Pを割り当てると、他の意味で使いたいときに「点P,Q,R」を使えなくなってしまいます。点と異なり、面が三角形や直線を構成する記法に入ることはないので、逐一「投影面」と呼ぶことにします。

視心をCではなくOとしたのも、「点A,B,C」の組み合わせを今後も使うために、Cを避けたためです。視心は投影面の中心とみることができるので、Oは原点「origin」のOから取っています。
====
////

== 像の定義

次に、なぞって浮かび上がる形について考えます。画家が視点を固定して対象上の点Pなぞっているとき、点Pは画家の目から見てペン先と重なって見えています。これは、*光の直進性を考慮すれば*、画家の目とペン先、点Pがこの順で一直線上にあるはずです。そのような範囲でペン先を動かした軌跡が、なぞって浮かび上がる形です。これを踏まえて、「像」の作り方を以下のように定めます。

[.definition]
.定義（像）
--
. 空間中の点Xに対して、視点Eから点X方向へ延びる半直線が投影面と交わる点があれば、それを「Xの像」と呼ぶ。
. 空間中の図形Sに対して、S上にあって像が存在するすべての点の像を集めた投影面上の図形を「Sの像」と呼ぶ。
--

{% sketch "sketches/ideal-camera2" %}

この定義は、「ガラス板になぞる方法」の話を幾何学的に単純化したものです。これが「ガラス板になぞる方法」と *よく対応している* ことを確認してください。そして、この像を取る操作を「透視投影」と呼びます。規則的に立体を平面に変換する方法を、全般的に「投影法」と呼びます。「透視投影」は投影法の *一種* です。

注意深く読んだ人は、なぜ線分ではなく半直線なのか？と疑問に思ったかもしれません。

確かに、視点、ペン先、点Pの順に並んでいるのであれば、つまり視点Eと点Pの「間」にペン先を置くのであれば、半直線ではなく線分と投影面の交点を求めるのでも良さそうに思えます。しかし、ここを半直線にしたことで、視点、ペン先、点Pの順だけでなく、視点、点P、ペン先、の順で並んでいてもよいということになっています。つまり、投影面の手前にある点についても「像」を作れるように条件を緩くしています。

現実にやろうとするとモチーフにペン先が隠れてしまって難しいかもしれませんが、そういうことは考えず、投影面より手前の点についても像が取れるということにした方が「話が簡単になる」のでこのようにしています。理想カメラの「理想」は「そういうものがあったら話が簡単になってうれしいなぁ」という意味でしたね。

== 幾何学だけを考える

この対応関係を確認したことで、これからの興味は、「正確な形とは何か」「正しい見え方とは何か」*ではなく*、「理想カメラで様々な形の像を作るとどのような形になるのか」また、「その像をどのように作図することができるのか」という話題に移っていきます。問題をうまく単純化し幾何学的な話に話題をすり替えることで、より正確で複雑な議論ができるようになったわけです。

重大な視点の変換があったので、ここまでの議論をまとめます。「ガラス板になぞる方法」では、主観の介入なく形を描けるということ、「形を再現」できるなどのメリットがある反面、別の視点から見た時には大きくゆがんだ形になってしまうというデメリットもありました。しかし、そのような「『正確な形』とは何か」「理想カメラが本当に『正確な形』を表しているのか」といった問題についていつまでも議論していくとキリがないので、*一旦* 目をつむって、理想カメラを使って得られる像の形を考えていきます。

****
== なぜこれが「カメラ」なのか。

ところで、この幾何学的なセットアップを「カメラ」と呼ぶのには抵抗があると思います。なぜそのように呼ぶのでしょうか。

実はこのセットアップが皆さんがよく知る「カメラ」に非常に似ているからです。「『正確な形』とは何か？」において、「現代では写真をトレースするという方法もあり得ると言及しました。この方向からも考えてみましょう。

現実のカメラは、レンズを使って光を集めて像を結ぶものが一般的ですが、レンズには光の屈折を使った複雑なものであり、歪みやピントなどの問題もあるため、まじめに考えると非常に複雑なものになります。
そこで、ここではレンズを使わないカメラ、つまりピンホールカメラについて考えます。ピンホールカメラは、光が通ることができる小さな穴を持つ箱で、箱の中に投影面があるものです。ピンホールカメラで得られる像は非常に暗いため実用的ではありませんが、レンズカメラと違い、ピンボケやレンズのゆがみなどの厄介な問題がないので、思考実験としては簡単に扱うことができます。

これも「光の直進性」を考えて、図のように考えると、ピンホールカメラによって描かれる像は、ひっくり返っているだけで「ガラス板になぞる方法」で描いた形と全く同じものが描かれることがわかります。つまり、ピンホールカメラも「ガラス板になぞる方法」と同様に、対象の形を正確に再現することができるのです。この点で、ピンホールカメラは「理想カメラ」に非常に近い存在と言えるでしょう。

TODO: 図を入れる

現実のレンズカメラは、レンズの特性や構造によって、ピンホールカメラとは異なる像を結びますが、多くの場合、できるだけ「ピンホールカメラ」や「理想カメラ」に近い形の像が得られるように設計されています。レンズカメラと理想カメラの差異、つまりレンズカメラを単純化する際に無視した要素についても、後で補足します。

TODO: 補足ページを作ってリンク
****
