---
layout: base.njk
title: 理想カメラの対称性
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]


== いつ形が変化し、いつしないのか

具体的な操作に入る前に、理想カメラにおいて「どのような時に形が変化し、どのような時にしないのか」を知っておくと便利です。

中でも特筆すべきこととして、 *視軸に対する回転対称性がある* ことが挙げられます。この事実は後に説明する、回転体の像や三点透視図法を理解する際に非常に役立ちます。

== 合同と相似

順を追って説明します。まず、「同じ形」について、言葉の意味をはっきりさせておきます。一口に同じ形、といっても、というには二種類あります。形と大きさがおなじ「合同」と、形が同じだけども大きさが同じとは限らない「相似」です。

[.definition]
.定義（合同）
--
図形AとBが、平行移動、回転、鏡写しのいずれかの操作をすることで重ね合わせることができるとき、AとBは「合同である」といいます。
--

[.definition]
.定義（相似）
--
図形AとBが、平行移動、回転、鏡写し、拡大縮小のいずれかの操作をすることで重ね合わせることができるとき、AとBは「相似である」といいます。
--

平行移動とはスライドのことです。合同であるとは、形をスライド、回転、鏡写しにすることで重ね合わせることができることを意味します。相似であるとは、形をスライド、回転、鏡写しに加えて拡大縮小することで重ね合わせることができることを指します。

透視図法の像の形について考えると、立体図形AとBが合同でも、その像A'とB'が合同とは限りません。同じ形でも、図形の位置や向き、見る位置や向きを変えると形が変わることは、経験的によく知っていると思います。像の形はカメラを動かせば変わるのが当然なのです。

しかし、いくつかの限られた条件で、同じ形になることがあります。そのような状況について知っておくと、分かりずらい状況を簡単な状況に置き換えたり、すでに知っている問題に落とし込むことができます。

== 視点と投影面と対象の位置関係

まず、簡単に理解できることとして、*カメラと対象の位置関係を固定した状態であれば* 、それらを空間中でどのように動かしても、像の形は変わりません。これは当たり前ですね。いまは純粋に幾何学的なことを考えているので、背景とか重力のような、カメラの向きを特定する要素は何もないことに注意してください。*像の形は視点と投影面と対象の位置関係だけで決まる* ので、カメラと対象を一緒に動かしても、像の形は変わらないのです。

{% sketch "sketches/symmetry-of-camera", {"mode":"random", "whatToMove":"both"} %}

== 視軸に対する回転対称性がある

ここからは、カメラと対象を別々に動かすことを考えていましょう。

まずは対象を固定して *視軸を中心に* カメラを回転させてみます。が、こうしても、カメラを決定するのに必要な要素、つまり視点と投影面は何も変わっていませんね。なので、像の形は変わらないはずです。便宜上長方形の領域を定めて、それを切り出して描いているだけで、実際は無限に広がる平面であったことに注意してください。

{% sketch "sketches/symmetry-of-camera", {"mode":"roll", "whatToMove":"camera"} %}

同じことの見方を変えます。カメラを固定し、*対象を、視軸を中心に対象を回転させた時、その像は視中心を中心に回転するだけで、それ以外の変化は起きません*。これを「回転対称性がある」と表現します。この対称性は、透視図法を考える上で非常に便利な性質です。考えるのが難しい状況も、視軸を中心に回すことで簡単な状況になるのなら *分かりやすい向きに回転させて考えてから、元の向きに戻せばよい* のです。

{% sketch "sketches/symmetry-of-camera", {"mode":"roll", "whatToMove":"objects"} %}

NOTE: 本テキストで単に回転対称といった時には、任意の角度で回転させても重なることを指します。つまり、2回対称や3回対称ではなく、無限回対称のことを指します。

== 並進対称性がない

一方で、*並進対称性がない* ことには注意が必要です。対象を固定してカメラを前後や左右に移動させると、あるいはカメラを固定して対象を前後や左右に移動すると、対象と視点との位置関係が必ず変化します。なので、像の形も変化すると考えるのが自然です（そして実際に変化します）。左右に移動した時はもちろん、前後に移動した時にもわずかに変化していることに注目してください。

{% sketch "sketches/symmetry-of-camera", {"mode":"parallel", "whatToMove":"camera"} %}

== 球対称性もない

こんどは対象を固定し、視点を中心にカメラの向きを変えることを考えてみます。対象と視点が固定されていれば、*物体の重なり方は* 変化しません。隠れていたものが現れたり、見えていたものが隠れたりはしていませんね。これは、二点の像が重なるか否かは視点と対象の位置関係のみによって決まるため、投影面は関係なく、視点を動かさない限り、重なり方は変わらないからです。

しかし視点を固定していても、カメラの向きを変えれば、つまり、投影面を面を動かせば、像の形は変化します。重なり方が変化しないだけでいっても、全体の形が歪まないとは限らないので、歪むように変形します。これは *視点に対する球対称性がない* ということができます。

実際にやってみると以下のようになります。少々分かりにくいですが、注意深く見るとただの平行移動ではなく、変形を伴っています。

{% sketch "sketches/symmetry-of-camera", {"mode":"pan-tilt", "whatToMove":"camera"} %}

TODO: やや分かりにくいので図を入れたい

このような話をすると、「カメラの向きを変えただけで像が変わるのはおかしい」「球対称性があるはずだ」などと考え、「球面に投影されていると考えるのが自然だ」とか、果ては「網膜は球体に歪んででいるから……」とか言う人がたくさんいます。しかし、今はそのような話はしていません。先ほど定義したような「理想カメラ」を動かしたときに何が起きるか、を考えているのです。そして、「理想カメラ」の定義と「ガラス板になぞる方法」や「ピンホールカメラ」との間に「良い対応」があること、そう定義することで「再生」ができるというメリットはすでに述べたとおりです。

まだ疑わしい人は、手元のスマホやカメラを起動して、レンズを中心に向きを変えてみてください。スマホのカメラは理想カメラではありませんが、ある程度理想カメラを近似した近いものになっているはずです。なので、像が平行移動するだけでなく形が変わることを確認できるはずです。

ちなみに、球面の投影面などを考えれば球対称にできるのではないか、と考える人もいますが、残念ながらそれは不可能です。球面のキャンバスを用意してその内側に絵を描くのであればまあ可能ですが、最終的に平面に描く以上は、カメラの回転を平面上の平行移動に対応させることはできません。「地球儀を平面の世界地図にすることができない」のと同じ話で、平面に描く以上は、どこかに必ず歪みが出るのです。詳細は、非平面投影のページで扱います。

