---
layout: base.njk
title: 透視図法の準備
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]

////
結論　
「正確な形」を描く方法は一つではない。
その一例として「視点を固定してガラス板になぞる」方法を考える。
これは「モチーフと重なる」「形が再現する」というメリットと、「視点をずらすと形が歪む」というデメリットがある。
////

== 「正確な形」とは何か？

形を正確に描写することは重要でしょうか。形が「正確に」描けている絵は、美術において「客観的」「冷静」などと評されることがあります。逆にデフォルメを効かせた絵は「感覚的」とか「勢いがある」とか評されることがあります。伝統的なリアリズムにおいては、前者はポジティブな評価で後者はネガティブな評価とされることが多いように思いますが、写真の登場以降は作風次第でどちらもポジティブな評価として受け入れられるようになっています。

しかし、ここでは「客観的」で「正確な」形に絞って議論を進めます。とはいっても、そもそも、「正確な形」とは何でしょうか。

例えば、画家が人物モデルを雇って絵を描いたとします。画家は「何度も見比べながら描いたので正しい」と思っていますが、それを見たある人は、「もっと丸い気がする」と言いました。別の人は「もっと鼻が高い気がする」とか言うかもしれませんし、モデル本人が見たら「私はもっと美形なはずだ」とか言うかもしれません。さて、このとき、誰が言っていることが正解か、判別することはできるのでしょうか。主観や感覚が介在すること無く「正確な形」を描くことはできるのでしょうか。

平面から平面に「正確な形」を写すのであれば、そんなに難しい問題ではありません。紙を重ねた時にぴったり重なれば全く同じ形をしていると確認できるでしょうし、そのような形を得るにはトレーシングペーパーやカーボン紙などを使ってなぞればよいでしょう。しかし立体を平面に描くにあたっては、「正確な形」を定義するのは難しいです。

現代であれば、写真と重ねてみればいい、写真をなぞればいい、と考えるかもしれません。しかし、写真に写った形が「正確な形」であるというのはどうして保証されるのでしょうか。

== 「なぞる」方法

ここで「正しい形」を描くための、ある意味で最も確実な方法を提案します。

まず、透明なガラス板を自分と対象の間に固定します。そして特定の場所に視点を固定して、見えた対象の形をそのまま、ガラス板上にペンで「なぞる」ようにして形を描くのです。

そんなにうまくいくはずがない、と思う人もいるでしょう。ここで、二つのコツがあります。まず、片眼で見ること。もう一つは目の位置が絶対に動かないようにすることです。特に後者は大事で、単に同じ場所に立つ、同じ椅子に座るだけでは体がブレてしまうので、固定したのぞき穴から覗くとか、顎を机に置くとか、何らかの方法で目の位置を完璧に固定する必要があります。この二つを守って、ある程度の時間と忍耐力を費やせば、きっと正確に形をなぞることができるでしょう。

ただし、これはあくまでも「*ある意味で正しいと呼べそう* な形」を得る方法の *ひとつ* に過ぎないことを忘れないでください。正確といっても、まったく別の方法（例えば、現物を定規で測って云云とか）を採用すればまったく別の形になるでしょう。しかし、とりあえずはこの方法に立って話を進めます。

== 「重なる」と「再現」、そして「歪み」

さて、先ほどの方法を用いて、どうにか頑張ってガラス板上でペンを動かしつづけたことで、その固定した視点から見ると完璧に重なって見える絵が *描けたとします*。

まずこれは、完璧に重なっているという点で「正確な形」を描いていると言えるでしょう。カーボン紙を使って平面から平面に移すのと同様、「重ねれば重なる」ことをもって「正確である」とするのは強い納得感があると思います。また、この方法は「見えた形をなぞる」という極めて単純な作業によって成り立っています。ここには画家の主観も介在しないし、「見比べる」とか「目測で測る」といった技術も必要ありません。誰がやっても（どのような程度仔細に書き込むかなどの差異は除いて、あくまで「形」だけを考えれば）ほぼ同じ結果になるという点でいえば、極めて「客観的」とも言えそうです。

そして、この方法はある一つの大きなメリットがあります。それは形を「再現」することができる、ということです。どういうことでしょうか。

ガラス板上に完璧に形をなぞれたとして、その形を下絵としていい感じにリアルな色を塗って、その後モチーフを取り除いたとします。そこに友達を呼んできて、描いた時と同じ視点から片目で、完成した絵を見てもらいます。すると、友達は、まるで対象がそこにあるかのように（少なくとも形については全く同じ形を）見ることができるでしょう。人間は片目では奥行きを区別できず、重なるかだけを判定できるとしたら、誇張した言い方をすれば、*本物と区別できない* 絵が出来上がるわけです。これが「再現」です。これは、遠近法の目的であった「立体感を錯覚させる」に十分に近いものと言えるでしょう。

一方、デメリットもあります。視点を固定して描いた分、*鑑賞者の視点が変わると全く違う形に見えてしまうのです*。特に、ガラス板の外周部では（正確に言えば視点から遠くなるほど）、外側に引き伸ばされるように歪んで見えることが知られています。しかし、これはある意味当たり前ともいえます。視点を動かしても正確に見えるというのは、もはや絵ではなく立体物でないとあり得ない話です。どのような方法を取っても、どこかに必ず歪みが出ます。

CAUTION: ここで「歪んで見える」というのは、描いたのと別の視点から見ているときの話です。*描いたときの視点から見れば*、どんなにガラス板が大きくても、もっと言えばガラス板が画家とモチーフの間に斜めに配置されていたとしても、歪んで見えることはありません。ある視点から完璧に重なるように描けば、その視点からは完璧に重なって見えるし、完璧に形が再現する、つまりそのように描いたらそうなるという当然の話なのですが、ここは要注意です。


== 現物は必要か

また、この方法の別のデメリットとして、「現物とガラス板を用意しないといけない」「視点や対象、ガラス板が動いてしまうと形をなぞることができない」などといった問題もあります。確かに、ガラス板を用意するのは大掛かりですし、想像上のものや高価なもの、動き回るものを描くのに使えないとなると、これは致命的です。

これらを回避するために、実際にこの「ガラス板になぞる」を行わずとも、それと行ったのと同じ形を予想し、描く方法があれば得る方法があればいいなぁ、と思うのは自然なことです。そのために幾何学が強力な道具となります。

これは現実に存在する複雑な物体を描くことを一旦諦めて幾何学的な形に限定することで、思考と計算、紙上の作図によって、正確になぞった形を得ることが可能となります。（そこから現実に存在する形への応用については、<<index.adoc>> で述べたとおりです。

次はページからは、これを幾何学の問題に落とし込むために、「ガラス板になぞる方法」を幾何学的に表していきます。

== 実在の例

ここまでで考えてきたのはあくまで思考実験でしたが、現実に対応するものは存在するでしょうか。


画家は歴史上、様々な方法や道具を使って「正確な形」を描こうとしてきました。実際に視点を固定してガラス板を直接なぞったという例は確認できませんでしたが、今回考えた「ガラス板になぞる方法」に近いことを実行した例はいくつかあります。例えば、ルネサンスの画家ブレネルスキが行った目を固定してグリッドを移していく方法、「デスケル」というグリッドのある透明な板を覗き込む方法があります。どちらもグリッドを使っているという点では間接的ですが、この「ガラス板になぞる方法」に近いことを実現する方法と言えるでしょう。
また、カメラオブスキュラというピンホールカメラのような道具を使って、モチーフの像を壁などに投影し、その像をなぞるという方法もあります。これは直接視点を置いているわけではありませんが、ガラス板になぞる方法と同様のものが得られます。

次に、再現について。現実に鑑賞者の目を固定するようなことは難しいですが、不可能ではないです。鑑賞するためののぞき穴を作ってそこから見るようにする方法があり、ブレネルスキはこの方法で観客を驚かせました。
あるいは絵を大きく描き、鑑賞者が特定の位置に立つように誘導する（絵が十分に大きければ、身長差や体の揺れなどの小さなずれは無視できます）などの方法があります。これはトリックアートなどでよく使われる方法です。