---
layout: base.njk
title: 平面の像
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]

== 連続性
ここでもヒルベルト公理から脱却し、微分幾何学の概念が必要になります。

[.definition]
.定義（曲線）
--
実数xに対して、点f(x)が連続に変化するとき、点f(x)の集合を「曲線」と呼ぶ。
--

NOTE: 直感的には、曲線は「繋がった線」のことです。この定義に従うと、円や直線、線分はすべて曲線です。「曲」という字が入りますが、直線や線分、折れ線などを除外するわけではないことに注意してください。

[.definition]
.定義（接線）
--
曲線C上の点Pに対して、点QをC上で動かしてPに限りなく近づけていったとき、Qをどちらから近づけても同じ直線lに限りなく近づくとき、lを「曲線Cの点Pにおける接線」と呼ぶ。
--
NOTE: 曲線が折れ曲がっているような場所では接線が定義できない。

[.definition]
.定義（接線連続）
--
曲線上のある区間において、端点を除く区間中のすべての点において接線が定義できることを接線連続と呼ぶ。
--

[.definition]
.定義（接する）
--
点Pにおいて曲線CとDが同じ接線を持つとき、曲線CとDは点Pにおいて「接する」と呼ぶ。
--

NOTE: 直感的には曲線に角がなく、滑らかであることを表す概念です。

これを踏まえると、以下のような定理が成り立ちます。

[.theorem]
.定理（接線の保存）
--
視点Eを通らない直線lが曲線Cに点Pで接しているとき、直線lの像は曲線Cの像に点Pの像で接する。
--

[.theorem]
.定理（連続性の保存）
--
接線連続な曲線Cについて、Cのすべての接線が視点を通らないとき、Cの像も接線連続となる。
--
[.proof]
--
定理（接線の保存）より、曲線Cの各点における接線の像は曲線Cの像の接線となる。したがって、接線連続性が保たれる。
--

NOTE: 直感的には、滑らかな曲線は滑らかな像を与えるという主張です。ただし接線が視点を通る場合を除外していることに注意してください。そのような点においては、像に角が生まれる場合があります。


== 一般の曲面に関する定理

さらに、曲面について考えると、応用範囲が広がります。滑らかな曲面は球や円柱だけでなく、例えば、コップの表面や人間の肌などいたるところで見ることができます。これらの曲面に対して、以下のような定理が成り立ちます。

[.definition]
.定義（曲面）
--
--

[.definition]
.定義（接面）
--
--

[.definition]
.定義（回り込み）
--
視点をEとする。
曲面S上の点Pに対して、直線EPがSの接線となるとき、「（Eから見て）曲面Sは点Pにおいて回り込む」と呼ぶ。
曲面SがEから見て点Pにおいて回り込むような点Pの集合を「（Eから見て）曲面Sが回り込む輪郭」と呼ぶ。
--

物体の輪郭には回り込む輪郭と回り込まない輪郭があります。回り込まない輪郭は曲面が接面連続でない、つまり面が折れて辺が生じている場所にできます。
例えば、球の輪郭はすべて回り込む輪郭になりますが、円柱は側面部分のみが回り込む輪郭で、断面部分に生じる輪郭は回り込まない輪郭です。

[.theorem]
.定理（回り込む輪郭の滑らかさ）
--
曲面Sが滑らかな時、Sが回り込む輪郭は、いくつかの滑らかな曲線となる
--



[.theorem]
.定理
--
ガウス曲率が0の滑らかな曲面の回り込む輪郭は直線となる。
TODO: 特定の例外を除く。
--
[.proof]
--

--
円柱面や、円錐面、折れていない紙面などの回り込む輪郭は、必ず直線であると言えます。

[.theorem]
.定理（曲面上の曲線と輪郭が接する）
--
滑らかな曲面S上に滑らかな曲線Cがあり、曲線C上に点Pがある。
点Pにおける曲線Cの接線が視点を通らず、曲面Sが点Pにおいて回り込むとき、曲線Cの像は点Pの像において曲面Sが回り込む輪郭の像と接する。
--
[.proof]
--
点Pにおける曲線Cの接線をlとする。lは点Pにおける曲面Sの接線のひとつである。仮定よりlは視点Eを通らない。
曲面Sは点Pにおいて回り込むので、直線EPは点Pにおける曲面Sの接線のひとつである。したがって、lとEPから点PにおけるSの接面αが一意に定まる。

一方、Pは滑らかな輪郭上の点である。定理（回り込む輪郭の滑らかさ）より、Pにおける回り込む輪郭の接線mが一意に定まる。
回り込む輪郭はS上の滑らかな曲線なので、接線mは接面α上にある。

接面αはEを通る平面なので、定理（平面の像）より、αの像はαと投影面の交線であり、lの像、mの像もその交線上にある。■
--

この定理から、例えば、「回転体の断面の像は回転体の輪郭に接する」「円柱の輪郭は（回り込まない輪郭もふくめて）接線連続である」などの主張が導けます。


