---
layout: base.njk
title: 点の像
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]

== 点の像

点の像の定義を再確認します。
[.definition]
.定義 （点の像）
--
空間中の点Xに対して、視点から点X方向へ延びる半直線が投影面と交わる点があれば、それを「Xの像」と呼ぶ。
--

== 像の定義域

定義には交わる点が *あれば* という留保がついています。実際、どのような時に点の像が存在するのでしょうか。以下、視点から投影面方向を「前」、その反対方向を「後ろ」と呼ぶことにします。

まず、点が投影面より「前」にある場合、これは視点と点の間に投影面があるので、半直線は必ず投影面と交わり、点の像が存在します。

点が投影面より「後ろ」にある場合は、注意が必要です。視点から点に向かって伸ばした半直線が、投影面に近づいていくのか、平行なのか、遠ざかっていくのかで区別する必要があります。投影面に近づいていく場合は、半直線を伸ばしていけばいずれ投影面と交わるので、点の像が存在します。平行な場合と遠ざかっていく場合は、いくら半直線を伸ばしても投影面と交わらないので、点の像は存在しません。

結局、「投影面に平行で視点を通る平面」が像が存在するか否かの境界になっていることが分かります。この面上より前側に点があれば点の像が存在し、この面上やこの面より後ろ側に点があれば、点の像は存在ません。この「点の像が存在する範囲」を、投影の「定義域」と呼びます。

この *「投影面に平行で、視点を通る平面」は、定義域とそうでない領域の境界になる* 重要な概念なので、本テキストでは「臨界面」と呼ぶことにします。

[.definition]
.定義 （臨界面）
--
理想カメラにおいて、投影面に平行で視点を通る平面を「臨界面」と呼ぶ。
--

[.theorem]
.定理（像の定義域）
--
臨界面に対して、投影面と点Pが同じ側にあれば、またその時に限り、点Pの像が一意に存在する。
--

実際にやってみると以下のようになります。長方形はあくまでも平面を示すためのもので、投影面は無限に広がっていることを忘れないでください。
像が長方形をはみ出してはるか遠くに行っていたとしても、「ある」ことには変わりありません。

{% sketch "sketches/image-of-point" %}

一般的に、点の像を求めるためには視点から点に伸びる半直線を考え、それと投影面の交点を求める必要があります。これは結構大変で、それを簡単にするための様々な定理と作図法をこれから学んでいきます。

しかし、点が投影面上にある場合は、非常に話が簡単です。なぜなら、視点から投影面上の点に伸びる半直線と投影面との交点は、その点自身になるからです。つまり、点の像はその点自身になります。

[.theorem]
.定理（投影面上の点の像）
--
点Pが投影面上にある場合、その点の像P'はP自身である。
--
