---
layout: base.njk
title: 点の像
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]

== 点の像

点の像の定義を再確認します。
[.definition]
.定義 （点の像）
--
空間中の点Xに対して、視点から点X方向へ延びる半直線が投影面と交わる点があれば、それを「Xの像」と呼ぶ。
--

== 像の定義域

定義には交わる点が *あれば* という留保がついています。実際、どのような時に点の像が存在するのでしょうか。以下、視点から投影面方向を「前」、その反対方向を「後ろ」と呼ぶことにします。

まず、点が投影面より「前」にある場合、これは視点と点の間に投影面があるので、半直線は必ず投影面と交わり、点の像が存在します。

点が投影面より「後ろ」にある場合は、注意が必要です。視点から点に向かって伸ばした半直線が、投影面に近づいていくのか、平行なのか、遠ざかっていくのかで区別する必要があります。投影面に近づいていく場合は、半直線を伸ばしていけばいずれ投影面と交わるので、点の像が存在します。平行な場合と遠ざかっていく場合は、いくら半直線を伸ばしても投影面と交わらないので、点の像は存在しません。

結局、「投影面に平行で視点を通る平面」が像が存在するか否かの境界になっていることが分かります。この面上より前側に点があれば点の像が存在し、この面上やこの面より後ろ側に点があれば、点の像は存在ません。この「点の像が存在する範囲」を、投影の「定義域」と呼びます。

この *「投影面に平行で、視点を通る平面」は、定義域とそうでない領域の境界になる* 重要な概念なので、本テキストでは「臨界面」と呼ぶことにします。

[.definition]
.定義 （臨界面）
--
理想カメラにおいて、投影面に平行で視点を通る平面を「臨界面」と呼ぶ。
--

[.theorem]
.定理（像の定義域）
--
臨界面に対して、投影面と点Pが同じ側にあれば、またその時に限り、点Pの像が一意に存在する。
--

実際にやってみると以下のようになります。長方形はあくまでも平面を示すためのもので、投影面は無限に広がっていることを忘れないでください。
像が長方形をはみ出してはるか遠くに行っていたとしても、「ある」ことには変わりありません。

{% sketch "sketches/image-of-point" %}

一般的に、点の像を求めるためには視点から点に伸びる半直線を考え、それと投影面の交点を求める必要があります。これは結構大変で、それを簡単にするための様々な定理と作図法をこれから学んでいきます。

しかし、点が投影面上にある場合は、非常に話が簡単です。なぜなら、視点から投影面上の点に伸びる半直線と投影面との交点は、その点自身になるからです。つまり、点の像はその点自身になります。

[.theorem]
.定理（投影面上の点の像）
--
点Pが投影面上にある場合、その点の像P'はP自身である。
--

== 図形の像

図形の像についても定義を確認します。

[.definition]
.定義（図形の像）
--
空間中の図形Sに対して、S上にあって像が存在するすべての点の像を集めた投影面上の図形を「Sの像」と呼ぶ。
--

これはガラス板上でペン先を動かす例に対応しているのでしたね。しかし、「すべての点」というのが厄介です。無数の点がある図形に対して、この方法をいちいち適用していくことはできません。

直感的には、図形上全体を動く点Pを取って、視点EからPに伸びる半直線EPを動かしていったときに、半直線がスイープする範囲を考えると分かりやすいと思います。もっとラフに言うと、EからP全体をなぎ払うようにビームを打った時に、そのビームに巻き込まれるような領域をまず考えます。その領域を投影面で切った断面を考えると、図形の像が得られます。

TODO: 図を入れる

== 厳密な証明

厳密に図形の像を求めるためには、その像に含まれる必要十分条件を示すことで、像を特定することができます。

[.theorem]
.定理（図形の像の必要十分条件）
--
視点をEとする。図形Sと、投影面上の図形S'について、以下の二つをともに満たす時、S'はSの像となる。

(1) S上の任意の点Pについて、半直線EPと投影面との交点が存在するとき、それはS'上にある。 +
(2) S'上の任意の点pについて、半直線EpとSとの交点が存在する。
--
[.proof]
.厳密な証明
--
結論から同値変形して示す。

Sの像がS'である。 +
⇔ 任意の点Pとpについて、PがS上にあって、pがPの像であるとき、またその時に限り、点pがS'上にある。

順と逆をそれぞれ同値変形する

任意の点Pとpについて、PがS上にあって、pがPの像であるとき、点pがS'上にある。 +
⇔ S上の任意の点Pについて、ある点pがPの像であるとき、点pはS'上にある。 +
⇔ S上の任意の点Pについて、その像pが存在するならば、点pはS'上にある。 +
⇔ S上の任意の点Pについて、半直線EPと投影面との交点が存在するとき、それはS'上にある。...(1)

任意の点Pとpについて、点pがS'上にあるとき、PがS上にあって、pがPの像である。 +
⇔ S'上の任意の点pについて、ある点PがS上にあって、pがPの像である。 +
⇔ S'上の任意の点pについて、pを像とする点PがS上に存在する。 +
⇔ S'上の任意の点pについて、半直線EpとSとの交点が存在する。...(2)

したがって、(1)かつ(2)とSの像がS'であることは同値である。■
--

(1)はともかく、(2)は直感的な像の取り方と逆向きになっていることに気を付けてください。(1)はS'がSの像全体を覆えていることを、(2)はS'がSの像からはみ出していないことを確認していて、両方を確認することではじめて一致したと言えます。

たとえば以下の例では、図形Sの像はS'ではありません。点AはS上の点であり、半直線EAが投影面との交点aを持つにもかかわらず、そのaがS'上にないので、(1)を満たしていません。また、点bはS'上の点ですが、半直線EbとSとの交点が存在しないので、(2)も満たしていません。したがって、S'はSの像ではありません。逆に、S'がSぴったりSの像であることを確認するには、このような点がどちらもないことを確認すればいいのです。

{% sketch "sketches/image-of-shape" %}

それと、以下の定理を示しておきます。

[.theorem]
.定理（部分の像）
--
SとTを空間中の図形とする。SがTの部分であるとき、Sの像はTの像の部分である。
--

[.proof]
.証明
--
Sの像をS'、Tの像をT'とする。SがTの部分であるとき、S上の任意の点Pについて、PはT上の点でもある。定義（図形の像）より、Pの像pはS'上にあると同時にT'上にもある。したがって、S'はT'の部分である。■
--

== 「図形」と「図形の像」を区別する

これからは、「図形」とその「像」をはっきり区別して書いていきます。絵を描くときに画面の上に現れるのは主に後者で絵を描くときはそれをもとの立体図形と同一視することもあるので混同しやすいのですが、これらは全然違うものなので注意してください。

例えば、「立方体」は空間中に存在する立体図形なのに対して、「立方体の像」は投影面上に現れる図形で、四角形だったり六角形だったりします。全然違いますよね。

立方体だったら「立方体を描く」といってもまあ立体は平面に入らないので「立方体の像を描く」の意味だろうなぁと察することができるかもしれませんが、平面図形の時には重大な混乱が起きます。例えば「円を描く」といったときに、空間中に存在する円に対してその「円の像」を描いているのと、投影面上にある「円」を描いているのとでは全然違います。（「描く」という言葉がすでに「平面図形そのものを描く」と「像を描く」の両方の意味を持ってしまっているのも一因です。）

（本テキストではまだ扱っていませんが）絵を勉強したことがある人は「平行な線は消失点で交わる」とか聞いたことがあると思いますが、幾何学的には平行線は交わらないので、ちんぷんかんぷんですね。これは「平行線の像」の話をしているのです。

なので、像の話をしているときは必ず「○○の像」と書くことにします。記号では多くの場合、図形Sの像は図形S'のように、図形の名前に「'」をつけて表すことにします。点の像についてはこの運用だと煩雑なので、点Pに対してpのように小文字にすることが多いです。

ただし、小文字は「直線l」などでも使うので、小文字だからと言って点の像とは限りませんし、「像である」以外の意味で'を使うこともあります。どちらも暗黙に使うことはせず、「点Pの像がpであるとき…」や「図形Sの像がS'であるとき…」のように明示的に書くので安心してください。


