---
layout: base.njk
title: 直線の像
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]


== 直線の像

前回は線分の像を考えましたが、今回は直線の像を考えます。直線は無限に長いので、これを考えると線分を好きなだけ「伸ばす」ような操作を考えることができるようになります。直線は無限に長いのでイメージするのが難しいですね。しかし、点Aと点Bの像がそれぞれaとbであったときに線分ABの像が線分abでしたが、直線ABの像も直線abとなるでしょうか。

== 直観的な理解

今回も直観的に予想してみましょう。

直線上全体を動く点Pを取って、視点EからPに伸びる半直線EPを動かしていったときに、半直線がスイープする（なぎ払う）領域をまず考えるとよいのでしたね。今回直線lに対して、Eからl全体をなぎ払うようにビームを撃つと、180度広がりそうですね。Eを通りlに平行な直線を境界として、それよりl側の範囲全体がなぎ払われることになりそうです。このような領域を、半平面と言います。

この領域を投影面で切った断面を考えると、直線の像が得られます。半平面を投影面で切ると、境界と投影面が平行でなければ半直線になりそうです。

さらに、投影面とlが平行でないときには、必ずその交点Aがありますね。Aの像はA自身になるので、lの像に含まれるはずです。ここまでを定理にしてみます。

[.theorem]
.定理（投影面と平行でない直線の像）
--
視点をEとする。Eを通らず、投影面と平行でない直線lの像は、EV//lとなるような投影面状の点V、lと投影面との交点をAとして半直線VAとなる。
--

NOTE: ここでは端点を含まない形での半直線の定義を採用しています。つまり、V自身はlの像には含まれません。

TODO: スケッチを入れる

[.proof]
.簡易的な証明
--
(1) 定理（図形の像の必要十分条件）を用いて示す。 +
E,l,V,Aは同一平面上にあるから、この平面上の図を描いて以下の二点を確認する。 +
[1] 直線l上の任意の点Pについて、直線VAと半直線EPの交点pがあるとき、pが半直線VA上にある。 +
[2] 半直線VA上の任意の点pについて、半直線Epは直線lと交わる。 +
よって示された。■

(2) Eを通りlに平行な直線はlのみであるため、Vはl上にある。 +
l上でEに対してV側にある点Pについて、半直線EPと半直線EVは一致するため、半直線EPと投影面の交点はVになる。■
--

TODO: 図を入れる

[%collapsible]
.厳密な証明
====
これも図を使わずに証明できます。まず「半平面」「直線に対する同じ側」を以下のように定義すると便利です。

[.definition]
.定義（直線に対する同じ側、反対側）
--
平面π上に直線lと、l上にない点A,Bがあって、lと線分ABが交わるとき、「平面π上で直線lに対してAとBが反対側にある」という。

AとBが同一であるか、lと線分ABが交わらないとき、「平面π上で直線lに対してAとBが同じ側にある」などという。
--

[.definition]
.定義（半平面）
--
平面π上の直線lとl上にない点Aについて、π上でlに対してAとPが同じ側にあるような点Pが属する図形を「平面π上でlに対してA側の半平面」と呼ぶ。
--

「同じ側」「半平面」には以下のような性質があります。これらは定義と、パッシュの公理から簡単に示せるでしょう。

[.theorem]
.定理（平面上での同じ側の推移性）
--
直線lと点A,B,Cが同一平面上にあって、lに対してAとBが同じ側にあり、かつ、lに対してBとCが同じ側にあるとき、lに対してAとCも同じ側にある。
--

[.theorem]
.定理（半平面の凸性）
--
平面π上の直線lに対して、点AとBが同じ側にあるとき、AとBを結ぶ線分AB上の任意の点もAと同じ側にある。
--

[.theorem]
.定理（半直線から半平面への拡大）
--
平面π上において、点Pが直線m上にあり、点Aが直線m上にないとき、半直線PA上にBがあるならば、平面π上で直線mに対してもAとBが同じ側にある。
--

これらの準備をすると、以下のような証明が描けます。

[.proof]
.厳密な証明（投影面と平行でない直線の像）
--
AとBが同一点である場合は定義（平面上の同じ側、反対側）より成り立つ。

同一点でない場合、l上でAとBが同じ側にあるということは、線分AB上に点Pがないことを意味する。lとmの交点はPのみであるから、線分ABはmと交わらない。定義（平面上の同じ側、反対側）より、π上でmに対してAとBが同じ側にある。■
--

これらを利用すると、定理（投影面と平行でない直線の像）は以下のように示せます。

[.proof]
.厳密な証明
--
(1) +
E,l,V,Aは同一平面上にある。α上の任意の点や線について、投影面との交点があれば、直線VA上にある。 +
定理（図形の像の必要十分条件）を用いて示す。以下、「同じ側」はα上でのことだけを考える。

[1] 直線l上の任意の点Pについて、直線VAと半直線EPの交点pがあるとき、pが半直線VA上にあることを示す。

A≠Pのとき、EV//APより、AとPは直線EVに対して同じ側にある。A=Pの時も自明に直線EVに対して同じ側にある。 +
pは半直線EP上にあるため、定理（半直線から半平面への拡大）より、Pとpは直線EVに対して同じ側にある。 +
したがって、点A,P,pはいずれも、直線EVに対して同じ側にある。 +
定理（半平面の凸性）より、線分Ap上にVはない。pは直線VA上にあるから、pは半直線VA上にある。

[2] 半直線VA上の任意の点pについて、半直線Epが直線lと交わることを示す。

まず、直線Epと直線lが平行ではないことを背理法で示す。 +
もしEpとlが平行であれば、Eを通りlに平行な直線はEVしかないので、EV=Ep +
EVと投影面との交点はVしかないので、V=p +
これはpが半直線VA上にあることに反する。 +
したがって、直線Epと直線lは平行ではない。 +

さらに、Epとlは同一平面にあるため交わる。この交点をPとする。

次に、Pが半直線Ep上にあることを示す。 +
A≠Pのとき、EV//APより、AとPは直線EVに対して同じ側にある。A=Pの時も自明に直線EVに対して同じ側にある。 +
pは半直線VA上にあるため、定理（半直線から半平面への拡大）より、Aとpは直線EVに対して同じ側にある。 +
したがって、点A,P,pはいずれも、平面α上で直線EVに対して同じ側にある。 +
定理（半平面の凸性）より、線分Pp上にEはない。Pは直線Ep上にあるから、Pは半直線Ep上にある。 +
--
====

このように、直線の像は投影面と平行な場合を例外として、半直線となります。その端は、投影面上にあってEV//lとなるような点です。この点は *非常に* 重要なので、「消失点」という名前を付けておきます。

[.definition]
.定義（消失点）
--
視点をEとする。
直線lが投影面と平行でないとき、投影面上の点VであってEV//lとなるようなものをlの消失点と呼ぶ。
--

絵を描いたことがある人は「消失点」を「無限に遠くにある点」等と習ったかもしれませんが、定義（消失点）にあるように、消失点はあくまでも「投影面上の点」であることに注意してください（しいて言えば直線l上の点を無限に特に動かしたときに、その *像* が漸近する点、と言えるかもしれませんが、あくまで像なので、投影面上の点です）。

ここで、消失点を求める操作のイメージを持っておきましょう。消失点の定義は、lに平行で視点を通る直線vを用意して、vと投影面の交点を消失点Vと考えても同じことです。つまり、消失点を求めたい直線lがあった時、lを平行移動、つまり向きを保ったままスライドしてEを通るところまで持ってきて、その時に投影面とどこで交わっているかを見る操作になります。

TODO: スケッチを入れる

この操作をすることで、lがもともとどこにあったかは関係なくなり、いわば直線の「方向」のみによって、消失点が決まります。定理化すると以下のようになります。

[.theorem]
.定理（消失点の一致）
--
直線lが消失点Vを持つとき、lに平行な直線mの消失点もVとなる。
--
[.proof]
.証明
--
定義（消失点）と平行の推移性から明らか。■
--

== 投影面と平行な場合

ちなみに、lが投影面と平行な場合には消失点が生まれません。その場合、なぎ払われる半平面と投影面の交差を考えると、両端のない直線になりそうです。ちゃんと書くと、以下のようになります。

[.theorem]
.定理（投影面と平行な直線の像）
--
(1) 投影面と平行な直線lの像は、lが臨界面より投影面側にある場合に存在し、Eとlで定まる平面と投影面の交線となる。 +
(2) 投影面と平行な直線lの像が存在する場合、lとlの像は平行である。
--

[.proof]
.簡易的な証明
--
(1) 平面El上の図を書けば明らか。

(2) lの像をl'とする。 +
(1)より、lとl'はともにEとlで定まる平面上にある。一方、lは投影面に平行であり、l'は投影面上にある。従って、lとl'は平行である。■
--

NOTE: lはそれ自身と平行であるという定義を採用しています。

== 消失点の求め方

直線の消失点を求める時には、原則として定義に立ち返って求めることになります。「直角を保証したい」などの特殊な場合の求め方については「n点透視図法」以降で扱おうと思うのですが、すぐにわかる例があるので紹介します。

[.theorem]
.定理（投影面に垂直な直線の消失点）
--
投影面に垂直な直線lの消失点は、視心と一致する。
--
[.proof]
.証明
--
投影面に垂直な直線lは、視軸と平行であるため、消失点と視心の定義より、消失点は視心と一致する。■
--

また、平行な線分の像が2つ以上分かっていれば、消失点の一致を逆に使って消失点を求めることもできます。

[.theorem]
.定理（直線の消失点の逆算）
--
線分AB、線分CDの像がそれぞれ線分ab,線分cdであり、AB//CDで、直線abと直線cdが点Vで交わっているとき、Vは直線ABと直線CDの消失点である。
--
[.proof]
.証明
--
AB//CDでありながらabとcdが平行でないことから、定理（投影面に平行でない直線の像）より、ABやCDは投影面と平行ではなく、したがって消失点を持つ。 +
また、AB//CDなので、定理（消失点の一致）よりABとCDの消失点は一致する。 +
線分abは直線ABの像に含まれるので、直線ABの消失点は直線abに含まれる。同様に、CDの消失点も直線cd上にある。 +
直線abと直線cdの交点はVのみなので、Vはabとcdの消失点となる。■
--

////
実際に作図するときには以下の定理の形で使うことが多いでしょう。

[.theorem]
.定理（平行な線分の延長）
--
線分AB,線分CD,線分EFが互いに平行であり、それぞれの像が線分ab,線分cd,線分efであるとき、直線ab,直線cd,直線efは平行であるか、一点で交わる。
--
[.proof]
.証明
--
線分ABの像、線分CDの像、線分EFの像はそれぞれ直線AB、直線CD、直線EFの像の部分である（∵定理（部分集合の像））。

[1] 直線ABが投影面と平行でない場合
定理（消失点の一致）より、直線AB、直線CD、直線EFは同じ消失点Vを持つ。定理（直線の投影）の(1)より、直線ab、直線cd、直線efはそれぞれ半直線VA、VC、VEとなる。定理（消失点の一致）より、Vはそれらの消失点であるから、直線ab、直線cd、直線efはすべてVを通る。■

[2] 直線ABが投影面と平行である場合
平行の推移性により直線CD,直線EFも投影面と平行である。さらに、定理（直線の投影）の(2)より、AB//ab、CD//cd、EF//efとなる。平行の推移性より直線ab,直線cd,直線efはすべて平行である。■
--
////

== 作図への応用

実はこの時点で、かなり実用的な作図をすることができます。現在投影面上で有効に使える操作は、

(1) 既知の点の像同士の間に線を引く。
(2) 既知の線の像同士の交点を得る。
(3) 消失点から既知の点まで半直線を引く。
(4) 既知の平行線の像同士の消失点を求める。
(5) 投影面に対して平行であると分かっている線に対して、それに平行な線を引く。

ぐらいでしょうか。
つまり、 *対象上で、「既知の点同士をつなぐ」「既知の線同士の交点を得る」「既知の点から既知の方向に線を伸ばす」の組み合わせで得られる図形の像は自由に作れる* ようになったわけです。

実際に図形上にない線分についても、補助線をうまく使ってこの操作の組み合わせで作図できるようなものであれば、作図することができます。

たとえば、不等辺四角形abcdが正方形ABCDの像であると仮定して、以下のものを作図していましょう。

. 2x2の4つの正方形に等分割する。
. 1辺を3分割する。
. ABに対してABCDと対称な正方形を描く（幅を倍にする）

しかし、まだ交差関係しか利用できておらず、正方形である場合しか扱えていません。それに、辺の長さを10等分するとか、辺の長さを1:√2に分割するとかいった操作がまだできません。もっと長さとか角度とかを定量的に扱いたいですよね。


////
[.theorem]
--
任意の点AとCの像がそれぞれaとcであり、投影面上の線分abと線分cdが交差しないとき、AB//CDかつABの像がabで、CDの像がcdであるような点Bと点Dが存在する。
--
[.proof]
--
abとcdが交差しないとき、AB//abとなる点Bを取ることができて、


[.theorem]
.定理
--
投影面上の任意の四角形abcdについて、abcdを像とするような平行四辺形ABCDが存在する
--
[.proof]
視点をEとする。
abcdが何組の平行な辺を持つかで分類する。
[1] 2組の平行な辺を持つ場合、abcdはすでに平行四辺形なので、ABCD=abcdとすれば定理（投影面上の点の像）より成り立つ。
[2] 1組の平行な辺を持つ場合、命名の対称性よりabとdcが平行である場合だけを考える。
直線bcとdaの交点をVとし、EVとabとともに平行で、Eを通らない平面αを一つ考える。
平面αと直線Eaの交点をA、直線Ebの交点をB、直線Ecの交点をC、直線Edの交点をDとすると、ABCDの像はそれぞれabcdである。

直線ABはα上にあってαは直線abと平行なのでab//AB、同様にdc//DC、よってAB//DC。
bcV、EbB、EcCが同一直線なので、直線BCと直線EVはともに平面Ebc上にある。直線BCはα上にあって、α//EVなので、BC//EV
同様にCD//EVなので、

EAaBbは同一平面上なので、AB//ab
AB//ab//cd
--
////


// ちなみに、面対称な図形の対応する点をそれぞれ繋ぐと、これらはすべて平行になるため、その像は平行であるか、一つの消失点で交わるかのいずれかになります。人間の顔や自動車のような複雑な形を定規で作図することはできませんが、描かれたそれらが歪んでいないかを検証したり、フリーハンドで描く時の下書きにしたりすることができます。

// まだ複雑な形状は扱っていないのでゼロから作図することはできませんが、


