---
layout: base.njk
title: 射影幾何学との接続
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]



[%collapsible]
.おまけ：射影幾何学とは
==
ここから先は、作図法や透視図法の理解には直接関係しない内容です。興味のある人だけ読んでください。

この定理を証明するのに5通りもの場合分けを使いました。これはもっと簡単に示せないのでしょうか。実は、この定理は射影幾何学の枠組みを用いると、より簡単に示すことができます。

射影幾何学は、ユークリッド幾何学の公理系から平行線公理を取り除き「どのような2直線も交わる」と主張することで始まります。平行に見える直線も、伸ばしていくといずれ交わることにするのです。そのような点を無限遠点とします。無限遠点は向きごとに決まっていて、3本の直線が互いに平行（に見える）のであれば、それは同じ無限遠点を共有することになります。

射影幾何学の例としては、半球上の幾何学があります。球面上では、大円（球の中心を通る平面と球の交線）が直線の役割を果たします。大円はかならず2点で交わります。例えば地球儀から1周する経線を二つ選ぶとかならず北極と南極の二点交わっていますね。どのような大円を選んでも、二つの交点があり、それらは地球の真裏にあります。なので、片方が北半球にあればもう片方は南半球にあります。ということは、北半球だけを観察すると、「2本の直線は必ず一点で交わる」と言えるわけです。ただし、この例では例外として、赤道上で交わる2点があります、これがちょうど無限遠点のようなものですね。

ただし、無限遠点も特殊な性質を持っているわけではなくて、ある意味で普通の「一点」と同じように扱うことができることに注意してください。先ほどの半球面上で何らかの作図をした後、それを複製して裏返して張り合わせて球体にし、今度は別の向きで切って半球にしてみます。こうすると、先ほど無限遠点だった場所が普通の点になり、普通の点が無限遠点になります。これらに性質（交わるか交わらないか、など）の差はないわけです。

ただし、射影幾何学においては順序の概念がないので、半直線が無かったり、線分の定義に癖があったりします。二点ABを選んだときに、線分ABは、直線（大円）のうちAB上ということになりますが、これは普通にABを繋ぐルートと、無限遠点を超えてぐるっと繋ぐルートの二つがあり、これらは本質的に区別できません（区別してしまうと、無限遠点が特殊な点ということになってしまって、射影幾何の面白さが損なわれてしまいます）なので、線分を定義するには「同一直線上にあるABCを、AからBを通ってCに行くルート」のように定めてあげる必要があります。同様に、無限遠点を特別扱いしたくないという理由から、半直線と言うものも存在しません。強い言えば、無限遠点を片端に持つ線分の一種になります。

射影幾何の考え方を使うと、今回の定理で重要な概念だった「互いに平行であるか、一点で交わる」という概念は、単に「一点で交わる」と言い換えることができます。そして、視点Eと点Pを繋いで像を求める時に半直線ではなく直線を使うようにする（そのようにして作られる像は、今までの像と虚像を合わせた形になります）など、理想カメラの定義からすべてを射影幾何の上でやり直し、消失点は無限遠点の像であるというようなことにすると、この定理は場合分けなく証明することができます。

ちなみに、先ほどの半球の中心に視点を置いて、北極を視心とし、投影面に像を作ると、射影幾何と投影面上の作図が接続されます。「赤道上で交わる線」は投影面上で平行線になることなどを確認してみてください。

射影幾何はユークリッド幾何を完備化したものであるとか、点と直線の双対定理が存在するとか、いろいろな面白い性質を持っていますが、ここではこれ以上は触れません。興味のある人は、以下のページなどを参照してください。
==