---
layout: base.njk
title: 円の像　その3
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]

「その2」で扱った方法で手書きで描いた楕円の形は、視心付近を描く限りでは十分高精度ですが、画角を広げていくと、3DCGで描かれたような「数学的に正しい」円の形との誤差が無視できなくなっていきます。現実のカメラにおいても、広角レンズで撮影された楕円の形は（そのレンズが歪みのない、「理想カメラ」に近いものだったとしても）後者に近いものになる場合があります。

この違いは、「その1」で提示した「近似」をはじめとするいくつかの主張が、厳密には正しくないことに起因しています。

長年「その2」の方法で絵を描いてきた人は、これを理由に、しばしば「3DCGは間違っている」や「レンズが歪んでいる」などと批判的に言うことがあります。

このページでは、「その1」で提示した「近似」をはじめとするいくつかの主張について、どこまでが正しく、どこから間違っていて、どのような反例が作れるのかを、分析していきます。これを知ることで、なぜ3DCGと手書きの絵の違いが生まれるのかを説明できるようになるでしょう。

しかし、ここで扱うような厳密な方法を手書きの絵やイラストに取り入れることはあまり現実的ではありません。大変であるだけでなく、手書きの楕円を描き慣れた人や見慣れた人から見た時に、逆に違和感の原因になることがあります。

実用的な観点からは、このページの内容はあくまで知っておく程度にとどめ、まずは「その2」で扱った考え方や方法をしっかり身に着けることをお勧めします。

なお、ここでは二次曲線について考えるため、座標幾何を利用します。


== 「円の像は楕円になる」について

始めに強い定理を示してしまいます。

[.theorem]
--
N次曲線の像はN次曲線の一部になる。
--
[.proof]
--
カメラの対称性より、視点Eを原点(0, 0, 0)、視心を(0, 0, 1)とする場合に固定する。
////
曲線がN次曲線であれば、x,y,zのN次多項式 f(x,y,z)=0 で表せる。このうち、臨界面に対して視心側の部分、つまり z > 0 の範囲のみが像を持つ。

点(x,y,z)の像は(x/z, y/z, 1)にあるから、点(x/z,y/z,1)が曲線の像になるための必要十分条件は、z>0 かつ f(x/z,y/z,1)=0 であること。

z>0であることに注意してこれを同値変形すると、z^N f(x/z, y/z, 1)=0 となる。これはx,y,zのN次多項式であるから、像はN次曲線になる。■
////
--

既に幾何的に示した事実ですが、直線は1次曲線で一次曲線は直線なので、この定理は直線の像が直線の一部になることも含意しています。

これを利用すると、円の像が二次曲線になることがすぐに分かります。

[.theorem]
--
(1) 円の像は一般に二次曲線になる。
(2) 円の全体が像を持つとき、円の像は楕円になる
(3) 円が臨界面に接しているときは、円の像は放物線になる、
(4) 円が臨界面と交差しているとき、円の像は双曲線の枝の片方となる
--
[.proof]
--
(1) 円は二次曲線なので円の像も二次曲線である。
(2) 連続写像であり、円と同相な二次曲線は楕円のみであるから、円の像は楕円になる。
TODO: 埋める
--

前回は円の全体が像を持つ場合に限って、(1)のケースだけを紹介しましたが、円の全体が像を持たないときは放物線や双曲線にもなります。これは円錐が切り方によっては楕円ではなく双曲線や放物線になることに対応しています。

日常目にする円の像は、(2)のケースが多いでしょう。例えば、正面から見たときのコインの像は円ですが、斜めから見たときのコインの像は楕円になります。双曲線になるのは、例えば大きなフラフープや円形の広場の中に立った場合など、十分に大きな円があってその中に視点が入っているような場合です。双曲線は二つの部分（枝と呼びます）に分かれていますが、片方は虚像となるため見えません。

放物線になるのは臨界面と円が接する場合です。視点が円周の付近にある時、投影面の方向を調整することで見ることができます。正確には臨界面と円との関係によるので、円がどんな大きさでも視点がどこにあっても、投影面の向きを変えることで放物線にも双曲線にもできるのですが、小さい円では画角が不足して観測できないことが多いと思います。

手元にスマホやタブレットがあれば、面白い実験ができます。（スマホのカメラは理想カメラではないですが、理想カメラに近いものと言えるでしょう）。スマホカメラにおいて臨界面はちょうどスマホの背面で近似できます。これを身近な円、例えば時計などの縁にくっつけた時、像は放物線となります。フラフープや洗面器のような大きくて中空の円があれば、その中にスマホを入れると双曲線になるはずです。


== 円の軸の像は「短軸に一致する」について

「その1」において、以下のような定理を紹介しました。これは、円の軸が視心を通る場合に限定すれば、正確な主張です。

[.theorem]
.定理（楕円の軸）
--
円Cの像が（円でない）楕円C'であるとき、Cの軸の像はC'の長軸または短軸と一致する。
--

しかし、「長軸または短軸」を「短軸」に読み替えて話を進めました。ここは数学的には全く正しい主張ではありません。厳密には、視距離をdとして、円の像が視心からd以上離れると、つまり画角が90度を超えると、成り立たなくなります。

円の像が消失線から離れるほど「正円に漸近する」、つまり短軸と長軸の比がどんどん1に近づくのみで、逆転することはないと考える人が多いのですが、実際に像を求めてみると、視心から離れたところでは逆転して奥行きのほうが長い楕円になることが分かります。「円に対して正面に近づくはずだから」と考えてしまうのかもしれませんが、かメラには球対称性がないのでそのような直感は外れています。