---
layout: base.njk
title: 線分の像
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]

== 線分の像

今回からは、特定の図形について考えていきます。とはいっても、まずは今回は最も簡単な例として、線分について考えてみます。今回はチュートリアルです。

== 直観的な予想

厳密に考える前に、結果を予想してみましょう。

図形上全体を動く点Pを取って、視点EからPに伸びる半直線EPを動かしていったときに、半直線がスイープする（なぎ払う）範囲を考えます。まずEからPにビームを打った時に、そのビームに巻き込まれるような領域をまず考えるとよいのでしたね。

線分をABとして、EからABを払うようにビームを撃つと、その通る領域は三角形EABをAB方向に無限に伸ばしたような形になりそうです（このような図形を角EABと呼びます）。

その領域を投影面で切った断面を考えると、図形の像が得られます。角EABは平面なので、投影面と交わる部分は線分になりそうです。その両端は、それぞれ半直線EAとEBに乗っています。つまり、点A,Bの像をそれぞれ点a,bとすると、線分ABの像は線分abになるのではないでしょうか。今回は簡単のため、線分EAや線分EBが投影面と交差しない場合は考えません。

== 直線上の三点の投影

ここから厳密に考えます。まず、

[.theorem]
.定理（直線上の三点の投影）
--
空間中の点A,B,Cが同一直線上にあって、それらが像a,b,cを持つとき、a,b,cは同一直線上にある。
--

[.proof]
.証明
--
視点をEとする。
平面EABを平面αとする。
仮定より、ABCが同一直線上なのでCもα上にある。
像の定義より、EAaは同一直線上なのでaもα上。
同様に、EBbは同一直線上なのでbもα上。
同様に、ECcは同一直線上なのでcもα上。
従って、abcはすべてα上。
また、αは投影面と平行ではない（∵投影面上にないEを含んでいて、投影面との共有点abcも持っている）。
abcはαと投影面の共通部分上にあるので、同一直線上にある。
--

これは透視図法において、直線や線分の像が曲がらないことを示す重要な定理です。
実在のカメラにおいては、魚眼レンズのように歪みのあるレンズの影響で直線が曲がることがあり、それを再現するような絵を描くこともありますが、透視図法に従う限り、そうはならないことが言えます。

== 線分の投影
ここから、線分の像が線分になることが示せます。

[.theorem]
.定理（線分の投影）
--
点A,Bがそれぞれ像a,bを持つとき、線分ABの像は線分abとなる。
--
[.proof]
.簡易的な証明
--
定理（図形の像の必要十分条件）を用いて示す。

線分AB上の任意の点Cについて考える。

まず、AとBがそれぞれ像を持つこと、定理（点の像の存在条件）と定理（半空間の凸性）より、Cも像を持つ。この像をcとする。
点A,B,Cは同一直線上にあるので、定理（直線上の三点の投影）より、a,b,cは同一直線上にある。
また、点Cは直線AB上でAとBの間にあるので、点Cの像cも直線ab上でaとbの間に存在すると予想できる。（ここは簡易的な説明であり、厳密な証明は後述する。）
したがって、線分ABの像は線分abとなる。
--

[.proof]
.厳密な証明
--
定理（カメラの相似変形）より、点Aが投影面上にある場合のみ示せば十分である。

この時、定理（投影面上の点の像）より、点Aと点aは同一である。また、EBbは同一直線上にあるので、EABbはすべて同一平面上である。

定理（図形の像の必要十分条件）を用いて示す。

[1] 線分AB上の任意の点Cに対して、Cの像cが線分ab上にあることを示す。

三角形ABbと直線ECについてパッシュの公理を考える。直線ECは線分ABと点Cで交わるため、直線ECは線分abまたは線分Bbと交わる。直線ECと直線Bbの交点はEただ一つであるが、定義（点の像）より、直線Bb上でEに対してBとbは同じ側にあるので、直線ECと線分Bbは交点を持たない。従って、直線ECは線分abと交わる。この交点を点cとすると、定義（点の像）より、点cは点Cの像となる。ゆえに、線分ABの像全体は線分abに含まれる。…[1]

[2] 線分ab上の任意の点cに対して、cを像とする点Cが線分AB上にあることを示す。

三角形ABbと直線Ecについてパッシュの公理を考える。直線Ecは線分abと点cで交わるため、直線Ecは線分ABまたは線分Bbと交わる。直線Ecと直線Bbの交点はEただ一つであるが、定義（点の像）より、直線Bb上でに対してBとbは同じ側にあるので、直線Ecと線分Bbは交点を持たない。従って、直線Ecは線分ABと交わる。この交点を点Cとすると、定義（点の像）より、点Cの像は点cとなる。ゆえに、線分ab全体が線分ABの像に含まれる。…[2]

[1]と[2]と定理（図形の像の必要十分条件）より、線分ABの像は線分abと一致する。■
--


== 作図への応用

この定理を使うと、例えば長方形の像が分かっているときに、その中心を作図することができます。


[.theorem]
.定理（長方形の中心の像）
--
長方形ABCDの像が四角形abcdであり、点Pが長方形ABCDの中心、つまり線分ACと線分BDの交点であるとき、点Pの像は線分acとbdの交点である。
--

[.proof]
--
点Pは線分AC上にあるため、定理（線分の投影）より、点Pの像は線分ac上にある。同様に、点Pの像は線分bd上にある。したがって、点Pの像は線分acと線分bdの交点である。
--

同様に、いくつかの点の像が分かっているとき、対象上でそれらを線分で繋ぐ操作と線分の交点を取る操作の組み合わせで得られる図形の像は、同等の手順を投影面上で行うことで得られます。これは投影面上で作図をするときに強力な道具となります。

以下、自明なことですが作図法においては重要なので、特筆しておきます。（平面上においては）2つの直線が交わるというのは珍しくないものの、3直線が一点で交わるのは得意なことです。

[.theorem]
.定理（一点で交わる3線分の像）
--
点A,B,C,D,E,Fの像がそれぞれa、b、c、d、e、fであるとする。
線分ABと線分CD、線分EFが一点で交わっているとき、それぞれの像である線分ab、線分cd、線分efも一点で交わる。
--

[.proof]
--
点Pを線分ABと線分CD、線分EFの交点とし、Pの像をpとすると、pは線分ab上、線分cd上、線分ef上に乗る。■
--
