---
layout: base.njk
title: 共点の保存
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]


== 結論

先に作図法において実用的な結論から述べます。

. 3本以上の直線や線分は、「互いに平行、または延長すると一点で交わる」と「それ以外」のどちらかに分類できる
. 空間中の3本以上の直線や線分が「互いに平行、または延長すると一点で交わる」で、1点でない像が存在する場合、これらの直線や線分の像も、必ず「互いに平行、または延長すると一点で交わる」

これは、ここまで確認した定理（一点で交わる3線分の像）や、定理（投影面と平行な直線の像）、定理（投影面と平行でない直線の像）を一般化したものです。この形で理解してしまうと簡単です。

== 共点

本題に入る前に、概念の整理をします

「3本以上の直線や線分は『互いに平行、または延長すると一点で交わる』と『それ以外』のどちらかに分類できる」ので、これに名前をつけておきましょう。

[.definition]
.定義（共点）
--
3本以上の直線や線分について、「互いに平行である、または延長すると一点で交わる」場合、これらは「共点」であると言う。
--

共点には平行のように推移性があります。当たり前ですね。以下では直線の場合だけ示していますが、線分についても成り立ちます。

[.theorem]
.定理（共点の推移性）
--
直線a,b,cと直線b,c,dが共点であるとき、直線a,b,c,dは共点である。
--
[.proof]
.証明
--
定義より、a,b,cが共点であるとき、a//b//cであるか、点Pがあってa,b,cが点Pで交わっているかのいずれかである。また、定義より、b,c,dが共点であるとき、b//c//dであるか、点Qがあってb,c,dが点Qで交わっているかのいずれかである。

(1) a//b//cであるとき、b//cであるから、bとcの交点は存在しない。したがって、b//c//dであり、平行の推移性より成り立つ。
(2) a,b,cが一点Pで交わっているとき、bとcは平行ではないから、b,c,dは一点Qで交わっている。bとcの交点が2つあることはないので、P=Qであり、a,b,c,dは一点で交わる。
--

== 証明

では本題を証明します。なお、ここでいう「延長」とは、線分や半直線についてそれが乗っている直線のことです。

[.theorem]
.定理（共点の保存）
--
空間中の3本以上の直線や半直線や線分が共点であって、線分や直線や半直線の像を持つ場合、これらの像は共点である。
--
[.proof]
--
線分が含まれる場合も定理（部分の像）より、その延長について成り立っていれば容易に示せる。3本の場合について示せば、4本以上の場合は定理（共点の推移律）から容易に示せる。したがって、3本の直線の場合のみ示せばよい。

l,m,nを、共点である3本の直線とし、l,m,nの像をそれぞれl',m',n'とする。

l'はlとEで定まる平面と投影面の交線上にあるから、l'の延長はその交線自体である。m'、n'についても同様である。

l,m,nが共点である場合、l,m,nは「互いに平行である、または延長すると一点で交わる」のどちらかであるから、場合分けして示す。

(1)l,m,nが互いに平行な場合、Eを通りl,m,nと平行な直線vを考える。lとEで定まる平面、mとEで定まる平面、nとEで定まる平面はすべて直線vを含む。
(1-1) vが投影面と平行でないとき、投影面とvの交点をVとすると、l',m',n'の延長はVで交わる。
(1-2) vが投影面と平行なとき、vとl'は同一平面上にありながら交点を持たないので、v//l'である。平行の推移律から、l',m',n'も互いに平行になる

(2)l,m,nが一点Pで交わるとき、直線EPを考える。lとEで定まる平面、mとEで定まる平面、nとEで定まる平面はすべて直線EPを含む。
(2-1)直線EPが投影面と平行でないとき、直線EPと投影面の交点をpとすると、l',m',n'の延長ははすべてpで交わる。
(2-2)直線EPが投影面と平行なとき、EPとl'は同一平面上にありながら交点を持たないので、EP//l'である。m'、n'についても同様である。平行の推移律から、l',m',n'はすべて平行になる。
--

{% sketch "sketches/concurrent" %}

== 具体例

(1-1)は定理（消失点の一致）に相当する場合です。この点Vはl,m,nの共通の消失点となります。平行な線が消失点に向かうことはよく知られていますね。(1-2)は定理（投影面と平行な直線の像）に相当する場合で、これも特に注意は必要ないでしょう。

(2-1)はPが臨界面より前側にある場合には、pがPの像となり、直線l,m,nの像の上はpが来るので、簡単です。しかし、*Pが臨界面より後ろ側にある場合* には、Pは像を持たないため、*pはPの像ではなく* 、しかも半直線としてのl'はpを通りません、*にもかかわらず*、l'を延長すればpで交わります。これについては、次のページで補足します。

(2-2)はPが臨界面上にある場合です。この場合は特殊で、*もともと交わっていた直線の像が平行になります*。これも少々びっくりする例かもしれません。 

どのようなときにそうなるか、具体例を考えてみてください

NOTE: ちなみに、次元を落とす変換なので逆は言えません。像が一点で交わっているからと言って、対象上でも一点で交わっているとは限りません。たまたま重なっているだけの場合があるからです。


