---
layout: base.njk
title: 平面の像
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]

== 平面の像

線分、直線の像を考えたので、今回は無限に広がる平面の像を考えます。

直観的に予想してみましょう。視点を通らない無限に広い平面があったとき、平面全体を「なぎ払う」ようなビームを考えると、空間の半分が巻き込まれそうです。そのビームが届くか届かないかの境界は、その平面を視点を通るところまでスライドしてきたときの平面になりそうです。

無限に広がる平面についても、直線における消失点に対応する「消失線」というのを定義できそうです。

[.definition]
.定義（消失線）
--
投影面と平行でない平面αについて、視点Eを通りα//α'なる平面α’を一意に取ることができる。このα'と投影面が交差する線をαの「消失線」と呼ぶ。
--

[.theorem]
.定理（平面の像）
--
(1) 視点を通らず、投影面と平行でない平面αの像は、投影面上でαの消失線を端とする半平面になる。
(2) 視点を通り、投影面と平行でない平面αの像は、αの消失線となる
(3) 投影面と平行な平面αの像は、αが臨界面より投影面側にある時にのみ存在し、投影面全体となる。
--
[.proof]
.証明
--
TODO: 埋める
--

[.theorem]
.定理（消失線の一致）
--
投影面と平行でない平面α1と、α1と平行なα2があるとき、それらの消失線は一致する。
--
[.proof]
--
定義（消失線）と平行の推移性より明らか。
--

== 投影面に対して平行な平面

[.theorem]
.定理（投影面に平行な平面上の図形）
--
投影面に平行な平面上の図形の像は、元の像と相似になる。

特に、投影面に平行な直線上の比は保存する。
--
[.proof]
.簡易的な証明
--
--





== 消失点と消失線

平面上の線、あるいは平面と平行な線の消失点を考えると、消失線との間に一定の関係があります。

[.theorem]
.定理（消失線と消失点）
--
(1) αと平行な任意の直線が消失点を持つならば、消失点はαの消失線上にある。
(2) αと平行な任意の直線が消失点を持たないならば、その像はαの消失線と平行。
--
[.proof]
.証明
--
視点をEとする。
αと平行で投影面と平行でない任意の直線をlとし、lの消失点をV、αの消失線をhとする。
Eとhで定まる平面をα'とすると、定義（消失線）よりα'はαと平行。
定義（消失点）より直線EVはlと平行。
EVとα'はともにαに平行でともにEを含むので、EVはα'上にある。
EVと投影面が交わるとき、その交点は投影面とα'の共有線上にあるから、h上にある ...■(1)
EVと投影面が交わらないとき、h//EV//lよりh//lで、定理（投影面に平行な直線の像）よりhはlの像と平行。...■(2)
--

消失線との交点を求めることで、

== 重力を導入（地平線）

ここまで扱ってきた数学的な三次元空間には上下の概念がありませんでしたが、有名な定理を示すために一時的に重力の概念を導入します。これでもなお *カメラには回転対称性がある* つまり図形的性質に関しては、地面に成り立つ性質は一般の平面についても成立することを忘れないようにしてください。

[.definition]
.定義（地面、水平、鉛直、地平線、高さ）
--
重力に対して垂直な平面を「地面」と呼ぶ。
地面に対して平行であることを、水平という。
地面に対して垂直であることを、鉛直という。
地面の消失線を地平線と呼ぶ。
地面から重力と反対方向に測った距離を「高さ」と呼ぶ。
--
NOTE: 垂直と鉛直は異なる概念です。

現実で「地面」と呼ぶ時には、土地の起伏があったり地球の丸みがあったりしますが、ここで「地面」と呼んでいるのは無限に広がる平面であり、そういったものは無視していることに注意してください。
別に平面地球論者でなくても、地球の丸みが問題にならないスケールで考えれば現実世界からそこまでひどく乖離するものではありません。そして、地面を平面と定めたことで、地平線が定義できました。
また、「高さ」もここで定義しています。これは地面から鉛直に測った標高のようなものです。地面より「下」にある場合には符号をマイナスにすることにしましょう。

このように定義することで、広く知られた以下の二つの主張が示せます。実用上は、投影面から長方形領域を切り出す際、多くの場合、地平線に対して傾かないように取ることが多いです。

[.theorem]
.定理（水平な線の消失点）
--
水平な直線の消失点は地平線上に来る。
--
[.proof]
--
定理（消失線と消失点）から明らか。■
--

[.theorem]
.定理（アイレベル）
--
視点と同じ高さにある点の像は、地平線と重なる。
--
[.proof]
--
視点と同じ高さの点Pはすべて、地平線に平行な平面α上にある。
平面αは視点を通るので、定理（平面の像）より、点Pの像はすべて地平線上に来る。■
--