---
layout: base.njk
title: 円の像　その1
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]

== 円について考える、その前に
今回からは、円と回転体の描き方について考えます。円とその周辺に関してはたくさんの誤解が起きやすいので、「その1」～「その3」の3ページに分割します。

「その1」では簡易的に像の性質を明らかにするための「近似」の導入、「その2」では「近似」に基づいた実用的な作図法、「その3」で厳密な証明などの補足、という三部構成にします。絵を描きたい人はその1とその2を読めば十分実用的な知識が手に入り、数学的主張のみに興味がある人はその1とその3を読めば満足できるという計画です。もちろん、全部読むことで深い理解を得ることもできます。

== 円と回転体
まず、定義から確認しましょう。

[.definition]
.定義（円）
--
平面πとπ上の点P、長さrがあったとき、平面π上で点Pから長さrの距離にある点の集合を円と呼ぶ
またこのとき、Pを円の中心、rを円の半径、Pを通りπに垂直な直線を円の軸と呼ぶ。
--

円の軸というのは数学ではあまり使わない言葉ですが、ここでは、円の像を考えるときに便利な概念なので定義しておきます。円は回転体の一種です。

[.definition]
.定義（回転体）
--
直線を軸として、その軸に対して回転対称な図形を回転体と呼ぶ。
--

NOTE: 本テキストで単に回転対称といった時には、任意の角度で回転させても重なることを指します。つまり、2回対称や3回対称ではなく、無限回対称のことを指します。

円だけでなく、円柱や円錐（直円錐）も回転体の一種です。現実への応用では、皿、瓶、ワイングラスなどの複雑な形も、ディティールを除けば回転体と考えることができます。取っ手のついたマグカップは回転体ではありませんが、取っ手を除いた部分だけで言えば回転体とみることができます。円を描く必要があるのは、ほとんどが回転体を描く場合です。

[.theorem]
.定理(回転体の像)
--
回転体の軸の像が視心を通るとき、像はその軸の像に対して線対称である。
--
[.proof]
--
回転体の軸をl、lの像をl'とする。
Eとlで定まる平面をαとすると、l'はα上にある
視心がl'上にあるため、視軸はα上にある。したがってαは投影面に垂直。
投影面と回転体はαに対して面対称なので、対称性により回転体の像はl'に対して線対称である。■
--

証明を読むとわかるとおり、これは回転体の軸が視心を通っている場合の対称性を利用した主張です。つまり、軸の像が視心を通っていないときには対称性は崩れ、この定理は成り立たなくなります。

しかし、それでは不便なので、「回転体の軸の像が *十分に視心付近を通る* 場合は、回転体の像はその軸の像に対して線対称であると *近似できる*」と考えます。さらに極端に、以下のように言ってしまいましょう。

[.assumption]
.近似
--
回転体の像は *常に* その軸の像に対して線対称であると扱ってよい。
--

これは、厳密には数学的には間違った主張で、これに基づいて厳密な作図をしようと思うと矛盾が簡単に作れてしまいます。が、絵を描くうえでは、ほとんどの場合、投影面の視心付近を描くので、実用上大きな問題は起きません。なので、多くの人、というかほぼ全員がこの主張を信じています。

円の像はどのように考えられるでしょうか。卵型やまんじゅう型になってもおかしくないように思えますが、そうはなりません。


== 円の像は楕円である

[.theorem]
.定理（円の像）
--
円の全体が像を持つとき、円の像は楕円になる。
--

NOTE: ここで言う楕円には円である場合も含まれていることに注意して下さい。あまり数学的な言葉づかいではないですが、通常の円が楕円でないことを強調するために「正円」と呼ぶこともあります。

楕円というのは以下のような図形です。単に「いびつに歪んだ円」という意味ではありません。短軸に対してだけでなく、長軸に対しても対称であることに気を付けてください。

TODO: 楕円の図を入れる

もし「円を斜めから見たら潰れるのだから楕円になるのは当然だ」と思った人がいたら、ちょっと待ってください。そんなに簡単な話ではありません。（まだ扱っていませんが）平行投影であれば単に図形を引き延ばしたり潰したりしていると考えることができるので当たり前かもしれませんが、今考えているのは透視図法です。透視図法において、平行線が平行にならず、正方形の像が不等辺四角形になることを考えると、これは極めて非自明な主張です。左右はともかく、前後（奥行き）方向についても対称な形になるのは、実に不思議なことです。

にもかかわらず、 この主張は *数学的に正確に成り立ちます* 。厳密な証明は後回しにして、ここでは直感的な理解を紹介します。

定義に基づくと、視点Eから円周上の各点Pに向かって半直線EPを伸ばしていき、投影面と交わる点が円の像です。これは見方を変えると、視点を頂点とする円錐を平面で切った断面を求めていると考えることができます。

NOTE: ある平面図形を底面とし、平面上にない頂点について、頂点から平面図形のばす線分または半直線を集めた図形を錐体と呼びます。円錐とは底面が円の錐体です。

そして、 *円錐を斜めの平面で切ると、楕円が得られる* ことがよく知られています。つまり円錐の細い方か太い方か関わらず、対称な形になるのです。これは、透視図法における円の像がまんじゅう型や卵型にならず楕円になることと似た非直感的な事実なので、これを理解できれば円の像が正確に楕円になることを理解したと言えそうです。この問題についての幾何的な証明については以下の動画が詳しいです。

https://www.youtube.com/watch?v=f12lJrFnVjs

しかし注意深く見ると、この動画で扱われている幾何的な証明は、円の軸上に円錐の頂点が存在する「直円錐」の場合に限定されることに気付くと思います。今回必要なのは、頂点の位置がどこにあっても円の像が楕円になることなので、より対称性が低い問題になっていることに気を付けてください（頂点が軸上にある直円錐は回転体ですが、頂点が軸上にない円錐は回転体ではありません）。このギャップを埋めるような厳密な証明については、後のページで補足します。

TODO: 図を入れる

「近似」から、次の主張が示せます。数学的な正しさを求める場合は、軸の像が視心を通る場合、という条件を付けて理解してください。

[.theorem]
.定理（楕円の軸）
--
円Cの像が（円でない）楕円C'であるとき、Cの軸の像はC'の長軸または短軸と一致する。
--
[.proof]
--
円Cの軸をl、lの像をl'とする。
C'は円ではない楕円なので対称軸は長軸と短軸の2つしかない。
一方で、*「近似」* より、C'はl'に対して線対称である。
したがって、l'はC'の長軸か短軸のどちらかと一致する。■
--

NOTE: 似た言葉ですが、円の軸は円が存在する平面に対して垂直な直線であるのに対し、楕円の長軸や短軸は楕円が存在する平面上にある直線で、まったく違うものを指しています。

ここで示されるのは、長軸または短軸のどちらかに一致する、ことのみが言われていますが、aまあ *実用的には* 短軸と一致すると考えてよいです。従って、「その2」では、円の軸の像＝短軸で、それに直交する軸を長軸として、話を進めます。厳密な観点からの補足は「その3」に回します。

== 円の中心の像は、楕円の中心と一致しない。

円の像が意外にも前後に対称な楕円になることはすでに述べたとおりですが、中心について考える場合はその限りではありません。

円周だけを見ると奇跡的に一致するというだけで、変形自体は当然非対称に行われています。

円に外接する正方形とその像を考え、正方形の中心を作図するとわかります。円の輪郭だけを書けば良い場合には意識する必要はありませんが、中心に点を描かなければいけない場合には必要です。
また、同心円の像を描かなければいけない場面でも、これを意識する必要があります。
