---
layout: base.njk
title: 共線の保存
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]

== 共線の保存

3つ（以上）の点が同一直線にあることを「共線である」と言います。透視図法の前後で、共線の関係が保たれます。

[.theorem]
.定理（共線の保存）
--
点A,B,Cが像a,b,cを持つとき、A,B,Cが共線であれば、a,b,cは共線である。
--

[.proof]
.証明
--
視点をEとする。

点E,A,Bから定まる平面をαとする。 +
仮定より、ABCが同一直線上なのでCはα上にある。 +
像の定義より、EAaは同一直線上なのでaもα上にある。同様に、b,cもα上にある。 +
また、αは投影面と平行ではない（∵投影面上にないEを含んでいて、投影面との共有点abcも持っている）。
abcはαと投影面の共通部分上にあるので、同一直線上にある。 +
--

これを利用すると、以下の定理が自明に分かります。

[.theorem]
.定理（直線上の図形の像）
--
図形Sが直線の一部（線分、半直線など）であるとき、Sの像も直線の一部である。
--
[.proof]
.証明
--
Sのうち像を持つ点が1点、2点以下であるときは自明なので、Sが3点以上を含むときに示す。 +
S上の2点をA,Bとし、それらの像をa,bとする。 +
S上の任意の点Cについて、A,B,Cは同一直線上にあるので、Cが像を持てば、定理（共線の保存）より、a,b,cも同一直線上にある。 +
従って、Sの像はa,bを含む直線の一部である。 +
--

これは透視図法において、直線や線分などの像が決して曲がらないことを示します。実在のカメラにおいては、魚眼レンズのように歪みのあるレンズの影響で直線が曲がることがあり、それを再現するような絵を描くこともありますが、透視図法に従う限り、そうはならないことが言えます。

== 共線の保存の逆

投影は次元を落とす変換なので、共線の保存の逆は成り立ちません。点A,B,Cが同一直線上になくても、点A,B,Cを含む平面が直線に縮退する場合には、像a,b,cが一直線上にあるからです。つまり、像が同一直線上にあっても、元の点が同一直線上にあるとは限りません。

しかし、*縮退が起きない場合に限って言えば*、逆が成り立ちます。

[.theorem]
.定理（共線の保存の逆）
--
視点Eを含まない平面αと、α上の任意の3点A,B,Cについて、点A,B,Cが像a,b,cを持ち、a,b,cが共線であれば、A,B,Cは共線である。
--

[.proof]
.証明
--
視点をEとする。

点E,a,bから定まる平面をβとする。 +
仮定より、a,b,cが同一直線上なのでcはβ上にある。 +
像の定義より、EAaは同一直線上なので、Aもβ上にある。同様に、B,Cもβ上にある。 +
また、βはαと平行ではない（∵αとβは共有点ABCを持っているが、βはα上にないEを含んでいる）。
abcはαとβの共通部分上にあるので、同一直線上にある。 +
--
