---
layout: base.njk
title: 線分の像
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]

今回からは、特定の図形について考えていきます。とはいっても、まずは今回は最も簡単な例として、線分について考えてみす。今回はチュートリアルです。

== 共線の保存

まず練習として、以下の定理を示しておきましょう。

[.theorem]
.定理（共線の保存）
--
空間中の点A,B,Cが同一直線上にあって、それらが像a,b,cを持つとき、a,b,cは同一直線上にある。
--

[.proof]
.証明
--
視点をEとする。

点E,A,Bから定まる平面をαとする。 +
仮定より、ABCが同一直線上なのでCはα上にある。 +
像の定義より、EAaは同一直線上なのでaもα上にある。同様に、b,cもα上にある。 +
また、αは投影面と平行ではない（∵投影面上にないEを含んでいて、投影面との共有点abcも持っている）。
abcはαと投影面の共通部分上にあるので、同一直線上にある。 +
--

== 線分の像

つぎは線分の像について考えます。今回は簡単のため、線分EAや線分EBが投影面と交差しない場合は考えません。

厳密に考える前に、結果を予想してみましょう。

図形上全体を動く点Pを取って、視点EからPに伸びる半直線EPを動かしていったときに、半直線がスイープする（なぎ払う）範囲、つまりEからPにビームを打った時に、そのビームに巻き込まれるような領域をまず考えるとよいのでしたね。線分をABとして、EからABをなぎ払うようにビームを撃つと、その通る領域は三角形EABをAB方向に無限に伸ばしたような形になりそうです（このような図形を角AEBと呼びます）。

その領域を投影面で切った断面を考えると、図形の像が得られます。角AEBは平面上の図形なので、投影面と交わる部分は線分になりそうです。その両端は、それぞれ半直線EAとEBに乗っています。つまり、点A,Bの像をそれぞれ点a,bとすると、線分ABの像は線分abになりそうです。

{% sketch "sketches/image-of-segment" %}

定理（図形の像の必要十分条件）を使って丁寧に示してみましょう。まず、以下の定理を使います。これは図を描くと当然のことを言っています。

[.theorem]
.定理（角の大小関係）
--
同一平面上の7つの点O,A,B,C,P,Qについて、半直線OA上にPがあり、半直線OB上にQがあり、線分AB上にCがあるとき、半直線OCは線分PQと交わる。
--

TODO: 図を描く

[%collapsible]
.厳密な証明
====
図を見れば当然であることも、数学的には公理から証明する必要があります。現代的なヒルベルト幾何学は十分な表現力を持っているので、当たり前のことはちゃんと示すことができます。

しかし、このような当たり前の主張ほど、ちゃんと証明するのは難しいことが多いです。

定理（角の大小関係）は順序の公理から厳密に示すことができます。以下の証明は、図を書いたらそうなるという「観察」を一切伴わず、すべて公理から言葉の上で示せていることを確認してみてください。

[.proof]
.厳密な証明
--
以下、パッシュの公理を、三角形XYZと直線lについて、XYZの各辺のうちちょうど0個か2個がlと交わるという形で利用する。 +
また、XYZが同一直線上にあるとき、半直線XY上にZがあるということ線分YZ上にXがないことは定義より同値である。

[1] 直線OCと線分PQが交わることを示す。 +
三角形ABPと直線OCについて、パッシュの公理を考える。 +
直線OCと直線ABの交点は点Cであり、A,C,Bはこの順にあるから、直線OCは線分ABと交わる。 +
直線OCと直線APの交点は点Oであり、A,O,Pはこの順にないから、直線OCは線分APと交わらない。 +
したがって、直線OCは線分BPと交わる。...(1)

次に、三角形BPQと直線OCについて、パッシュの公理を考える。 +
(1)より、直線OCと線分BPは交わる。 +
直線OCと直線BQの交点は点Oであり、B,O,Qはこの順にないから、直線OCは線分BQと交わらない。 +
したがって、直線OCは線分PQと交わる。...(2)

[2] (2)の交点をRとして、Rが半直線OC上にあることを示す。 +
三角形APRと直線OBについて、パッシュの公理を考える。 +
直線OBと直線APの交点は点Oであり、A,O,Pはこの順にないから、直線OBは線分APと交わらない。 +
直線OBと直線PRの交点は点Qであり、P,R,Qはこの順にあるから、直線OBは線分PRと交わらない。 +
したがって、直線OBと線分ARは交わらない。...(3)

三角形ACRと直線OBについて、パッシュの公理を考える。 +
(3)より、直線OBと線分ARは交わらない。 +
直線OBと直線ACの交点は点Bであり、A,C,Bはこの順にあるから、直線OBは線分ACと交わらない。 +
したがって、直線OBは線分CRと交わらない。したがって、交点Rは半直線OC上にある。...(4)

(2)と(4)より、半直線OCと線分PQは交わる。■
--
====

この定理を使って丁寧に示してみましょう。

[.theorem]
.定理（線分の投影）
--
点A,Bがそれぞれ像a,bを持つとき、線分ABの像は線分abとなる。
--
[.proof]
.証明
--
以下視点をEとする。定理（図形の像の必要十分条件）を用いて示す。

[1] 線分AB上の任意の点Cに対して、Cの像cが線分ab上にあることを示す。 +
線分AB上の任意の点Cについて考える。 +
EABで定まる平面をαとすると、E,A,B,C,a,bはすべてα上にある。 +
定理（角の大小関係）より、半直線ECは線分abと交わる。この交点をcとする。 +
cは投影面上にあるから、cはCの像である。

[2] 線分ab上の任意の点cに対して、cを像とする点Cが線分AB上にあることを示す。 +
線分ab上の任意の点cについて考える。 +
Eabで定まる平面をαとすると、E,A,B,a,b,cはすべてα上にある。 +
定理（角の大小関係）より、半直線Ecは線分abと交わる。この交点をCとする。 +
cは投影面上にあるから、cはCの像である。

[1]と[2]と定理（図形の像の必要十分条件）より、線分ABの像は線分abと一致する。■
--

これは透視図法において、線分の像が曲がらないことを示します。実在のカメラにおいては、魚眼レンズのように歪みのあるレンズの影響で直線が曲がることがあり、それを再現するような絵を描くこともありますが、透視図法に従う限り、そうはならないことが言えます。

== 作図への応用

以下、自明なことかもしれませんが、作図法においては重要なので、特筆しておきます。

[.theorem]
.定理（線分の交点の像）
--
線分ABと線分CDが点Pで交わっていて、点A,B,C,Dそれぞれが像a,b,c,dを持つとき、Pの像はabとcdの交点になる
--

[.proof]
.証明
--
点Pは線分AB上にあるため、定理（部分の像）より、Pの像はABの像の上にある。CDについても同様。

定理（線分の投影）より、線分ABの像は線分ab、線分CDの像は線分cdであるから、Pの像pはabとcdの交点になる。
--

[.theorem]
.定理（一点で交わる3線分の像）
--
点A,B,C,D,E,Fの像がそれぞれa、b、c、d、e、fであるとする。
線分ABと線分CD、線分EFが一点で交わっているとき、それぞれの像である線分ab、線分cd、線分efも一点で交わる。
--

[.proof]
.証明
--
点Pを線分AB、線分CD、線分EFの交点とし、Pの像をpとする。pは線分ab上、線分cd上、線分ef上に乗る。■
--


これらの定理を使うと、例えば四角形abcdが長方形ABCDの像であると分かっているときに、長方形のの中心の像を作図することができますね。長方形の中心は対角線ACとBDの交点なので、acとbdの交点が中心の像となります。

同様に、いくつかの点とその像が分かっているとき、対象上でそれらを線分で繋ぐ操作と交点を取る操作の組み合わせで得られる図形の像は、同等の手順を投影面上で行うことで得られます。これは投影面上で作図をするときに強力な道具となります。

ただし、まだ線分を延長するような操作については示していないことに注意してください。