---
layout: base.njk
title: 点の像
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]

== 点の像

点の像の定義を再確認します。
[.definition]
.定義 （点の像）
--
空間中の点Xに対して、視点から点X方向へ延びる半直線が投影面と交わる点があれば、それを「Xの像」と呼ぶ。
--



== 像の定義域

交わる点が *あれば* という留保がついています。実際、どのような時に点の像が存在するのでしょうか。

以下、視点から投影面方向を「前」、その反対方向を「後ろ」と呼ぶことにします。

まず、点が投影面より前にある場合、これは視点と点の間に投影面があるので、半直線は必ず投影面と交わり、点の像が存在します。

点が投影面より後ろある場合は、注意が必要です。視点から点に向かって伸ばした半直線が、投影面に近づいていくのか、平行なのか、遠ざかっていくのかで区別する必要があります。投影面に近づいていく場合は、半直線を伸ばしていけばいずれ投影面と交わるので、点の像が存在します。平行な場合と遠ざかっていく場合は、いくら半直線を伸ばしても投影面と交わらないので、点の像は存在しません。

まとめると、「投影面に平行で視点を通る平面」が像が存在するか否かの境界になっていることが分かります。この面上より前側に点があれば点の像が存在し、この面上やこの面より後ろ側に点があれば、点の像は存在しない、ということになります。この「点の像が存在する範囲」を、投影の「定義域」と言います。

この「投影面に平行で、視点を通る平面」は、定義域とそうでない領域の境界になる需要な概念なので、本テキストでは「臨界面」と呼ぶことにします。

[.definition]
.定義 （臨界面）
--
理想カメラにおいて、投影面に平行で視点を通る平面を「臨界面」と呼ぶ。
--

[.theorem]
.定理（点の像の存在条件）
--
臨界面に対して、視心と点Pが同じ側にあれば、またその時に限り、点Pの像が存在する。
--

[.proof]
.厳密な証明
--


--

[.theorem]
.定理（点の像の一意性）
--
点Pの像が存在するとき、その像は一意である。
--

[.proof]
.証明
--
定義（点の像）より、点Pの像は、視点から点P方向へ延びる半直線と投影面との交点である。半直線と平面が交わる点は高々一つしかないので、点Pの像は一意である。
--


== 自明な例：投影面上の点の像

一般的に、点の像を求めるためには視点から点に伸びる半直線を考え、それと投影面の交点を求める必要があります。これは結構大変で、それを簡単にするための様々な定理と作図法をこれから学んでいきます。

しかし、点が投影面上にある場合は、非常に話が簡単です。なぜなら、視点から投影面上の点に伸びる半直線と投影面との交点は、その点自身になるからです。つまり、点の像はその点自身になります。

[.theorem]
.定理（投影面上の点の像）
--
点Pが投影面上にある場合、その点の像P'はP自身である。
--

図形の像についても定義を確認します
[.definition]
.定義（図形の像）
--
空間中の図形Sに対して、S上にあって像が存在するすべての点の像を集めた投影面上の図形を「Sの像」と呼ぶ。
--

これはガラス板上でペン先を動かす例に対応しているのでしたね。しかし、「すべての点」というのが厄介です。無数の点がある図形に対して、この方法をいちいち適用していくことはできません。

実際に図形の像を求めるためには、その像に含まれる必要十分条件を示すことで、像を特定することができます。

空間中の図形Sと、投影面上の図形S'について、以下の二つをともに満たす時、S'はSの像となります。
. S上の任意の点Pについて、その像pが存在するならば、それはS'上にある。
. S'上の任意の点pについて、その点を像とする点PがS上に存在する。

[.proof]
.厳密な証明
--
定義に従った、Sの像をS''とする。つまり、S''は「S上にあって像が存在するすべての点の像を集めた図形」である。
S上の任意の点Pについて、その像pが存在するならば、S'上にあるならば、S''⊆S'である。
S'上の任意の点pについて、その点を像とする点PがS上に存在するならば、S'⊆S''である。
S''⊆S'かつS'⊆S''より、S''=S'である。■
--

ここに点の像の定義を代入して書き下すと、以下の定理を得ます。

[.theorem]
.定理（図形の像の必要十分条件）
--
視点をEとする。空間中の図形Sと、投影面上の図形S'について、以下の二つをともに満たす時、S'はSの像となる。
. S上の任意の点Pについて、半直線EPと投影面との交点が存在するとき、それはS'上にある。
. S'上の任意の点pについて、半直線EpとSとの交点が存在する。
--

[.theorem]
.定理（部分集合の像）
--
S₁とS₂を空間中の図形とする。S₁がS₂の部分集合であるとき、S₁の像はS₂の像の部分集合である。
--

[.proof]
.証明
--
S₁の像をS₁'、S₂の像をS₂'とする。S₁がS₂の部分集合であるとき、S₁上の任意の点Pについて、PはS₂上の点でもある。定義（図形の像）より、Pの像pはS₁'上にあると同時にS₂'上にもある。したがって、S₁'はS₂'の部分集合である。■
--