---
layout: base.njk
title: 平面の像
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]

本来連続性を扱うには微分幾何学の概念が必要になるのですが、やや厳密性を落として初等幾何の範囲で説明を完結させます。

== 曲線

直感的には、曲線は「繋がった線」のことです。この定義に従うと、円や直線、線分はすべて曲線です。「曲」という字が入りますが、直線や線分、折れ線などを除外するわけではないことに注意してください。
曲線であるということを指して「*位置連続*」ということもあります。グラフの連続性みたいなものですね。

初等幾何の範囲内でできるだけ厳密に定義しようと思うと、以下のようになると思います。

[.definition]
.定義（曲線）
--
図形上に点Pを取って、点Pを中心とする球面を考える。ある長さrがあって、rより半径が小さいどんな球面についても、球面と図形の交点が常に2つであれば、その図形は点Pの近傍で曲線である。
--

まどろっこしい定義をしていますね。どういうことが考えてみましょう。
ぐにゃぐにゃ曲がった複雑な曲線上に点Pを取って、Pを中心とする球を適当に考えると、交点はたくさんある場合もあります。しかし、球を小さくしていくと、交点はあるときからちょうど2つになり、それ以上どんなに小さくしても2つのままです。

{% sketch "sketches/definition-of-curve" %}

一方、例えば平面に対して同様のことを考えると、どんなに小さな球を考えても、交点は常に無数に（つまり球を切る円周上に）存在します。つまり、平面は曲線ではありません。

また、端のある場合にはどうでしょうか。例えば線分ABについて、AやBを中心とする球を考えると、球を小さくしていったときに交点は1つになるので、、点AやBの *「近傍」では* 曲線ではないです。しかし、線分全体が曲線ではないというわけではなくて、線分AB上に（途中に）中心を取ると、交点は2つになるので、線分は（の内点近傍で）曲線です。どんなに端に近くても、端そのものでなければ、その端までの距離をrとするとrより小さな球体はすべて2個の交点を持つことに注意してください。

[.definition]
.定義（接線）
--
曲線C上の点Pに対して、点QをC上で動かしてPに限りなく近づけていったとき、Qをどちらから近づけても同じ直線lに限りなく近づくとき、lを「曲線Cの点Pにおける接線」と呼ぶ。
--

線の端や曲線が折れ曲がっているような場所では接線が定義できない。

[.definition]
.定義（接線連続）
--
曲線上のある区間において、区間中のすべての点において接線が定義できることを接線連続と呼ぶ。
--

直感的には、曲線に角がなく、滑らかであることを表す概念です。接線連続な曲線は折れ線などを除外するため、一般語の曲線に近づいたかもしれません。しかし、なお直線などは除外されていないことに気をつけてください。これはグラフで言う「微分可能」のようなものだと思うと理解しやすいです。

[.definition]
.定義（接する）
--
点Pにおいて曲線CとDが同じ接線を持つとき、曲線CとDは点Pにおいて「接する」と呼ぶ。
--


== 曲面

曲線と同様に、曲面も定義しておきましょう。

[.definition]
.定義（面）
--
十分に狭い範囲を見て平面と重なる同相になる図形を「面」と呼ぶ。
--

[.definition]
.定義（接面、接線）
--

--

== 連続性の保存

さて、ここまで定義した曲線や曲面の像について、うれしい性質があります。

[.theorem]
.定理（位置連続性の保存）
--
定義域内において、曲線の像は曲線になる。
--

直感的に言えば、定義域から出ない限り、つながっていた線がちぎれることはないという主張です。

[.theorem]
.定理（接線の保存）
--
視点Eを通らない直線lが曲線Cに点Pで接しているとき、直線lの像は曲線Cの像に点Pの像で接する。
--

[.theorem]
.定理（接線連続の保存）
--
接線連続な曲線Cについて、Cのすべての接線が視点を通らないとき、Cの像も接線連続となる。
--
[.proof]
--
定理（接線の保存）より、曲線Cの各点における接線の像は曲線Cの像の接線となる。したがって、接線連続性が保たれる。
--

直感的には、滑らかな曲線は滑らかな像を与えるという主張です。

ただし、定理（位置連続の保存）と異なり、接線が視点を通る場合を除外していることに注意してください。そのような点においては、像に尖った角が生まれる場合があります。

== 一般の曲面に関する定理

さらに、曲面について考えると、応用範囲が広がります。滑らかな曲面は球や円柱だけでなく、例えば、コップの表面や人間の肌などいたるところで見ることができます。これらの曲面に対して、以下のような定理が成り立ちます。

[.definition]
.定義（曲面）
--
--

[.definition]
.定義（接面）
--
--

[.definition]
.定義（回り込み）
--
視点をEとする。
曲面S上の点Pに対して、直線EPがSの接線となるとき、「（Eから見て）曲面Sは点Pにおいて回り込む」と呼ぶ。
曲面SがEから見て点Pにおいて回り込むような点Pの集合を「（Eから見て）曲面Sが回り込む輪郭」と呼ぶ。
--

物体の輪郭には回り込む輪郭と回り込まない輪郭があります。回り込まない輪郭は曲面が接面連続でない、つまり面が折れて辺が生じている場所にできます。
例えば、球の輪郭はすべて回り込む輪郭になりますが、円柱は側面部分のみが回り込む輪郭で、断面部分に生じる輪郭は回り込まない輪郭です。

[.theorem]
.定理（回り込む輪郭の滑らかさ）
--
曲面Sが滑らかな時、Sが回り込む輪郭は、いくつかの滑らかな曲線となる
--



[.theorem]
.定理
--
ガウス曲率が0の滑らかな曲面の回り込む輪郭は直線となる。
TODO: 特定の例外を除く。
--
[.proof]
--

--
円柱面や、円錐面、折れていない紙面などの回り込む輪郭は、必ず直線であると言えます。

[.theorem]
.定理（曲面上の曲線と輪郭が接する）
--
滑らかな曲面S上に滑らかな曲線Cがあり、曲線C上に点Pがある。
点Pにおける曲線Cの接線が視点を通らず、曲面Sが点Pにおいて回り込むとき、曲線Cの像は点Pの像において曲面Sが回り込む輪郭の像と接する。
--
[.proof]
--
点Pにおける曲線Cの接線をlとする。lは点Pにおける曲面Sの接線のひとつである。仮定よりlは視点Eを通らない。
曲面Sは点Pにおいて回り込むので、直線EPは点Pにおける曲面Sの接線のひとつである。したがって、lとEPから点PにおけるSの接面αが一意に定まる。

一方、Pは滑らかな輪郭上の点である。定理（回り込む輪郭の滑らかさ）より、Pにおける回り込む輪郭の接線mが一意に定まる。
回り込む輪郭はS上の滑らかな曲線なので、接線mは接面α上にある。

接面αはEを通る平面なので、定理（平面の像）より、αの像はαと投影面の交線であり、lの像、mの像もその交線上にある。■
--

この定理から、例えば、「回転体の断面の像は回転体の輪郭に接する」「円柱の輪郭は（回り込まない輪郭もふくめて）接線連続である」などの主張が導けます。


