---
layout: base.njk
title: 射影幾何学
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]


== 本当に無限遠点は対称なのか

無限遠点は通常の点と同じように線を引いたり点を取ったりできる、と言いましたが、いまいちしっくりこない人が多いと思います。今回はその補足です。

== 無限遠点と無限遠直線

[.definition]
.定義（無限遠点）
--
直線lに対して、以下の性質を見たすような「lの無限遠点P」と呼べる点が存在する。

(1) 別の直線mがl//mであれば、mもPを通る。 +
(2) 任意の点QとPを結ぶことができて、直線PQはlに平行である。
--

前回は言及しませんでしたが、無限遠点同士を結んだ場合は無限遠直線というのが生まれます。

[.definition]
.定義（無限遠直線）
--
αが平面の向きに対応する無限遠直線と呼べる直線が存在する。ある直線lがα上にあるか、αと平行なとき、αとlは交点を持つ。
--

lの無限遠点Pとmの無限遠点Qを結ぶ無限遠直線PQは、lとm両方に平行な平面の「向き」に相当します。平面幾何であれば無限遠直線は一つだけで、空間図形を考えると無数にあります。

*消失線は無限遠直線の像と考えることができ* て、定理（消失線上の消失点）は直線と無限遠直線の交点の像を得る操作に一致します。同一平面上の直線の消失点が消失線上に並ぶのは共線の保存と同じことを言っています。これも便利な概念ですね。

無限遠点を導入し、平行線は共通の「方向」を表す無限遠点で交わることにしたことで、「同一平面上であれば、かならず2つの直線は1つの交点を持つ」ようになりました。また、無限遠点を入れても、「どのような2つの点も1つの直線だけで結べる」というルールは通常通り保たれます。

まとめると、

- PとQが通常の点であれば、通常通り直線PQがある
- Pが通常の点でQが無限遠点であれば、Pを通りQが表す「方向」の直線がある
- PとQが無限遠点同士であれば、PとQの「方向」が両方乗った平面の無限遠直線になる

- lとmが通常の直線で、平行でない場合は、どちらも通常の交点を通る
- lとmが通常の直線で、平行である場合は、共通の無限遠点を通る
- lが通常の直線でmが無限遠直線である場合、どちらもlのの無限遠点

確かに「同一平面上であれば、かならず2つの直線は1つの交点を持つ」が成り立っていますね。*無限遠とか平行とかに関わらず成り立つタイプの命題であれば* 無限遠点も通常の点も同列に扱うことができます。これまで示してきた中で、共線や共点に関しては平行だとか無限遠だとかの性質を使わずに示すことができるので、いずれかが無限遠点や無限遠直線でも問題なく成り立ちます。

このようなルールが成り立つ幾何学のことを「*射影幾何学*」と呼びます

これは、幾何学の命題は定義や公理から導かれるので、定義の上では同じように扱うことができていれば、それを組み合わせた性質も同じになる、という論理です。

しかし、そうはいっても幾何学は図を描いて理解したいですよね。無限遠点についても通常の点と同じ性質が言えることは、どうやったら直観的に理解できるでしょうか。

== 球面上での幾何学

ところで、球面上の幾何を考えます。

まず、球面においては大円のことを「直線」と呼びます。大円というのはそこで球を切ったときにちょうど半分に割れるような円で、地球で例えるなら赤道や経線のようなものです。どう見ても円に見えますが、これを「直線」と *呼ぶことにします*。

これは大円に沿って移動する経路が最短であることを考えると受け入れやすいでしょう。東京からニューヨークに飛行機で移動するときに太平洋を渡るのではなくアラスカ経由になるというあれです。

以下の図において、赤い線と緑の線は「直線」ですが、青い線は大円ではないので直線ではありません

TODO: スケッチを入れる。

NOTE: このような最短経路を与える線を測地線と呼び、曲面上で直線に相当するものが欲しいときに考えることが多いです。

二つの「直線(大円)」は必ず、球面上にある2点、それも球に対して互いに真裏にある2点で交わっています。地球で例えるなら2つの経線は北極と南極で交わりますね。このようなペアを「1点」と *呼ぶことにします*。これもどう見ても2つあるように見えますが、言葉の上での約束です。

すると、「どのような2本の「直線」も、1つの「点」だけで交わる」と言えますね。

そして、「どのような2つの「点」も、1つの「直線」だけで結べる」と言えますね。北極と南極のような2点では結ぶ「直線」は無数にあるように思えるかもしれませんますが、これは1ペアなので反例になっていません。2つの点というのは2ペアということです。

このように定義すると、前回無限遠点を追加したことで得られた「どのような2本の「直線」も、1つの「点」で交わる」「どのような2つの「点」も、1つの「直線」で結べる」というルールを、無限遠点というな特殊な例を使わずに作り出すことができました。球面は対称性が高いので、どの点も同じ性質を持っていて、特別な性質を持つ点はないはずです。

== 半球と平面の対応

次に気になるのは、球面上で作った「射影幾何」が、どのように無限遠点や無限遠直線のある「射影幾何」と対応しているかです。

先ほど定義した「1点」は球の真反対にあるので、地球で例えるなら片方が北半球にあればもう片方は南半球にあります。ということは、片方の半球だけを観察すると、普通に1ペアのうち片方だけを見ることができます。ただし、切った断面（赤道）についてはまだペアが残っています。

この半球上で起きている出来事を、球の中心に視点を置いて、断面に平行な平面の上にに向かって「投影」してみます。

すると、それぞれの「直線(大円)」は平面上の直線に投影されます。半球上に交点を持つ2本の直線は普通に交点を持つ直線に投影されますが、赤道上で交わっている直線は平行線になります。ということは、赤道上の点が無限遠点、赤道が無限遠直線に対応しそうです。

そして、同じ出来事を球面上で回転させることで（あるいは断面と投影面を変えることで）無限遠点が通常の点になったり通常の点が無限遠点になったりします。これをもって無限遠点と通常の点は性質に対称性があるという証拠になりそうです。

ただし、今考えたのは平面上の射影幾何と球面の対応です。空間の射影幾何については4次元中にある球を考えないといけないので、直観的にイメージするのは厳しいです。