---
layout: base.njk
title: 射影幾何学との接続
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]

== 射影幾何学までの道のり

ここまで、作図法や透視図法の理解に必要な定理を確認してきました。実は、ここまで示してきた透視図法の性質は射影幾何学の言葉を使うと非常にすっきりと、簡潔に書くことができます。

ただし、一般に知られている射影幾何学と透視図法はわずかに違うので、微妙な修正が必要です。このページはそのギャップ埋めのためのものです。

先に明かしてしまうと、このページでは透視図法の作図に使える新しい事実は一つも登場しません。これまで登場した定理、特に「共点の保存」を射影幾何の言葉で書き直し、より簡潔に理解しようというものです。つまり、悪い言い方をすると言葉遊び的な側面が強いものです。数学的な興味の対象として読んでください。

== 場合分けを無くしたい！

前回の「共点の保存」の証明は、線同士が平行である場合とそうでない場合、投影面と平行である場合とそうでない場合、の組み合わせで4パターンの場合分けがありましたね。さらに、交点がある場合に、その交点が臨界面より後ろにある場合には、交点の像がないのに延長すると交わるという不思議な性質がありました。これらのことを、もっとすっきりと説明できないでしょうか。

== 「臨界面より前なら……」を無くしたい！

点Pの像は、視点をEとすると半直線EPと投影面の交点でした。なので、点の像は臨界面より前にある場合のみ定義できるのでしたね。しかし、これが原因で場合分けが厄介になっている場面がたくさんあります。そこで、便宜上、以下の概念を定義しておきます。

[.definition]
.定義（虚像）
--
視点をEとする。
点Pに対して、Pの像が存在しないとき、直線EPと投影面の交点があれば、それを虚像と呼ぶ。
図形Sに対して、S上の点の虚像をすべて集めた図形をSの虚像と呼ぶ。
--

これは要するに、視点Eから点Pと正反対方向に半直線を伸ばしたときに、投影面と交わったところを「虚像」と呼ぼう、と言っています。点Pの虚像をpとすると、Pとpは視点Eを挟んでちょうど180度反対の方向にあります。そのような虚像は点Pが臨界面より後ろにあるときに存在します。

虚像は「ガラス板になぞる方法」で言えば見えるわけがありません。人間は前しか見えないし、もし（複眼とかで）後ろが見えたとしても、真反対方向にあるものを「重なっている」といって投影面になぞるのは無理があります。しかし、幾何学的には、半直線より直線のほうが圧倒的に扱いやすいので、こういうものを考えます。

なぜこんなものを定義したかと言えば、臨界面より前にあるか後ろにあるかで場合分けしたくないからです。なので、 *このページに限っては* 断りなく「像」と言ったら基本的に虚像も含むと考えてください。

この条件下で、直線の像を考えてみましょう。アニメーションで見てみると以下のようになります。青く表示されるのが虚像です。

TODO: スケッチを入れる

L上で点Pを動かすと、Pが臨界面に近づいたときにPの像ははるか遠方に行きます。そして、Pが臨界面より後ろに行くと、代わりに消失点の反対方向からPの虚像が表れて、直線のほぼ全体を塗りつぶします。

しかし、あくまでも「ほぼ全体」です。定理（図形の像の必要十分条件）の[2]で確認してみると、消失点Vに対して、EVとlが平行となって交点を持たないので、Vはlの像には含まれないことが分かります。つまり、消失点を除く必要があるのです。……この場合分けもなくしたいですね。

== 「平行でないとき…」をなくしたい！

次に、「平行なら…」「交点を持つなら…」というような場合分けもなくしたいですね。これは、無限遠点というものを導入することで解決できます。

[.definition]
.定義（無限遠点）
--
直線lに対して、以下の性質を見たすような「lの無限遠点P」と呼べる点が存在する。

(1) 別の直線mがl//mであれば、mもPを通る。 +
(2) 任意の点QとPを結ぶことができて、直線PQはlに平行である。
--

無限遠点というのは特定の点ではなく無数にあり、いわゆる直線の「方向」と対応します。同じ「方向」の直線は同じ無限遠点を通り、異なる「方向」の直線は通りません。別に平行線がどこかでぐにゃりと曲がって交差するようなイメージを持つ必要はありません。「無限遠点を通る」という言葉が出てきたときには、「ああこれは要するに平行のことを言っているんだな」と読み替えてくれれば問題ありません。言葉遊びのようなものだと思ってください。

例えば、直線lが無限遠点Pを通っているとします。別の直線mがlと同じ「方向」であれば（今までの言い方で言えばlとmが平行であれば）、mは同じ無限遠点Pを通ります。このときlもmもPを通っているので、Pで交わっていると考えることができます。別の「方向」であれば、別の無限遠点Qを通るので、交わりません。

(2)は無限遠点に対して直線を引く操作を定めています。l上にない点Qがあったとして、「QとPを直線で結ぶ」といったら、（従来の言葉で言うと）Qを通りlに平行な線を引く操作に相当します。そうして得た直線をmとすると、mとlは平行なので、確かにmはPを通っています。

こうすると、「平行になるように線を引く」という特殊な操作を、あたかも「点と点を繋ぐ」と同じことをしているかのように考えることができます。

ちなみに、平面αと直線lが平行なとき、lの「方向」を表す無限遠点Pは「α上にある」ということができます。なぜなら、平面α上にl//mとなる直線mを取ることができて、無限遠点Pはm上にあり、mはα上にあるからです。この無限遠点Pは平面αと直線lの両方が通っているので、αとlの交点ということができます。

== 無限遠点の像

さて、透視図法に話を戻します。

直線lの消失点を求める操作を思い出してみましょう。「視点Eを通りlに平行な直線vを引いて、直線vと投影面の交点Vをもとめると、Vが消失点となる」のでしたね。これを今覚えた「無限遠点」の言葉を使って言い換えてみましょう。「Eを通りlに平行な直線vを引く」という操作は、lの「方向」に相当する無限遠点をPとすると、「EとPを直線で結ぶ」ことに相当します。そして、EPと投影面の交点が消失点Vになりますね。

次に、点の像の求め方を思い出してみます、点Pの像は（虚像を含めると）、EとPを直線で結んで、EPと投影面との交点を求めるのでしたね。

あれ、ずいぶんと似ていますね。

この点Pが無限遠点である場合の像についても、通常の点と同じように、像を定義してみましょう。無限遠点Pはある「方向」を示しているので、EとPを直線で結ぶことは、Eから見てその「方向」に向かう線を引くことに相当します。すると、その線と投影面の交点がPの像になります。

これはまさしく、Pが示している「方向」の消失点そのものですね。つまり、「無限遠点の像は消失点になる」と言えそうです。（ただし、無限遠点は向きを持たないので、投影面より前にあるか後ろにあるかが定義できません。なので、これは像とも虚像とも区別がつかないことになります）

Pが表す方向が投影面と平行である場合も考えておきましょう。このとき、EPは投影面と平行になってしまいますが。その場合Pが投影面との交点ということになるのでしたね。これは定理（投影面上の点の像）の拡張で、P自身がPの像と言えそうです。

== 直線の像

もう一度直線lの像を考えてみましょう。像と虚像を合わせたことで、直線の像は「ほとんど」直線になりましたが、まら消失点をとり除く必要がありました。これが無限遠点を入れたことでどうなったでしょうか。

直線lが無限遠点Pを通るとき、lの消失点VはPの像になっていました。ということは、消失点Vもlの像に含んでよいことになりますね！　これで、文字通り一点の曇りもなく「直線の像は消失点を通る直線である」と言えるようになりました！

== 逆に、平行線の消失点

無限遠点を考える目的は、「平行な場合」の場合分けを無くすことでした。もう一つ、ぜひなくしたい場合分けがありますよね。定理（投影面に平行な直線）では、投影面に平行な直線は消失点を持たないことになっていたので、これが面倒な場合分けになっていました。これについても考えてみましょう。

lが投影面と平行なときについても、普通の直線と同じように消失点を求めてみます。まず、lに平行で視点Eを通る直線vを考えてと、vと投影面の交点を求めるのでしたね。vと投影面は平行なので、交点はvの無限遠点Vです。v//lなので、これは同時に、lの無限遠点でもあります。これが「消失点」と呼べそうです。

そして、lの像l'はl//l'を満たすのでした。つまり、l'は消失点を通る直線です。これはさっきの投影面と平行でない直線の像と全く同じ性質です。見事、投影面に平行な場合も、全く同じ言葉で説明できるようになりました。

== 共点の保存

さて、前回の「共点の保存」について考えてみます。

まず、共点というのは「3本以上の直線が互いに平行である、または一点で交わる」という概念でしたが、「3本の線が平行である」というのは「同じ無限遠点で交わっている」ということなので、これらはどちらも「3本の直線が一点（ただし無限遠点の場合あり）で交わる」といって差し支えないです。

で、定理（共点の保存）の主張は、「3本以上の直線が共点である場合、その像も共点である」でしたね。これは今からするともう当たり前です。三本の直線が1点Pで交わっている場合、Pを通る直線の像はPの像pを通る直線になるので、三本の直線が1点Pで交わっている場合、当然その像も一点で交わります。

前回の(1-1)～(2-2)の4つの場合分けは、いまや、交点が普通の点か、臨界面上にあるのか、投影面と平行な無限遠点なのか、そうでない無限遠点なのか、の違いで *しかない* ことがわかります。

念のため、無限遠点を知らなかった頃の言葉に翻訳しておきます。

. Pを通る直線の像はPの像pを通ります。これが普遍原則です。
. Pが普通の点であるとき、臨界面より前にあればpは目に見える像、臨海面より後ろにあればpは虚像になりますが、いずれにせよです。
. Pが投影面と平行でない無限遠点であれば、pは消失点になるので、Pを通る直線の像は消失点を通る直線になります。
. 点Pが臨界面上にある普通の点であれば、pは投影面上のEPの無限遠点になるので、どの像も平行になります。
. 交点Pが投影面と平行な無限遠点であれば、pは投影面上の無限遠点P自身になるので、どの像も平行になります。

ね、簡単でしょう？

== 射影幾何学は曲面上？

射影幾何学の例としては、半球上の幾何学があります。球面上では、大円（球の中心を通る平面と球の交線）が直線の役割を果たします。大円はかならず2点で交わります。例えば地球儀から1周する経線を二つ選ぶとかならず北極と南極の二点交わっていますね。どのような大円を選んでも、二つの交点があり、それらは地球の真裏にあります。なので、片方が北半球にあればもう片方は南半球にあります。ということは、北半球だけを観察すると、「2本の直線は必ず一点で交わる」と言えるわけです。ただし、この例では例外として、赤道上で交わる2点があります、これがちょうど無限遠点のようなものですね。

ただし、無限遠点も特殊な性質を持っているわけではなくて、ある意味で普通の「一点」と同じように扱うことができることに注意してください。先ほどの半球面上で何らかの作図をした後、それを複製して裏返して張り合わせて球体にし、今度は別の向きで切って半球にしてみます。こうすると、先ほど無限遠点だった場所が普通の点になり、普通の点が無限遠点になります。これらに性質（交わるか交わらないか、など）の差はないわけです。

ただし、射影幾何学においては順序の概念がないので、半直線が無かったり、線分の定義に癖があったりします。二点ABを選んだときに、線分ABは、直線（大円）のうちAB上ということになりますが、これは普通にABを繋ぐルートと、無限遠点を超えてぐるっと繋ぐルートの二つがあり、これらは本質的に区別できません（区別してしまうと、無限遠点が特殊な点ということになってしまって、射影幾何の面白さが損なわれてしまいます）なので、線分を定義するには「同一直線上にあるABCを、AからBを通ってCに行くルート」のように定めてあげる必要があります。同様に、無限遠点を特別扱いしたくないという理由から、半直線と言うものも存在しません。強い言えば、無限遠点を片端に持つ線分の一種になります。

射影幾何の考え方を使うと、今回の定理で重要な概念だった「互いに平行であるか、一点で交わる」という概念は、単に「一点で交わる」と言い換えることができます。そして、視点Eと点Pを繋いで像を求める時に半直線ではなく直線を使うようにする（そのようにして作られる像は、今までの像と虚像を合わせた形になります）など、理想カメラの定義からすべてを射影幾何の上でやり直し、消失点は無限遠点の像であるというようなことにすると、この定理は場合分けなく証明することができます。

ちなみに、先ほどの半球の中心に視点を置いて、北極を視心とし、投影面に像を作ると、射影幾何と投影面上の作図が接続されます。「赤道上で交わる線」は投影面上で平行線になることなどを確認してみてください。

射影幾何はユークリッド幾何を完備化したものであるとか、点と直線の双対定理が存在するとか、いろいろな面白い性質を持っていますが、ここではこれ以上は触れません。興味のある人は、以下のページなどを参照してください。