---
layout: base.njk
title: 共点の保存
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]


投影面に平行でない直線の像は、その全体が像を持つわけではなく、臨界面より前の部分のみが像を持つのでした。では、臨界面より後ろの部分はどうなっているのでしょうか。ここは「ガラス板になぞる方法」で言えば実際には見えない部分ですが、これについて考えると少し幾何学的な性質が見えてきます。そしてその幾何学的な性質は、上手く扱うと作図法に応用できます。


== 結論

先に作図法において実用的な結論から述べます。

. 3本以上の直線や線分は、「互いに平行、または延長すると一点で交わる」と「それ以外」のどちらかに分類できる
. 空間中の3本以上の直線や線分が「互いに平行、または延長すると一点で交わる」で、1点でない像が存在する場合、これらの直線や線分の像も、必ず「互いに平行、または延長すると一点で交わる」

これは、ここまで確認した定理（一点で交わる3線分の像）や、定理（投影面と平行な直線の像）、定理（投影面と平行でない直線の像）を一般化したものです。これはとても強力で、便利な主張ですが、にわかには信じがたいかもしれません。なので、これから順を追って説明していきます。

== 既知の場合

まず、ここまでに述べた定理の中で、関連するものを思い出します。一部の場合に関しては、この主張はすでに確認済みです。

線分が一点で交わる場合については、*その交点が像を持つのであれば*、定理（一点で交わる3線分の像）で確認したように像も一点で交わりますね。直線に延長した場合も、交点が像を持つのであれば同様に示せます。そもそも延長した場合にどのようになるかについて考えているので、線分か直線かは本質的な違いを生みません。

直線が投影面に対して平行でない場合には、定理（投影面と平行でない直線の像）と定理（消失点の一致）を組み合わせると、それらの像の延長は消失点で交わることが確認できます。

直線が投影面に対して平行な場合には、定理（投影面と平行な直線の像）で確認したようにそれぞれもとの直線と平行になるので、平行の推移律から像も平行になります。

互いに平行な線分の像については、直線について既に示せているので線分は部分集合の像で簡単に示せます。

「1点でない像が存在する場合」、というのは、線分が像を持たない場合や、直線や線分の延長が視点を通る場合を除外しています。

結局、確認できていないのは、交点がある場合で、その交点が像を持たない場合ですね。その場合にも、「平行または一点で交わる」ことを示せば、結論が示されたことになります。

== 虚像
便宜上以下の概念を定義しておきます。

[.definition]
.定義（延長）
--
線分や半直線が乗っている直線のことをその「延長」と呼ぶ。直線の延長はその直線自身とする。
--

[.definition]
.定義（虚像）
--
視点をEとする。
点Pに対して、Pの像が存在しないとき、直線EPと投影面の交点があれば、それを虚像と呼ぶ。
図形Sに対して、S上の点のうち像が存在しない点の虚像をすべて集めた図形をSの虚像と呼ぶ。
--

NOTE: 臨界面上にある点については、像も虚像も存在しないことに注意してください。

すると、以下のような定理が成り立ちます。

[.theorem]
.直線、半直線、線分の像の延長と虚像の延長の一致
--
任意の直線または半直線または線分について、その像の延長と虚像の延長は一致する。
--
[.proof]
.証明
--
直線、半直線、線分の延長をlとすると、像や虚像はlの像や虚像の部分集合になる。
視点をEとすると、lの像と虚像はともにEとlで定まる平面と投影面との交線上にあるから、像の延長と虚像の延長はいずれもこの交線となる。
--

[.theorem]
.定理（共点の保存）
--
. 3本以上の直線や線分は、「互いに平行、または延長すると一点で交わる」と「それ以外」のどちらかに分類できる
. 空間中の3本以上の直線や線分が「互いに平行、または延長すると一点で交わる」場合、これらの直線や線分の像も、必ず「互いに平行、または延長すると一点で交わる」
--

[.proof]
.証明
--
線分や半直線について、それが乗っているただ一つの直線のことを「延長」と呼ぶ。

線分の像の延長は直線の像の延長と一致するため、直線について示せば十分である。

5つの場合に分けて示す

[1] 空間中の直線が互いに平行で、それらが投影面に平行な場合。
  定理（投影面と平行な直線の像）と平行の推移律から、像はすべて平行になる。
[2] 空間中の直線が互いに平行で、それらが投影面に平行でない場合。
  定理（投影面と平行でない直線の像）と定理（消失点の一致）から、像の延長は共通の消失点で交わる。
[3] 空間中の直線が臨界面より前の一点で交わる場合。
  交点をPとすると、Pは像を持つのでその像をpとすると、pはともに直線の像の上に乗るから、像の延長は一点pで交わる。
[4] 空間中の直線が臨界面より後ろの一点で交わる場合。
  交点をPとすると、Pは虚像を持つのでその虚像をpとすると、pはともに直線の虚像の上に乗る。直線の像の延長と虚像の延長は一致するから、像の延長は一点pで交わる。
[5] 空間中の直線が臨界面上の一点で交わる場合。
  交点をPとし、pを通る任意の直線をlとする。視点Eとlから定まる平面をαとする。
  l上の任意の点の像はαと投影面の交線上にあるため、lの像の延長はαと投影面の交線となる。これをmとする。
  EPとmはともにα上にあり、直線EPは臨界面上の直線であり、mは投影面上の直線であり、臨界面と投影面は平行であるから、EPとmは平行である。
  Pを通る他の直線l'を考えても、同様にEPと平行になるから、平行の推移律より、lとl'は互いに平行。よって、像はすべて平行になる。
よって示された。■
--

NOTE: 次元を落とす変換なので逆は言えません。像が一点で交わっているからと言って、対象上でも一点で交わっているとは限りません。たまたま重なっているだけの場合があるからです。

