---
layout: base.njk
title: 図形の像
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]


== 図形の像

図形の像についても定義を確認します。

[.definition]
.定義（図形の像）
--
空間中の図形Sに対して、S上にあって像が存在するすべての点の像を集めた投影面上の図形を「Sの像」と呼ぶ。
--

これはガラス板上でペン先を動かす例に対応しているのでしたね。しかし、「すべての点」というのが厄介です。無数の点がある図形に対して、この方法をいちいち適用していくことはできません。

直感的には、図形上全体を動く点Pを取って、視点EからPに伸びる半直線EPを動かしていったときに、半直線がスイープする範囲を考えると分かりやすいと思います。もっとラフに言うと、EからP全体をなぎ払うようにビームを打った時に、そのビームに巻き込まれるような領域をまず考えます。その領域を投影面で切った断面を考えると、図形の像が得られます。

TODO: 図を入れる

== 厳密な証明

厳密に図形の像を求めるためには、その像に含まれる必要十分条件を示すことで、像を特定することができます。

[.theorem]
.定理（図形の像の必要十分条件）
--
視点をEとする。図形Sと、投影面上の図形S'について、以下の二つをともに満たす時、S'はSの像となる。

(1) S上の任意の点Pについて、半直線EPと投影面との交点が存在するとき、それはS'上にある。 +
(2) S'上の任意の点pについて、半直線EpとSとの交点が存在する。
--
[.proof]
.厳密な証明
--
結論から同値変形して示す。

Sの像がS'である。 +
⇔ 任意の点Pとpについて、PがS上にあって、pがPの像であるとき、またその時に限り、点pがS'上にある。

順と逆をそれぞれ同値変形する

任意の点Pとpについて、PがS上にあって、pがPの像であるとき、点pがS'上にある。 +
⇔ S上の任意の点Pについて、ある点pがPの像であるとき、点pはS'上にある。 +
⇔ S上の任意の点Pについて、その像pが存在するならば、点pはS'上にある。 +
⇔ S上の任意の点Pについて、半直線EPと投影面との交点が存在するとき、それはS'上にある。...(1)

任意の点Pとpについて、点pがS'上にあるとき、PがS上にあって、pがPの像である。 +
⇔ S'上の任意の点pについて、ある点PがS上にあって、pがPの像である。 +
⇔ S'上の任意の点pについて、pを像とする点PがS上に存在する。 +
⇔ S'上の任意の点pについて、半直線EpとSとの交点が存在する。...(2)

したがって、(1)かつ(2)とSの像がS'であることは同値である。■
--

(1)はともかく、(2)は直感的な像の取り方と逆向きになっていることに気を付けてください。(1)はS'がSの像全体を覆えていることを、(2)はS'がSの像からはみ出していないことを確認していて、両方を確認することではじめて一致したと言えます。

たとえば以下の例では、図形Sの像はS'ではありません。点AはS上の点であり、半直線EAが投影面との交点aを持つにもかかわらず、そのaがS'上にないので、(1)を満たしていません。また、点bはS'上の点ですが、半直線EbとSとの交点が存在しないので、(2)も満たしていません。したがって、S'はSの像ではありません。逆に、S'がSぴったりSの像であることを確認するには、このような点がどちらもないことを確認すればいいのです。

{% sketch "sketches/image-of-shape" %}

それと、以下の定理を示しておきます。

[.theorem]
.定理（部分の像）
--
SとTを空間中の図形とする。SがTの部分であるとき、Sの像はTの像の部分である。
--

[.proof]
.証明
--
Sの像をS'、Tの像をT'とする。SがTの部分であるとき、S上の任意の点Pについて、PはT上の点でもある。定義（図形の像）より、Pの像pはS'上にあると同時にT'上にもある。したがって、S'はT'の部分である。■
--