---
layout: base.njk
title: 直線の像
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]


== 直線の像

前回は線分の像を考えましたが、今回は直線の像を考えます。

点Aと点Bの像がそれぞれaとbであったときに線分ABの像が線分abでしたが、、直線ABの像も直線abとなるでしょうか。直線は無限に長いのでイメージするのが難しいですね。
結論から言うと、残念ながらそのようにはなりません。以下のようになります。

[.theorem]
.定理（投影面と平行でない直線の像）
--
視点をEとする。投影面と平行でない直線lの像は、Vを投影面上にあってEV//lとなるような点とすると。
(1) lがEを通らないとき、lと投影面との交点をAとすると、半直線VAとなる。
(2) lがEを通るとき、V一点となる。
--

NOTE: ここでは端点を含まない形での半直線の定義を採用していることに注意してください。つまり、V自身はlの像には含まれません。

TODO: スケッチを入れる

[.proof]
.簡易的な証明
--
(1) 定理（図形の像の必要十分条件）を用いて示すが、平面EVA上の図を書けば明らか。■
(2) 
Eを通りlに平行な直線はlのみであるため、Vはl上にある。
l上でEに対してV側にある点Pについて、半直線EPと半直線EVは一致するため、半直線EPと投影面の交点はVになる。■
--

[.proof]
.厳密な証明
--
(1)
定理（図形の像の必要十分条件）を用いて示す。

[1]まず、直線l上の任意の点Pについて、半直線EPと投影面との交点pが存在するとき、pは半直線VA上にあることを示す。

AP//EVなので、Pは平面EVA上にあり、さらに線分APは直線EVと交わらないので、平面EVA上で直線EVに対してAとPは同じ側にある。
pは半直線EP上にあるので、pも平面EVA上にあり、さらに平面EVA上で直線EVに対してPとpは同じ側にある。
従って、定理（同じ側の推移性）より、平面EVA上で直線EVに対してAとpは同じ側にある。
すると、pは直線AV上にあって、線分Ap上にVはない。
よって、pは直線VA上のうちVに対してAと同じ側、つまり半直線VA上にある。...[1]

////
平面EVA上で直線EVに対してAと同じ側にある半平面をHとする。
PA//EVなので、Pは平面EVA上にあり、さらに（線分PAは直線EVと交わらないので定理（半平面の凸性）より）PはH上にある。
pは直線EP上にあるので、pも平面EVA上にある。さらに、pは半直線EP上にあるので、定理（半直線から半平面への拡大）より、pはH上にある。
Hと投影面の共通部分は半直線VAであるため、pは半直線VA上にある。
////

[2] 次に、半直線VA上の任意の点pについて、半直線Epと直線lの交点が存在することを示す。

pは半直線VA上にあるので、pは平面EVA上にあり、さらに、pは平面EVA上で直線EVに対してAと同じ側にある。（∵線分pA上にVがないから）

l//EVより、lも平面EVA上にある。直線Epと直線lは同一平面上である。
Epとlは平行ではない（pが半直線VA上にあるのでp≠V）ので、直線Epと直線lの交点がただ一つ存在する。これを点Pとする。

AP//EVより、Pは平面EVA上でEVに対してAと同じ側にある。
pとA、PとAが平面EVA上で直線EVに対して同じ側にあるので、定理（同じ側の推移性）より、pとPも平面EVA上で直線EVに対して同じ側にある。

線分Pp上にEはないので、Pは半直線Ep上にある。...[2]

[1]と[2]と定理（図形の像の必要十分条件）より、直線lの像は半直線VAと一致する。■
--

このように、直線の像は投影面と平行な場合を例外として、半直線となります。その端は、投影面上にあってEV//lとなるような点です。この点は *非常に* 重要なので、「消失点」という名前を付けておきます。

[.definition]
.定義（消失点）
--
視点をEとする。
直線lが投影面と平行でないとき、投影面上の点VであってEV//lとなるようなものをlの消失点と呼ぶ。
--

NOTE: lに平行で視点を通る直線l'を用意して、l'と投影面の交点を消失点Vとしても同じことです。

絵を描いたことがある人は「消失点」を「無限に遠くにある点」等と習ったかもしれませんが、定義（消失点）にあるように、消失点はあくまでも「投影面上の点」であることに注意してください（しいて言えば直線l上の点を無限に特に動かしたときに、その像が漸近する点、と言えるかもしれませんが、実際に消失点自体が無限に遠くにあるわけではありません）。

ここで、消失点を求める操作のイメージを持っておきましょう。
消失点を求めたい直線lがあった時、lを平行移動、つまり向きを保ったままずらしてEを通るところまで持ってきて、その時に投影面とどこで交わっているかを見る操作になりますね。

TODO: スケッチを入れる

このとき、もともと直線がどこにあったかに関係なく、いわば直線の「方向」のみによって消失点は決まります。定理化すると以下のようになります。

[.theorem]
.定理（消失点の一致）
--
直線lが消失点Vを持つとき、lに平行な直線mの消失点もVとなる。
--
[.proof]
.証明
--
定義（消失点）と平行の推移性から明らか。■
--


なお、lが投影面に対して平行な場合は、以下のようになります。

[.theorem]
.定理（投影面と平行な直線の像）
--
(1) 投影面と平行な直線lの像は、lが臨界面より投影面側にある場合に存在し、Eとlで定まる平面と投影面の交線となる。
(2) 投影面と平行な直線lの像が存在する場合、lとlの像は平行である。
--
[.proof]
--
.簡易的な証明
--
(1) 
定理（図形の像の必要十分条件）を用いて示す。平面El上の図を書けば明らか。

(2) 
lの像をl'とする。
(1)より、lとl'はともにEとlで定まる平面上にある。一方、lは投影面に平行であり、l'は投影面上にある。従って、lとl'は平行である。■
--

NOTE: lはそれ自身と平行であるという定義を採用しています。

実際に作図するときには以下の定理の形で使うことが多いでしょう。

[.theorem]
.定理（平行な線分の延長）
--
線分AB,線分CD,線分EFが互いに平行であり、それぞれの像が線分ab,線分cd,線分efであるとき、直線ab,直線cd,直線efは平行であるか、一点で交わる。
--
[.proof]
.証明
--
線分ABの像、線分CDの像、線分EFの像はそれぞれ直線AB、直線CD、直線EFの像の部分である（∵定理（部分集合の像））。

[1] 直線ABが投影面と平行でない場合
定理（消失点の一致）より、直線AB、直線CD、直線EFは同じ消失点Vを持つ。定理（直線の投影）の(1)より、直線ab、直線cd、直線efはそれぞれ半直線VA、VC、VEとなる。定理（消失点の一致）より、Vはそれらの消失点であるから、直線ab、直線cd、直線efはすべてVを通る。■

[2] 直線ABが投影面と平行である場合
平行の推移性により直線CD,直線EFも投影面と平行である。さらに、定理（直線の投影）の(2)より、AB//ab、CD//cd、EF//efとなる。平行の推移性より直線ab,直線cd,直線efはすべて平行である。■
--

具体的な消失点の位置の求め方については次回以降で考えていこうと思うのですが、一つだけ、とても簡単にわかる例があるので紹介します。

[.theorem]
.定理（投影面に垂直な直線の消失点）
--
投影面に垂直な直線lの消失点は、視心と一致する。
--
[.proof]
.証明
--
定義（消失点）から、直線lの消失点をVとすると、EV//lとなる。投影面に垂直な直線lは、歯軸と平行であるため、その消失点は視心と一致する。■
--


== 作図への応用

実はこの時点で、かなり実用的な作図をすることができます。現在投影面上で使える操作は、

(1) 既知の点の像同士の間に線分を引いて、線分の像を得る。
(2) 既知の線の像同士の交点を取って、交点の像を得る。
(3) 既知の方向の直線の線の像を得るために、既知の消失点から既知の点の像まで半直線を引く。
(4) 平行であることがわかっている2つの線について、それらの像同士を延長し、消失点を求める。

ぐらいでしょうか。

つまり、 *対象上で、「既知の点同士をつなぐ」「既知の線同士の交点を得る」「既知の点から既知の方向に線を伸ばす」の組み合わせで得られる図形の像は自由に作れる* ようになったわけです。

例えば、直方体には3組の平行な線分があるので、*それらの消失点の位置さえわかれば*、それぞれの消失点を通る線を引く、それらの線同士の交点を取る、という操作を繰り返すことで、直方体の像を作ることができます。

////
[.theorem]
--
任意の点AとCの像がそれぞれaとcであり、投影面上の線分abと線分cdが交差しないとき、AB//CDかつABの像がabで、CDの像がcdであるような点Bと点Dが存在する。
--
[.proof]
--
abとcdが交差しないとき、AB//abとなる点Bを取ることができて、


[.theorem]
.定理
--
投影面上の任意の四角形abcdについて、abcdを像とするような平行四辺形ABCDが存在する
--
[.proof]
視点をEとする。
abcdが何組の平行な辺を持つかで分類する。
[1] 2組の平行な辺を持つ場合、abcdはすでに平行四辺形なので、ABCD=abcdとすれば定理（投影面上の点の像）より成り立つ。
[2] 1組の平行な辺を持つ場合、命名の対称性よりabとdcが平行である場合だけを考える。
直線bcとdaの交点をVとし、EVとabとともに平行で、Eを通らない平面αを一つ考える。
平面αと直線Eaの交点をA、直線Ebの交点をB、直線Ecの交点をC、直線Edの交点をDとすると、ABCDの像はそれぞれabcdである。

直線ABはα上にあってαは直線abと平行なのでab//AB、同様にdc//DC、よってAB//DC。
bcV、EbB、EcCが同一直線なので、直線BCと直線EVはともに平面Ebc上にある。直線BCはα上にあって、α//EVなので、BC//EV
同様にCD//EVなので、

EAaBbは同一平面上なので、AB//ab
AB//ab//cd
--
////

しかし、消失点の位置を特定する方法はまだ限られています。また、対象上の長さを測る方法などはまだ全く知りません。これからはどのように消失点の位置を特定するか、ということを考えていきます。


ちなみに、面対称な図形の対応する点をそれぞれ繋ぐと、これらはすべて平行になるため、その像は平行であるか、一つの消失点で交わるかのいずれかになります。人間の顔や自動車のような複雑な形を定規で作図することはできませんが、描かれたそれらが歪んでいないかを検証したり、フリーハンドで描く時の下書きにしたりすることができます。

まだ複雑な形状は扱っていないのでゼロから作図することはできませんが、


例題：
互いに直角であるようなlとmがあり、直線lの消失点がV₁で、直線mの消失点がV₂と与えられていたと想定し、これを利用して長方形の像を描く。

互いに直角であるようなlとmとsがあり、直線lの消失点がV₁で、直線mの消失点がV₂、直線sの消失点がV₃と与えられていたと想定し、これを利用して直方体の像を描く。

長方形の像が与えられた時に、2x2の4つの長方形に分割する。

長方形の像が与えられた時に、その1辺を3分割する。

長方形の像が与えられた時に、その対角線を引く。