---
layout: base.njk
title: 拡張された像
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]


TODO: 縮退を除外

== 無限遠点の像

直線lの消失点を求める操作を思い出してみましょう。「視点Eを通りlに平行な直線vを引いて、直線vと投影面の交点Vをもとめると、Vが消失点となる」のでしたね。これを今覚えた「無限遠点」の言葉を使って言い換えてみましょう。「Eを通りlに平行な直線vを引く」という操作は、lの「方向」に相当する無限遠点をPとすると、「EとPを直線で結ぶ」ことに相当します。そして、EPと投影面の交点が消失点Vになりますね。

次に、点の像の求め方を思い出してみます、点Pの像は（虚像を含めると）、EとPを直線で結んで、EPと投影面との交点を求めるのでしたね。

あれ、ずいぶんと似ていますね。

この点Pが無限遠点である場合の像についても、通常の点と同じように、像を定義してみましょう。無限遠点Pはある「方向」を示しているので、EとPを直線で結ぶことは、Eから見てその「方向」に向かう線を引くことに相当します。すると、その線と投影面の交点がPの像になります。

これはまさしく、Pが示している「方向」の消失点そのものですね。つまり、「無限遠点の像は消失点になる」と言えそうです。（ただし、無限遠点は向きを持たないので、投影面より前にあるか後ろにあるかが定義できません。なので、これは像とも虚像とも区別がつかないことになります）


== 拡張された直線の像

ここまでで、虚像と無限遠点を導入しました。この条件下で、直線の像を考えてみましょう。アニメーションで見てみると以下のようになります。青く表示されるのが虚像です。

{% sketch "sketches/image-of-line", {"virtual": true} %}

L上で点Pを動かすと、Pが臨界面に近づいたときにPの像ははるか遠方に行きます。そして、Pが臨界面より後ろに行くと、代わりに消失点の反対方向からPの虚像が表れます。直線lが無限遠点Pを通るとき、lの消失点VはPの像になっていました。ということは、消失点Vもlの像に含んでよいことになります。

まとめると、投影の前後で以下のような対応関係があります。

臨界面より後ろの部分→虚像
臨界面との交点→投影面上の無限遠点
臨界面より前の部分→実像
無限遠点→消失点

無限遠点の像＝消失点と虚像を合わせることで、「直線の像は消失点を通る直線である」と言えるようになりました。

TODO: 定理として示す。

////
== 投影面に平行な直線の消失点

TODO: 話をまとめる

無限遠点を考える目的は、「平行な場合」の場合分けを無くすことでした。もう一つ、ぜひなくしたい場合分けがありますよね。定理（投影面に平行な直線）では、投影面に平行な直線は消失点を持たないことになっていたので、これが面倒な場合分けになっていました。これについても考えてみましょう。

「消失点は無限遠点の像である」はこの場合にも使えるでしょうか。

lが投影面と平行なときについても、普通の直線と同じように消失点を求めてみます。まず、lに平行で視点Eを通る直線vを考えて、vと投影面の交点を求めるのでしたね。vと投影面は平行なので、交点はvの無限遠点Vです。v//lなので、これは同時に、lの無限遠点でもあります。これが「消失点」と呼べそうです。

そして、lの像l'はl//l'を満たすのでした。つまり、l'は消失点を通る直線です。これはさっきの投影面と平行でない直線の像と全く同じ性質です。見事、投影面に平行な場合も、全く同じ言葉で説明できるようになりました。

投影面と平行なlが無限遠点Pを通るとき、直線EP（つまりEを通りlと平行な直線）は投影面と平行な直線です。このとき直線EPと投影面の交点は無限遠点Pです。なので、Pが消失点になりそうです。確かに、lの像はlと平行なので、lの像も同じ無限遠点Pを通ります。確かにこれはPが消失点ということができそうです。

このとき、EPは投影面と平行になってしまいますが。その場合Pが投影面との交点ということになるのでしたね。

しかし、lとmは平行なので、今は無限遠点Pで「交わって」いると考えます。lとl'も平行なので、同じ無限遠点Pで交わっていますね。そして、この点Pは投影面上にあります。

l'とm'は
これは定理（投影面上の点の像）の拡張で、P自身がPの像と言えます。
////

== 無限遠直線の像

消失点が無限遠点の像であったのと同様に、　*消失線は無限遠直線の像と考えることができます*

[.theorem]
.無限遠直線の像
--
平面α上の無限遠直線をlとすると、lの像はαの消失線となる。
--

[.proof]
.簡易的な証明
--
（射影幾何を使うので交点を持つかの判定は省略する。像か虚像かは定義できない）
像の定義より、lの像は視点Eとlで定まる平面と投影面の交線である。
消失線の定義より、これはαの消失線と一致する。■
--

=== 直線と無限遠直線の交わり

無限遠直線lと通常の直線mが同一平面上にあるとき（lが表す「向き」で、かつmが乗るような平面が存在するとき）、lとmはmの無限遠点で交わります。

この状況の像を描いてみると理解しやすいでしょう。無限遠直線lの像l'は消失線であり、mの無限遠点Pの像はmの消失点Vです。Pはl上の点なので、Vはl'上の点となります。mの消失点が消失線上にあることを表しています。

つまり、定理（消失線上の消失点）は直線と無限遠直線の交点の像を表していたのです。