---
layout: base.njk
title: 円の像　その3
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]


== 重大な「仮定」

その1、その2では、円の性質について厳密な観点から議論しました。

しかし、このページでは以下の3つを前提として、円の像を実用的に描く上での注意点を考えていきます。

「仮定」
- 円の像は楕円である。
- 回転体の像は、軸の像に対して線対称である。
- 円の軸の像は楕円の短軸に一致する。

これらはいずれも例外があるものの、、絵を描く人の間で広く信じられているものです。視心付近において、大きすぎない円を描く限りにおいては、「近似」として成り立つと考えられるものです。これらがどこまで正しく、どこが厳密には間違っていて、どのような場合に例外が生まれるのかは、前のページを参照してください。

それよりも、この「前提」を認めたとしても見落としやすい注意点が無数にあるので、それらをしっかり理解し運用できるようになることの方が重要です。

== この仮定を置く妥当性

「その1」「その2」を読んできた先に読んできた方は、この前提がどこまでが正しく、どこから間違っていて、どのような反例が作れるのかを説明できるでしょう。

この「前提」は、標準画角で絵を描く限りでは十分正確ですが、画角を広げていくとその限りではありません。これから紹介する方法はすべてこの前提に成り立っているため、広い画角では、「数学的に正しい」円の像との誤差が無視できなくなっていきます。

しかしこの「前提」が絵を描く人の間で広く信じられているのも事実です。（稀に、「楕円である」から信じていない人もいます。が、「その1」「その2」で出したような反例はほとんど知られていません）。

特に、長年この方法で絵を描いてきた人は、これを理由に、しばしば「3DCGは間違っている」や「広角レンズが歪んでいる」などと批判的に言うことすらあります。3DCGや（十分に高精度に作られた）レンズは理想カメラに近い挙動をするので、厳密に正しい円の像を描いてくれているのですが、手書きの楕円を描き慣れた人や見慣れた人からすると、逆に違和感の原因になることすらあるわけです。

そのような厳密さを手書きの絵やイラストに取り入れるのは、手間がかかる上にメリットが少ないです。この「前提」を取り入れることで、大幅に理解しやすくなり、作図も楽になります。そこで、いったんこの「前提」を認めるのは、厳密ではないにせよ、十分合理的だと考えられます。

それよりも、この「前提」を認めたとしても見落としやすい注意点が無数にあるので、それらをしっかり理解し運用できるようになることの方が重要です。

== 軸の探し方

{% sketch "sketches/image-of-circle-basic", {"roll": true} %}

楕円の軸の方向とその長さを決めることができれば、楕円は一意に定まります。

原則は次の手順です

. 円の軸の像を描く。これが仮定(3)により、楕円の短軸と一致する。
. 直線上で短軸の位置と長さを決める。
. 短軸に垂直2等分線を引いて、長軸とする。
. 長軸と短軸それぞれに対称になるように楕円を描く。

長さについてはまだ扱っていないので、軸の方向だけを考えます。一点透視図法を学ぶると、正方形の像を描いてそれに内接するような楕円を描くことで、長さについても正確に扱うことができます。

とにもかくにも、円の軸の像を先に定めて後から長軸を決めるのが鉄則です。これを誤って、長軸を先に定めてしまったり、なんとなく「長そう」な方向を長軸にしてしまうのがよくある失敗です。

失敗例１　周囲に対称性を崩す要因があるとき
　マグカップの取っ手や、ビーカーの注ぎ口などがあった時に、それを通る線を長軸だと誤認することがよくあります。これらは面対称な図形の対称軸（正中線）ですが、回転体は回転対称なので、それらの要因によって像の形が変化することはありません。

失敗例２　軸の像が倒れているとき
　カメラの回転対称性により、軸が倒れていても、その軸が楕円の短軸であり、回転体の対称軸とするべきなのですが、誤りやすいです。長軸を鉛直に取ってしまうなどの失敗例があります。

実用上では、自分の描いている絵の中で回転体の対称性が意図せず対称性が大きく崩れていることに気付けないことや、正確に線対称に描けないこと、のほうが問題になることが多いです。

当然、回転体の像が線対称であると意識することで、歪みとして見えやすいです。

楕円の軸を見つけることは重要です。軸で4等分したそれぞれが合同であることを意識することで、フリーハンドでも精度の高い楕円を描くことができるからです。

== 円の中心

円の像が意外にも前後に対称な楕円になることはすでに述べたとおりですが、中心について考える場合はその限りではありません。

円周だけを見ると奇跡的に一致するというだけで、変形自体は当然非対称に行われています。

円に外接する正方形とその像を考え、正方形の中心を作図するとわかります。円の輪郭だけを書けば良い場合には意識する必要はありませんが、中心に点を描かなければいけない場合には必要です。
また、同心円の像を描かなければいけない場面でも、これを意識する必要があります。

TODO: 同心円スケッチ


== 楕円の作図法

このページでは、楕円の作図法について扱います。ほかのページは図形的な性質についてフォーカスしているので、具体的な作図法だけでページを作るのは異例のことです。直線は定規で書けるのでその組み合わせ方が問題であるのに対して、楕円はそれ自体がどうやって描くのかが問題になるからです。そもそも定規とコンパスで描ける道具ではありません。


== 楕円の定義と性質

まず、楕円がどのような形で、どのような性質を持っているのかを確認しておきます。楕円には複数の定義の方法があり、これらがすべて同じ形を表しています。


デジタルであれば、楕円ツールや線対称ツールを使うことで、容易に描画できるし。アナログでも、型紙を作る、長さを測る、コンパスを工夫して用いるなど、道具と方法を適切に選ぶことで、線対称を描くことができる。フリーハンドで描く場合も、対称性などの性質を知っていると自分の絵の歪みに気付きやすい。

== 楕円の描き方「性質を熟知して描く」

楕円の描き方にはいくつかあります。

私のおすすめの方法です。これは技能がなくとも、知識と時間を使えば必ず描ける方法です。時間をかけて正確に描きこんでいくデッサンなどに適しています。

楕円を描く際には、*必ず* 長軸と短軸を決めるところから初めます。まず、楕円の中心O、長軸の両端AとB、短軸の両端CとDを作図します。これらをどのような順で作図していくかは場合によりけりです（ABを二等分してOを得る場合も、AOを延長してBを得る場合もあるでしょう）が、最終的に OAとOB、OCとODの長さが等しいこと、ABとCDが直交していることを確認してください。そうなっていないと、楕円にはなりません。

TODO: 図を作る

次に、Aを通りCDに垂直な線、Bを通りCDに垂直な線、Cを通りABに垂直な線、Dを通りABに垂直な線を引きます。これらの線はそれぞれ、楕円の接線となります。十分に伸ばすと、4等分された長方形ができるはずです。

TODO: 図を作る

次に、その4等分された領域それぞれに、フリーハンドで曲線を描きこんでいきます。枠線とちょうど接していること、つまり角度がついて尖ったり、直線の部分が入ったりしないように気を付けてください。

TODO: 図を作る

それぞれ描いたら、4つの領域がそれぞれ合同、つまり曲がり方や面積が一致していることを、目測で確認します。画面を回して長軸が垂直になる向きと短軸が垂直になる向きそれぞれで見て、左右対称になっていることを確認してください。もし非対称であれば、修正してください。

TODO: 図を作る

== 楕円の描き方「フリーハンドで描く」

熟練した人は、勢いよくフリーハンドで描くこともできます。建築家やプロダクトデザイナーは短時間のスケッチで多数の楕円を描く必要があるため、この方法を好む傾向があります。

フリーハンドで描く場合も、まず長軸と短軸は決めておきましょう。そこに何度か空中で楕円を描きながら狙いを定め、イメージができたら、勢いよく描いてみてください。

描けた楕円について、よい例と悪い例を列挙します。
TODO: 図を作る
