---
layout: base.njk
title: 無限遠点と無限遠直線
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]

== 「平行でないとき…」をなくしたい！

「平行なら…」「交点を持つなら…」というような場合分けが択残ありました。この場合分けもなくしたいですね。

通常のユークリッド幾何学では、平面上の2つの線は平行であるか、1点で交わっているかのどちらかです。これを「同一平面上の2つの線は常に1点で交わる」と *書き換える* ことにします。

== 無限遠点

これは、無限遠点という仮想の点を導入することに相当します。

[.definition]
.定義（無限遠点）
--
直線lに対して、以下の性質を見たすような「lの無限遠点P」と呼べる点が存在する。

(1) 別の直線mがl//mであれば、mもPを通る。 +
(2) 任意の点QとPを結ぶことができて、直線PQはlに平行である。
--

無限遠点というのは特定の点ではなく無数にあり、いわゆる直線の「方向」と対応します。同じ「方向」の直線は同じ無限遠点を通り、異なる「方向」の直線は通りません。ただし、「方向」といっても平行かどうかだけを見ているので、ベクトルと違って180度違う向きは同じ向きになります。直線のどちらにつながっているかとかは考えません。

これは別に平行線がどこかでぐにゃりと曲がって交差するようなイメージを持つ必要はありません。「無限遠点を通る」という言葉が出てきたときには、「ああこれは要するに平行のことを言っているんだな」と読み替えてくれれば問題ありません。言葉遊びのようなものだと思ってください。

TODO: 図を入れる　平行マークで描くとイメージしやすいだろう

例えば、直線lが無限遠点Pを通っているとします。別の直線mがlが平行であれば、つまり同じ「方向」であれば、mは同じ無限遠点Pを通ります。このときlもmもPを通っているので、Pで交わっていると考えることができます。一方、mがlと平行でなければ、つまりlとmが別の「方向」であれば、mはPとは別の無限遠点Qを通るので、Pでは交わりません（同一平面上であれば無限遠点でない交点を持ちます）。

(2)は無限遠点に対して直線を引く操作を定めています。l上にない点Qがあったとして、「QとPを直線で結ぶ」といったら、（従来の言葉で言うと）Qを通りlに平行な線を引く操作に相当します。そうして得た直線をmとすると、mとlは平行なので、確かにmはPを通っています。

こうすると、「平行になるように線を引く」という特殊な操作を、あたかも「点と点を繋ぐ」と同じことをしているかのように考えることができます。

ちなみに、平面αと直線lが平行なとき、lの「方向」を表す無限遠点Pは「α上にある」ということができます。なぜなら、平面α上にl//mとなる直線mを取ることができて、無限遠点Pはm上にあり、mはα上にあるからです。この無限遠点Pは平面αと直線lの両方が通っているので、αとlの交点ということができます。

== 無限遠直線

[.definition]
.定義（無限遠直線）
--
αが平面の向きに対応する無限遠直線と呼べる直線が存在する。ある直線lがα上にあるか、αと平行なとき、αとlは交点を持つ。
--

lの無限遠点Pとmの無限遠点Qを結ぶ無限遠直線PQは、lとm両方に平行な平面の「向き」に相当します。平面幾何であれば無限遠直線は一つだけで、空間図形を考えると無数にあります。

== これでどのように場合分けが減ったか

TODO: 書く
射影幾何学では、2つの直線は同一平面上であれば必ず交点を持ち、直線と平面は必ず交点を持ちます。

== モチベーションとのつながり

TODO: 書く。場合分けが減る、情報が増える