---
layout: base.njk
title: 円の像　その2
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]

== どんな楕円かを知りたい

「その1」では、円の像は（ほとんどの場合で）楕円であることを確認しました。*ただし、どんな楕円であるかについては、まだ一切判明していないことを忘れないでください*。楕円を描くためにはどんな楕円か知る必要がありますね。

これを解き明かすため、今回は別の視点から円について考えていきます。

楕円には必ず、長軸と短軸があり、長軸と短軸が定まれば一意に定まります。（長軸と短軸の位置が決まればそこから焦点を作図できることを確認してみてください）

「その1」の議論で円の像が楕円であることが分かっているので、あとは「長軸と短軸がわかれば」円の像が描けそうです。しかし、長軸と短軸の定め方は *自明ではありません*。直観に反例が多数あります。今回はそれを確認します。

== 円は回転体でもある

ところで、円には重要な性質があります。回転対称性です。

[.definition]
.定義（回転体）
--
直線を軸として、その軸に対して回転対称な図形を回転体と呼ぶ。
--

NOTE: 本テキストで単に回転対称といった時には、任意の角度で回転させても重なることを指します。つまり、2回対称や3回対称ではなく、無限回対称のことを指します。

[.definition]
.定理（円の軸）
--
平面α上にあって、Pを中心とする円は、Pを通りαに垂直な直線lを軸とする回転体である。
--
[.proof]
.証明
--
対称性より明らか。
--

「円の軸」というのは数学ではあまり使わない言葉ですが、ここでは、円の像を考えるときに *非常に重要な* 概念なので、このように呼ぶことにします。

円だけでなく、円柱や円錐（直円錐）、球やトーラスなども回転体の一種です。特定の断面図を軸を中心に回転させたときに通る領域が回転体になります。円は、断面が点である回転体で、断面を長方形にすれば円柱、三角形にすれば円錐になります。

現実への応用では、皿、瓶、ワイングラスなどの複雑な形も、ラベルや模様のようなディティールを除けば回転体と考えることができます。取っ手のついたマグカップは回転体ではありませんが、取っ手を除いた部分だけで言えば回転体です。このように、実用上 *円を描く必要があるのは、ほとんどが回転体の一部* です。

（強引に言えば）かなり回転体とは言いづらい図形（サイコロのように立方体に円が書かれているものとか）であっても、円自体が回転体なので、円以外のところを無視して円に注目し、その軸を考えてください。

図形が回転対称であるということは、*図形を回転させても像の形は変化しない* ことを意味します。

以下は透視図法で円を描いた図です。円と周囲のグリッドの関係を見てみると、円が回転対称であるため、軸を中心に回転させても像の形は変化しないことが分かります。

{% sketch "sketches/circle-basic", {"grid": true} %}

== 回転体の像と対称性

[.theorem]
.定理(回転体の像)
--
回転体の軸の像が視心を通るとき、回転体の像は軸の像に対して線対称である。
--
[.proof]
.証明
--
回転体の軸をl、lの像をl'とする。 +
Eとlで定まる平面をαとすると、l'はα上にある。 +
視心がl'上にあるため、視軸はα上にある。したがってαは投影面に垂直。 +
投影面と回転体はαに対して面対称なので、対称性により回転体の像はl'に対して線対称である。■
--

さて、この対称性から、次の主張が示せます。

[.theorem]
.定理（楕円の軸）
--
直線lを軸とする円Cの像が（円でない）楕円C'で、lの像l'が視心を通る場合、l'の像はC'の長軸または短軸と一致する。
--
[.proof]
.証明
--
C'は円ではない楕円なので対称軸は長軸と短軸の2つしかない。 +
一方で、定理（回転体の像）より、C'はl'に対して線対称である。 +
したがって、l'はC'の長軸か短軸のどちらかと一致する。■
--

NOTE: 似た言葉ですが、円の軸は円が存在する平面に対して垂直な直線であるのに対し、楕円の長軸や短軸は楕円が存在する平面上にある直線で、まったく違うものを指しています。

証明を読むとわかるとおり、これらの定理は回転体の軸が視心を通っている場合の対称性を利用した主張です。つまり、軸の像が視心を通っていないときには対称性は崩れます。楕円であることには違いないのですが、円の軸と楕円の軸が一致せず、傾くことが確認できます。

{% sketch "sketches/eccentric-circle" %}

*しかし、実用的に絵を描く上では*、画面上どこにあっても円の軸の像と楕円の軸を一致させて描くことがほとんどです。通常描かれる範囲の画角では問題にならないため、「近似」しているといえるでしょう。

// {% sketch "sketches/accurate-circle" %}

== 楕円の長軸と短軸

定理（楕円の軸）で示されたのは、長軸または短軸のどちらかに一致することのみです。円の軸の像と一致する方とそれに対して垂直な軸のどちらが長軸である、つまり長いかは定かではありません。実際、楕円が消失線から離れるほど、楕円は前後方向が伸びていき、いずれ逆転します。以下はその様子を極端に広い画角で描いたものです。

{% sketch "sketches/circle-large-pov" %}

円の像が消失線から離れるほど「正円に漸近する」、つまり短軸と長軸の比がどんどん1に近づくのみで、逆転することはないと考える人が多いのですが、図のように外接する正方形と補助線を入れて、共線や交差を保ったまま描こうと思うと、像がと消失線からの距離に比例して（単なる単調増加ではなく厳密に定数倍に）前後を長くしていくしかないことが分かります。

*が、実用的に絵を描く上では*、そのような例は無視して、回転軸と一致する方の軸を自明に「短軸」、それに垂直な軸を「長軸」と呼ぶことがほとんどです。これもあくまで近似で、画角が極端に広い場合や、投影面と円がほぼ平行である場合（円が乗る消失線が視心から遠い場合）には例外も生じますが、ほぼ無視されています。