---
layout: base.njk
title: 共点の保存2
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]

「共点の保存」で確認したように、交点が臨界面より後ろにある場合には、実際には交点の像がなくても、直線の像を延長すると交わるという性質がありました。これは今まで無視してきた臨界面より後ろについても、何らかの幾何学的な法則が成り立っていると考えるのが自然です。

さらに、「共点の保存」の証明では、線同士が平行である場合とそうでない場合、投影面と平行である場合とそうでない場合、の組み合わせで4パターンの場合分けがありましたね。「シンプルな定理なわりに証明が長いなぁ」と思いませんかでしたか？　これをもっとシンプルに考えたいですよね。

== 共点の保存

射影幾何学の言葉で「共点の保存」について考えてみます。

まず、共点というのは「3本以上の直線が互いに平行である、または一点で交わる」という概念でしたが、「3本の線が平行である」というのは「同じ無限遠点で交わっている」ということなので、これらはどちらも「3本の直線が一点（ただし無限遠点の場合あり）で交わる」といって差し支えないです。

で、定理（共点の保存）の主張は、「3本以上の直線が共点である場合、その像も共点である」でしたね。これは今からするともう当たり前です。三本の直線が1点Pで交わっている場合、Pを通る直線の像はPの像pを通る直線になるので、三本の直線が1点Pで交わっている場合、当然その像も一点で交わります。

前回の(1-1)～(2-2)の4つの場合分けは、いまや、交点が普通の点か、臨界面上にあるのか、投影面と平行な無限遠点なのか、そうでない無限遠点なのか、の違いで *しかない* ことがわかります。

念のため、射影幾何学を知らなかった頃の言葉に翻訳しておきます。

. Pを通る直線の像はPの像pを通ります。これが普遍原則です。
. Pが普通の点であるとき、臨界面より前にあればpは目に見える像、臨界面より後ろにあればpは虚像になりますが、いずれにせよです。
. Pが投影面と平行でない無限遠点であれば、pは消失点になるので、Pを通る直線の像は消失点を通る直線になります。
. 点Pが臨界面上にある普通の点であれば、pは投影面上のEPの無限遠点になるので、どの像も平行になります。
. 交点Pが投影面と平行な無限遠点であれば、pは投影面上の無限遠点P自身になるので、どの像も平行になります。

虚像を描いてみると分かりやすいでしょう。

{% sketch "sketches/concurrent", {"virtual": true} %}