---
layout: base.njk
title: 射影幾何までの道のり
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]

== なぜ、射影幾何学を考えるのか

ここまで、作図法や透視図法の理解に必要な定理を確認してきました。これは当たり前のユークリッド幾何学に基づいて考えてきました。
実は、これらの透視図法の性質は、「射影幾何学」の言葉を使うと、非常にすっきりと、簡潔に書くことができます。

ただし、数学で扱う射影幾何学と、美術で扱う（目に見える）透視図法はわずかに違います。そのため、両者がどの点で似ていて、どの点で似ていないのかも、正確に理解する必要があります。

先に明かしてしまうと、このセクションでは透視図法の作図に使える新しい事実は一つも登場しません。これまで登場した定理、特に「共線の保存」と「共点の保存」を射影幾何の言葉で書き直すだけです。これは悪い言い方をすると言葉遊び的な側面が強いものです。

しかし、この章を通じて射影幾何の視点から理解しなおすことで、より単純で一貫した理解を得ることができるかもしれません。

== 理由① 場合分けを減らしたい

これまで扱ってきた定理には、様々なパターンがありました。例えば平行な場合と交わる場合、投影面と平行な場合とそうでない場合、臨界面より前にある場合と後ろにある場合、像を持つ場合と持たない場合、など多数の場合分けがあって、かなり厄介でした。

ここからは定理をできるだけシンプルに、簡単に書き直すため、このような場合分けがなくなるように、定義や公理を拡張していきます。

== 理由② 「像を持たない」以上の情報を知りたい

ここまでの説明では、点が像を持つ場合と持たない場合があったり、直線の全体が像を持つ場合があったり臨界面より前の部分だけが像を持つ場合があったりしましたね。

これは場合分けがあって複雑になるだけでなく、像がないことによって「部分の像」などの定理が適用できずに不便になる部分があります。

像や交点の定義を拡張することで、これまで単に「像を持たない」としてひとくくりにしてしまっていた部分に、どのような理由で像がないのか、強いて像があるとしたらどこにあるのか、などといった情報を与えることができます。

次のページから、その具体的な方法を紹介していきます。