---
layout: base.njk
title: 円の像　その1
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]

今回からは、円と回転体の描き方について考えます。円とその周辺に関してはたくさんの誤解が起きやすいので、「その1」～「その3」の3ページに分割します。

== 円の像は楕円？

さて、透視図法における円の像はどのように考えられるでしょうか。以下の定理が成り立ちます。証明は後に回しますが、これは近似も誇張もなく、厳密に成り立つ定理です。

[.theorem]
.定理（円の像）
--
円の全体が像を持つとき、円の像は楕円になる。
--

NOTE: 円も楕円の一例です。あまり数学的な言葉づかいではないですが、通常の円が楕円でないことを強調するために「正円」と呼ぶこともあります。

楕円というのは以下のような図形です。単に「いびつに歪んだ円」という意味ではありません。2つの（円の場合は無数の）対称軸を持ち、短軸と長軸（あるいは二つの焦点と距離の和）を定めたら一意に定まる、自由度の低い図形です。

// 楕円がどのような形で、どのような性質を持っているのかを確認しておきます。楕円には複数の定義の方法があり、これらがすべて同じ形を表しています。

TODO: 楕円の図を入れる


もし「円を斜めから見たら『潰れる』のだから楕円になるのは当然だ」と思った人がいたら、ちょっと待ってください。そんなに簡単な話ではありません。（まだ扱っていませんが）平行投影であれば単に図形を引き延ばしたり潰したりしていると考えることができるので当たり前といえるかもしれませんが、今考えているのは透視図法です。

透視図法においては、平行線が平行にならず、正方形の像が不等辺四角形になることを考えると、これは極めて非自明な主張です。特に、左右はともかく、前後（奥行き）方向についても対称な形になるのは、実に不思議なことです。卵型やまんじゅう型になってもおかしくないように思えます。

が、そうはなりません。 この主張は *数学的に正確に成り立ちます* 。

== 直観的な理解①

まず、直感的な理解を紹介します。

透視図法において、正方形の像が奥に向かって細くなることや、奥にある正方形の像が徐々に小さくなっていくこと
は、「直線の像」で紹介した通りです。このことと、円の像が前後に対称な楕円になることは、一見すると、相反しているように感じます。

しかし、これらが矛盾せず両立することが、以下の図でわかります。

{% sketch "sketches/circle-parallel-square" %}

これは円を平行な接線で挟み、接点同士をつなぐ長方形を引いた状況を、透視図法を使って「斜めから見た」状況です。

まず、斜めから見たことで平行線の像が消失点で交わるようになります。また、接線は保存するので、斜めから見ても平行線の像は楕円の接線になっています。このとき、接点が「奥」に移動するのに伴って、直径の像が奥に移動し、奥の面積が小さくなっています。

別の視点からこの観察を解釈してみます。見る角度を変えていくと同時に、(1)楕円がつぶれる、(2)奥に向かってすぼまる(3)前後の面積差がつく、という三つの変化が同時に起きます。もし、(2)だけならたまご型になるだろうし、(3)だけならだけなら（逆さ）まんじゅう型になるであろうところが、ちょうど *両方が同時に起きる* ことによって、その効果が「相殺」し、楕円であることと両立できる、と見ることができます。

TODO: 図を作る

ちなみに、どれくらい消失点が近づいて、どれくらいの奥行き割合になるかは、*楕円の形だけでは決まりません*。 (2)と(3)がぴったり相殺することは分かりましたが、(1)と(2)、(1)と(3)の関係はまだわかっていないからです。これは *画角に対する円の大きさによって決まります*。以下のアニメーションで楕円は変形していませんが、画角次第ではどの瞬間もあり得る状況です。画角と奥行きの関係がどのように定まるのかは、 03-02 で説明する予定です。TODO:リンク 

{% sketch "sketches/ellipse-and-line" %}

== 直観的な理解②

直感的な理解①では、楕円であることと *相反するわけではない* ことが分かったのみで、まだ「楕円である」とは言えません。もう少し証明らしく考えます。

例によって視点から円全体を「なぎ払う」ようにビームを動かすことを考えてみましょう。ビームが通る部分は円錐形になりますね。それを投影面で切った断面が円の像になります。

NOTE: ある平面図形を底面とし、平面上にない頂点について、頂点から平面図形まで伸ばした線分や半直線を集めた図形を錐体と呼びます。円錐は底面が円の錐体です。円に対して視点が斜めにありますが、一点に

そして、 *円錐を斜めの平面で切ると、楕円が得られる* ことがよく知られています。つまり円錐の細い方か太い方か関わらず、対称な形になるのです。これは、透視図法における円の像がまんじゅう型や卵型にならず楕円になることと似た驚きがあります。これを理解できれば円の像が正確に楕円になることを理解したと言えそうです。この問題についての幾何的な証明については以下の動画が詳しいです。

++++
<div style="text-align:center">
<iframe width="560" height="315" src="https://www.youtube.com/embed/f12lJrFnVjs?si=Y_45SdXyruf2_5qo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
</div>
++++

しかし注意深く見ると、この動画で扱われている幾何的な証明は、円の軸上に円錐の頂点が存在する「直円錐」の場合に限定されることに気付くと思います。今回必要なのは、頂点の位置がどこにあっても円の像が楕円になることなので、対称性が低い問題になっています。
傾いた円錐に球は内接しないので、残念ながらこの証明は使えません。今示したい事実と、この証明に直接の関連性はなく、あくまでも「似た問題」から、感覚的な「納得感」を得るために紹介しました。

== 円の像は二次曲線になる

ここから、厳密な証明に移ります。前提知識は座標幾何と、線形代数による回転です。

座標幾何を使うと図形に含まれる点が満たすべき条件を方程式で表すことで、数値的に図形を扱うことができるようになります。例えば半径rの円は\(x^2 + y^2 = r^2\) で表されますし、空間中の平面は\(ax + by + cz + d = 0\) で表されます。それから、行列の基本的な性質（といっても、回転が一次式で表せることと、それが逆変換できることだけ）です。

まず、どんなN次曲線についても成り立つ強力な定理を示してしまいます。

[.theorem]
.定理（N次曲線の像）
--
視点を通らない平面上のN次曲線の像はN次曲線の一部になる。
--
[.proof]
.厳密な証明
--
座標幾何を用いる。カメラの対称性より、視点Eを原点\((0, 0, 0)\)、投影面を平面 \(z=1\) とする場合に固定する。このとき、点\((x,y,z)\)の像は、\(z \gt 0\) のときに \((x/z,y/z,1)\) にある。

xy平面上のN次曲線は、xとyのN次方程式 \(f(x,y)=0\) で表せるが、N次以外の項があると扱いづらいので、ダミー変数\(z=1\)を置いてN次の同次方程式 \(f(x,y,z)=0\) かつ \(g(x,y,z)=0\) と表す。ただし、\(g(x,y,z)=z-1\)で、\(z=1\)のときに\(0\)になる一次式である。

xyz空間中で原点を通らない平面αを考える。平面αを\(z=1\)に移動する直交行列を\(A\)とする。

\(z=1\)上のN次曲線 \(f(x,y,z)=0\)かつ\(g(x,y,z)=0\) に\(A^{-1}\)を作用させた、\((f \circ A)(x,y,z)=0\) かつ  \((g \circ A)(x,y,z)=0\) は、α上のN次曲線である。\(A\)は相似変形なので、\(f\)を適切に選ぶことでα上の任意のN次曲線と一致させることができる。また、\(A\)は線形変換であるから、多項式と合成しても次数は変わらない。したがって、α上のN次曲線は、N次同次方程式 \((f \circ A)(x,y,z)=0\) と 一次方程式 \((g \circ A)(x,y,z)=0\) の連立で表すことができる。

ここではα上のN次曲線の像が投影面上のN次曲線の一部になることを示せばよいので、定理（像の必要十分条件）のうち[1]だけ示せばよい。したがって、示すべき主張は以下の通りである。

任意のN次同次方程式 \(f\) と 一次方程式 \(g\) について、あるN次同次方程式 \(h\) があって、\(x,y,z\) が \((f \circ A)(x,y,z)=0\) と \((g \circ A)(x,y,z)=0\) かつ\(z \gt 0\)を満たすとき、\(u=x/z, v=y/z\) は、\(h(u,v,1)=0\) を満たす。

これは\(h=f \circ A\)と置けば満たされる。（∵同次性より、\((f \circ A)(x,y,z)=z^N(f \circ A)(x/z,y/z,1)=0 \Leftrightarrow (f \circ A)(u,v,1)=0\)）

よって示された。■
--

この証明は抽象的なので、ピンとこなかった場合は円をあらわす二次式を立てて計算してみるとよいでしょう。

ちなみに、既に幾何的に示した事実ですが、1次曲とは直線のことなので、定理（N次曲線の像）は直線の像が直線の一部になることも含意しています。とても幅広い定理です。

定理（N次曲線の像）と定理（位置連続性の保存）を組み合わせて利用すると、円の像が二次曲線になることがすぐに分かります。二次曲線は楕円だけでなく、放物線や双曲線も含まれるので、視点をうまく設定することでそのような例も作ることができます。

[.theorem]
.定理（円の像）
--
(1) 円の像は一般に二次曲線になる。 +
(2) 円の全体が像を持つとき、円の像は楕円になる +
(3) 円が臨界面に接しているときは、円の像は放物線になる、 +
(4) 円が臨界面と交差しているとき、円の像は双曲線の枝の片方となる +
--
[.proof]
.簡易的な証明
--
(1) 円は二次曲線なので円の像も二次曲線である。 +
(2) 投影は連続写像であり、円と同相な二次曲線は楕円のみであるから、円の像は楕円になる。
(3) 円が臨界面に接しているとき、円の像は一点が無限遠点にある。これと同相な二次曲線は放物線のみであるから、円の像は放物線になる。 +
(4) 円が臨界面と交差しているとき、臨界面に対して投影面と反対側にある部分は虚像となる。これと同相な二次曲線は双曲線のみであるから、円の像は双曲線の枝の片方となる。■
--

こうして、円の像は二次曲線、特にほとんどの場合は楕円になることが示されました。放物線や双曲線になる例外はあるとはいえ、少なくとも、*どんな場合であっても、たまご型やまんじゅう型にはなりません*。これらは二次曲線ではないからです。放物線や双曲線になる例外は、円錐が切り方によっては楕円ではなく双曲線や放物線になることと対応しています。

アニメーションにすると以下のようになります。

{% sketch "sketches/image-of-circle-all" %}

日常的に目にする円の像は、(2)のケースが多いでしょう。双曲線をみることができるのは、十分に大きな円（例えば大きなフラフープや円形の広場など）があってその中に視点が入っているような場合です。双曲線は二つの部分（枝と呼びます）に分かれていますが、片方は虚像となるため見えません。先ほどのアニメーションで青で描かれているのが双曲線の場合の虚像です。

放物線になるのは臨界面と円が接する場合で、ちょうど楕円になるか双曲線になるかの境界にあるときです。視点が大きな円の円周の付近にある時、投影面の方向を調整することで見ることができます。

正確に言えば円の大きさや視点の位置は関係なく、臨界面と円がどう交差するかだけが問題で、円がどんな大きさでも視点がどこにあっても関係なく、投影面の向きを変えることで放物線にも双曲線にもできるのですが、小さい円では画角が不足して観測できないことが多いと思います。

手元にスマホやタブレットがあれば、面白い実験ができます（スマホのカメラは理想カメラではないですが、理想カメラに近いものと言えるでしょう）。スマホカメラにおける臨界面はちょうどスマホの背面で近似できます。カメラを起動し、これを身近な円、例えば時計などの縁にくっつけた時、像は放物線となります。フラフープや洗面器のような大きくて中空の円があれば、その中にスマホを入れると双曲線になるはずです。

== 円の像は（ほとんどの場合で）楕円になる

しかし、日常的に描く *ほとんどの* 場面では、円の像が楕円になる場合です。

なので、*次ページからは円の像が楕円であることをほぼ前提にして*、言い換えると、「円の全体が像を持つ場合に限って」円の像の描き方について考えていきます。

なお、まだ「円の像が楕円である」、つまり円周がたまたま楕円になるということが分かっただけで、*どんな楕円かについてはまだ何もわかっていない* ことに注意してください。

== 楕円の描き方への応用

ちなみに、定理（N次曲線の像）から、円だけでなく他の二次曲線の像も二次曲線になることが分かります。楕円も円と同様に二次曲線なので、楕円の像も二次曲線になります。

これはフリーハンドで楕円を描くときに、応用することができます。楕円の像は二次曲線になるので、楕円を長軸側のうまい位置から見て幅と高さが一致して見えたら、正確な円になっているはずです。フリーハンドで描いた楕円をそのように見たときに円がいびつになっていたら、それは楕円もいびつになっていることがわかります。ちょうど「アナモルフォーシス」を見るのに似ていますね。