---
layout: base.njk
title: 曲線
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]

本来連続性を扱うには微分幾何学の概念が必要になるのですが、やや厳密性を落として初等幾何の範囲で説明を完結させます。

== 曲線

直感的には、曲線は「繋がった線」のことです。この定義に従うと、円や直線、線分はすべて曲線です。「曲」という字が入りますが、直線や線分、折れ線などを除外するわけではないことに注意してください。
曲線であるということを指して「*位置連続*」ということもあります。グラフの連続性みたいなものですね。

初等幾何の範囲内でできるだけ厳密に定義しようと思うと、以下のようになると思います。

[.definition]
.定義（曲線）
--
図形上に点Pを取って、点Pを中心とする球面を考える。ある長さrがあって、rより半径が小さいどんな球面についても、球面と図形の交点が常に2つであれば、その図形は点Pの近傍で曲線である。
--

まどろっこしい定義をしていますね。どういうことが考えてみましょう。
ぐにゃぐにゃ曲がった複雑な曲線上に点Pを取って、Pを中心とする球を適当に考えると、交点はたくさんある場合もあります。しかし、球を小さくしていくと、交点はあるときからちょうど2つになり、それ以上どんなに小さくしても2つのままです。

TODO: 作る
// {% sketch "sketches/definition-of-curve" %}

一方、例えば平面に対して同様のことを考えると、どんなに小さな球を考えても、交点は常に無数に（つまり球を切る円周上に）存在します。つまり、平面は曲線ではありません。

また、端のある場合にはどうでしょうか。例えば線分ABについて、AやBを中心とする球を考えると、球を小さくしていったときに交点は1つになるので、、点AやBの *「近傍」では* 曲線ではないです。しかし、線分全体が曲線ではないというわけではなくて、線分AB上に（途中に）中心を取ると、交点は2つになるので、線分は（の内点近傍で）曲線です。どんなに端に近くても、端そのものでなければ、その端までの距離をrとするとrより小さな球体はすべて2個の交点を持つことに注意してください。

[.definition]
.定義（接線）
--
曲線C上の点Pに対して、点QをC上で動かしてPに限りなく近づけていったとき、Qをどちらから近づけても同じ直線lに限りなく近づくとき、lを「曲線Cの点Pにおける接線」と呼ぶ。
--

線の端や曲線が折れ曲がっているような場所では接線が定義できない。

[.definition]
.定義（接線連続）
--
曲線上のある区間において、区間中のすべての点において接線が定義できることを接線連続と呼ぶ。
--

直感的には、曲線に角がなく、滑らかであることを表す概念です。接線連続な曲線は折れ線などを除外するため、一般語の曲線に近づいたかもしれません。しかし、なお直線などは除外されていないことに気をつけてください。これはグラフで言う「微分可能」のようなものだと思うと理解しやすいです。

[.definition]
.定義（接する）
--
点Pにおいて曲線CとDが同じ接線を持つとき、曲線CとDは点Pにおいて「接する」と呼ぶ。
--

== 連続性の保存

さて、ここまで定義した曲線や曲面の像について、うれしい性質があります。

[.theorem]
.定理（位置連続性の保存）
--
定義域内において、曲線の像は曲線になる。
--

直感的に言えば、定義域から出ない限り、つながっていた線がちぎれることはないという主張です。

[.theorem]
.定理（接線の保存）
--
視点Eを通らない直線lが曲線Cに点Pで接しているとき、直線lの像は曲線Cの像に点Pの像で接する。
--

[.theorem]
.定理（接線連続の保存）
--
接線連続な曲線Cについて、Cのすべての接線が視点を通らないとき、Cの像も接線連続となる。
--

[.proof]
.証明
--
定理（接線の保存）より、曲線Cの各点における接線の像は曲線Cの像の接線となる。したがって、接線連続性が保たれる。
--

直感的には、滑らかな曲線は滑らかな像を与えるという主張です。

ただし、定理（位置連続の保存）と異なり、接線が視点を通る場合を除外していることに注意してください。そのような点においては、像に尖った角が生まれる場合があります。


