---
layout: base.njk
title: 投影法と遠近法
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]

== 遠近法
人間は二つの目を使い、その像の違いを脳で処理することで遠近感や立体感を認識しています。しかし、絵という平面のメディアでは（3Dメガネやレンチキュラー、立体視などの特殊な例を除き）、左右それぞれの目に異なる像を提供することはできません。
画家たちはこの制約の中で、あの手この手を使って見た者に *立体感を錯覚* させる方法を考案してきました。これらの方法を総称するのが *広義の*「遠近法(perspective)」です。

== 投影法
ところで、空間中に存在する立体物を、立体のまま絵の中に閉じ込めることはできません。*何らかの方法で立体から平面に変換する* 必要があります。墨を塗って魚拓を取る、切り開いて展開図にする、三面図を書いて形を伝える……立体を平面に変換して記録する方法は様々ですが、その中でも特に、投影と呼ばれる幾何学的な規則に従って立体を平面に写し取る方法を「投影法(projection)」と呼びます。投影法にも、どのような規則で写し取るかによって、様々な投影法があります。

一定の規則に従って立体を正確に平面に描くことは、遠近感を錯覚させる強力な手段の一つとなります。そのため、投影法は広義の遠近法の一部と位置付けることができます。一方で、空気遠近法に代表されるように、投影法とは関係のない遠近法もあるので、これを分けて考える必要があります。

=== 透視図法
*狭義で* 「遠近法」というときは、投影法のさらに一種である、*透視図法* を指すことが多いです。

この透視図法は非常に重要な概念なので、様々な呼び方があります。例えば、*遠近法 (perspectiveの訳)*、*透視図法 (perspectiveの訳)*、*線遠近法 (linear perspective の訳)*、*透視投影 (perspective projection の訳)*、*射影変換 (projective transformation の訳)*、*パース (perspectiveの日本における略語）*、……などなど。

透視図法以外の投影法、例えば平行投影が「遠近法」であるかについて、不毛な議論が生じることがあります。「狭義の遠近法ではない」という点を強調すれば「遠近法ではない」となるし、「投影法全体が広義の遠近法の一種」という点で見れば「遠近法である」という話になり、一見矛盾したように見てしまうのです。これは名前が同じであるから生じている問題で、本質的にはどちらも間違ったことは言っていません。

このような混乱を避けるため、「狭義の遠近法」と「広義の遠近法」を明確に区別する必要があります。ここからは、狭義の遠近法を「透視図法」と呼び、広義の遠近法は単に「遠近法」と呼ぶことにします。

[%collapsible]
.補足：語源と訳語について
====
perspective は語源に立ち返ると、 per-(通して) と specere(見る) に分けることができます。透視図法の創始であるブルネレスキがなぜこの概念に perspective (原著ではイタリア語で prospettiva ですが) と名付けたのかは推測するしかありませんが、透視図法の概念を学ぶとこれが透視図法を指すのに自然な命名であることがわかると思います。

https://www.etymonline.com/word/perspective によると、perspectiveという語やそれに相当するラテン語、フランス語の単語はは14世紀後半にはすでに「光の科学」の意味で使用されていたようです。ブルネレスキが透視図法を発明した時点で15世紀前半なので、perspective という語はすでに存在していました。

「透視図法」はおそらく明治期に日本に透視図法が持ち込まれた時に作られた訳語でしょう。調べた限り記録が残っていないのでこれも推測ですが、perspectiveを語源から per-(通して) と specere(見る) に分けて、それぞれを漢字に訳したのだろうと思われます。現在であれば、perspective は一語で「遠近法」と訳されてしまいます。日本語に「遠近法」と「透視図法」の二つの単語があって、本書で使い分けられるのは、訳された時代の差による偶然かもしれません。

ちなみに、英語の perspective は多義語で、「遠近法」のほか「視点」「見通し」といった意味があります。逆に、日本語の「透かし見る」という意味では see through 、超能力的な意味での「透視」は clairvoyance などというのが適切で、perspective ではおそらく通じないでしょう。

なお、 狭義の遠近法であることを強調するために、「線遠近法(linear parspective)」という呼び方がありますが、個人的にこの書き方はあまり好きではありません。なぜなら、ある意味で言えば透視図法以外の遠近法も線を使う（投影のための線を引く）し、ある意味で言えば透視図法が「線」を使うとは限らない（直線的でない立体を描く場合など）からです。もしかすると原義では幾何学ではなく代数的な意味での「線形(linear)」だったのかもしれませんが、それで言うなら一次変換で記述できる平行投影のほうが、よほど「線形」です。いずれにせよ、本質を表した名前ではないと思われます。
====

== 注意

この章では、特に投影法について言及しているときは、原則として数学的に厳密な用語の使い方をします。たとえば「直線」とは、幅がなく無限にまっすぐ伸びる数学的な直線を指し、「立方体」は6つの正方形を直角に組み合わせた立体を指します。

このような話をすると、「そんなものは現実には存在しない、どんなものも多少は歪んでいる」「幾何学図形ではなく現実に存在するものを描きたいんだ」とか、あるいは「図法を学ぶと絵が固くなる」などといった批判を受けることがあります。しかし、いずれも適切ではありません。

現実のモチーフは多かれ少なかれ幾何形状に似ています。ビルや箱が直方体に似ているというのは明らかですが、もう少し緩く考えると自動車やバスタブも直方体に似ているし、人間の手足は円柱に似ています。これらを描く時は下書きとして描いた幾何形状に歪みや凹凸を「肉付け」することで現実感を出します。いくら似ていると言っても幾何形状をそのまま描くわけではありません。

肉付けの程度が大きくなるほど、投影法の重要度は下がりますが、歪みの少ないもの（規格化された工業製品や高度に文明化した都市など）を描く場面では、そういった肉付けによる要素が少ない分、作図技術が成果物の善し悪しを大きく左右するでしょう。

「絵が固くなる」という批判は、幾何形状を下書きとして描いたあと、現実のわずかな歪みや凹凸を「肉付け」するステップをしなかったときに起こる問題であって、投影法そのものの欠陥ではありません。現実に存在する形状と幾何形状との違いも重要ですが、だからといって正確な幾何形状の描き方を学ぶことが、現実のものを描くことの妨げになるわけではありません。

むしろ幾何学的なアプローチには積極的なメリットがあります。「歪み」「質感」といった複雑な要素をいったん排除して問題を単純化することで、数学的、幾何学的な方法論を適用することができ、より深く、正確な考察が可能になるのです。

このやり方に慣れていない方はまず [リンク] を参照してください。また、ここで意図的に省いた要素については [リンク] で補足します。
TODO: 現実と幾何学の接続


== 本章の構成

本章では遠近法を以下のように分類し、それぞれについて説明していきます。

. 遠近法
.. 投影法
... 中心投影
.... 透視図法
.... 非平面投影
... 平行投影
.... 正投影
.... 斜投影
. その他の遠近法

構成は以下のようにします。概ね頭から順に読むことを想定していますが、読むべき順というよりは、一般的なことから個別具体的なことへ進む順になっています。必要に応じて行き来してください。


* link:00-01-axiom/[00-01 ヒルベルトの公理]
* link:00-02-basic-theorem/[00-02 基本定理]
* link:01-01-prepare/[01-01 透視図法の準備]
* link:01-02-ideal-camera/[01-02 「理想カメラ」の定義]
* link:01-03-geometry-methods/[01-03 初等幾何と解析幾何]
* link:01-04-symmetry-of-camera/[01-04 理想カメラの対称性]
* link:01-05-field-of-view/[01-05 画角]
* link:01-06-degree-of-freedom/[01-06 制約と自由度]
* link:02-01-image-of-point/[02-01 点の像]
* link:02-02-image-of-segment/[02-02 線分の像]
* link:02-03-image-of-line/[02-03 直線の像]
* link:02-04-image-of-plane/[02-04 平面の像]
* link:02-05-concurrent/[02-05 共点の保存]
* link:02-06-point-at-infinity/[02-06 虚像と無限遠点]
* link:02-07-projective-geometry/[02-07 射影幾何学との接続]
* link:03-01-curve/[03-01 曲線]
* link:03-02-image-of-circle-1/[03-02 円の像　その1]
* link:03-03-image-of-circle-2/[03-03 円の像　その2]
* link:03-04-image-of-circle-3/[03-04 円の像　その3]
* link:03-05-surface/[03-05 曲面]
* link:04-01-n-point-perspective/[04-01 n点透視図法]
* link:04-02-1-point-perspective/[04-02 1点透視図法の作図法]
* link:04-03-2-point-perspective/[04-03 2点透視図法の作図法]
* link:04-04-3-point-perspective/[04-04 3点透視図法の作図法]
* link:05-00-ignored-factor/[05-00 無視した要素]
* link:non-planer-projection/[非平面投影]
* link:other-perspectives/[other-perspectives]
* link:theorem/[透視図法の諸定理]
