---
layout: base.njk
title: 透視図法の諸定理
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]


凡例
A⊥B：AとBは垂直
A//B：lとmは平行
△ABC∽△DEF：△ABCと△DEFは相似
|AB|：線分ABの長さ
⇒：ならば
⇔：ならば、またその時に限り

ここでは一般的なユークリッド幾何学の公理と性質を認める。全ては列挙しないが、以下は重要なので特記する。

（平行による推移）
直線lとl'、直線mとm'がとl//l'、m//m'を満たすとき、l//mならl'//m'で、またl⊥mならl'⊥m'。
直線lとl'、平面AとA'がとl//l'、A//A'を満たすとき、l//Aならl'//A'で、またl⊥Aならl'⊥A'。
平面AとA'、平面BとB'がとA//A'、B//B'を満たすとき、A//BならA'//B'で、またA⊥BならA'⊥B'。

（面と直線の直角）
直線lと平面Sが垂直であるなら、S上の任意の直線とlは垂直である。
直線lと、S上にあって平行でない二直線mとnがl⊥mかつl⊥nを満たすなら、lはSに垂直である。
（注：これは特に「同一直線上にない点ABCと、直線lについて、直線AB⊥lかつ直線AC⊥lなら直線BC⊥l」の形でよく使う。）


定義（視点、投影面）
三次元ユークリッド空間中に投影の中心となる点Eを取り、視点と呼ぶ。また、視点を通らない無限平面を取り、投影面と呼ぶ。

定義（点の像）
空間中の点Aに対して、視点EからA方向に伸ばした半直線と投影面の交点が存在する場合、その点を「Aの像」と呼ぶ。

定義（図形の像）
空間図形Pに対して、P上の各点の像を集めて得られる投影面上の平面図形を「Pの像」と呼ぶ。

定理（直線上の三点の投影）
空間中の点A,B,Cが同一直線上にあって、それらが像a,b,cを持つとき、a,b,cは同一直線上にある
（∵仮定より、ABCが同一直線上なのでEABCは同一平面上。(平面EABC)をSとする。
像の定義よりEAaは同一直線上にあるのでEABaは同一平面上であるから、aはS上。
同様に、b、cもS上にあることが言える。Eabcはすべて同一平面上。
面Sは投影面と平行でない（∵投影面上にないEを含んでいて、投影面との共有点abcも持っている）ので、面Sと投影面の共通部部分は直線のみ。
abcは投影面上でもあり面S上でもあるので、投影面と面Sが交差する直線上にある。　■）
（注：直線や線分の投影が曲がらないことの根幹）

定理（線分の投影）
点A,Bがそれぞれ像a,bを持つとき、線分ABの像は線分abとなる。

定義（消失点）
直線Lが投影面と平行でないとき、EV//Lとなる点Vを投影面上に取ることができ、その点VをLの消失点と呼ぶ。

定理（直線の投影）
視点Eを通らず、投影面と平行でない直線Lの像は、Vを端とし、投影面とLの交点を通る半直線となる。
視点Eを通らず、投影面と平行な直線Lの像は、Lに平行な投影面上の直線となる。

定理（平行な線の消失点）
投影面に対して平行でない直線Lと、Lに平行な直線mがあるとき、Lとmの消失点は一致する。

定義（視心と視距離）
視点から投影面に下ろした垂線の足を視心と呼び、ここではOと置く。また、|EO|を視距離と呼び、ここではdと置く。

定理（一点透視図法の消失点）
互いに垂直な直線L₁L₂L₃があり、L₁は投影面と平行でなく、L₂L₃が投影面と平行であるとき、L₁の消失点をVとする。このとき、O=Vが成り立つ。
（∵L₁⊥L₂//投影面、L₁⊥L₃//投影面より、L₁⊥投影面であり、L₁//EVであるから、EV⊥投影面。
また視心の定義より、EO⊥投影面であるからEV//EOである。
Eを通りEOに平行な直線はEOただ一つしか存在しないため、EV=EOである。
直線EOと投影面の交点はただ一つしか存在しないためV=O　■）
（注：直方体の向きが混在していても、一点透視図法の消失点は必ず視心にある。）

定理（二点透視図法の消失点）
互いに垂直な直線L₁L₂L₃があり、L₁L₂は投影面と平行でなく、L₃は投影面と平行であるとき、L₁,L₂の消失点をそれぞれV₁,V₂とする。このとき、
(1)  直線V₁V₂はL₃の像l₃に垂直である。
（∵L₁⊥L₃、L₁//EV₁、L₃//l₃より、EV₁⊥l₃である。
同様にL₂⊥L₃、L₂//EV₂、L₃//l₃より、EV₂⊥l₃である。
EV₁⊥l₃、EV₂⊥l₃より、V₁V₂⊥l₃である。　■）

(2)  視心O、V₁、V₂は同一直線上にある。
（∵EO⊥投影面であり、l₃は投影面上の直線であるため、EO⊥l₃である。
EO⊥l₃、EV₁⊥l₃より、OV₁⊥l₃である。
V₁V₂⊥l₃と合わせるとOV₁//V₁V₂である。
V₁を通りOV₁に平行な直線はただ一つであるためOV₁=V₁V₂　■）

(3)  V₁とV₂は視心Oに対して反対側にあり、|OV₁|×|OV₂|=d²となる。
（∵EV₁⊥EV₂、V₁V₂⊥OEなので、△EOV₁∽△V₂OE（∵∠EOV₁=∠V₂OE=90°、∠EV₁O=90°-∠OEV₁=∠V₂EO）。
  |OV₁|:|EO|=|EO|:|OV₂|であるから、|OV₁|×|OV₂|=|EO|²=d²　■）

定理（三点透視図法の消失点）
互いに垂直な直線L₁L₂L₃があり、いずれも投影面と平行でないとき、これらの消失点をそれぞれV₁,V₂,V₃とする。このとき、
(1) OV₁⊥V₂V₃が成り立つ。
（∵消失点の定義とL₁L₂L₃の条件より、EV₁とEV₂とEV₃はたがいに垂直である。
EV₂⊥EV₁かつEV₃⊥EV₁より、V₂V₃⊥EV₁…①
EO⊥投影面で、V₂V₃は投影面上の直線なので、V₂V₃⊥EO…②
①②より、OV₁⊥V₂V₃　■）
（注：V₂V₃が地平線だとすると、V₁はOの真下にある、と考えるのが直感的だろうか）

(2)視心Oは△V₁V₂V₃の垂心となる。
（∵対称性より、OV₂⊥V₃V₁、OV₃⊥V₁V₂も成り立つので、Oは△V₁V₂V₃の垂心　■）

(3) V₂V₃とOV₁の交点をP、V₃V₁とOV₂の交点をQ、V₁V₂とOV₃の交点をRとすると、|OV₁|×|OP|=|OV₂|×|OQ|=|OV₃|×|OR|=d²が成り立つ。
（∵Pは(平面EV₂V₃)上の点であり、(平面EV₂V₃)⊥EV₁であるから、EP⊥EV₁。
△EOV₁∽△POE（∵∠EOV₁=∠POE=90°、∠EV₁O=90°-∠OEV₁=∠PEO）より|OV₁|:|EO|=|EO|:|OP|であるから、|OV₁|×|OP|=|EO|²=d²。
対称性より|OV₁|×|OP|=|OV₂|×|OQ|=|OV₃|×|OR|=d²　■）







定義（消失線）
投影面と平行でない平面Sについて、視点Eを通り平面Sと平行な平面S'がただ一つ存在する。S'と投影面が交差する線をSの「消失線」と呼ぶ。

定理（平行な面の消失線）
投影面と平行でない平面S1と、S1と平行なS2があるとき、それらの消失線は一致する。

定理（消失線と消失点）
S上の直線及び、Sと平行なすべての直線の消失点は、Sの消失線上に来る。

定義（地平線）
特に、地面の消失線を地平線と呼ぶ。
地面：重力に対して垂直な平面
水平：地面に対して水平
鉛直：地面に対して垂直

（ここまで扱ってきた数学的三次元空間には上下の概念がなかった、実際描かれる建物等は水平な床と鉛直な柱を持つことが多いため、地平線を考えることが多い。ただし、図形的性質は重力に関係せず成立することに注意）


