export const sketchManifest: Record<string, { loader: () => Promise<unknown> }> = {
  "_script/sketches/test-sketch": { loader: () => import("../_script/sketches/test-sketch.sketch.ts") },
  "color-and-light/sketches/2d-gamut-test": { loader: () => import("../color-and-light/sketches/2d-gamut-test.sketch.ts") },
  "color-and-light/sketches/3d-LSM-color": { loader: () => import("../color-and-light/sketches/3d-LSM-color.sketch.ts") },
  "color-and-light/sketches/gamut-convex-hull": { loader: () => import("../color-and-light/sketches/gamut-convex-hull.sketch.ts") },
  "color-and-light/sketches/metamerism": { loader: () => import("../color-and-light/sketches/metamerism.sketch.ts") },
  "color-and-light/sketches/photometry": { loader: () => import("../color-and-light/sketches/photometry.sketch.ts") },
  "color-and-light/sketches/sine-wave": { loader: () => import("../color-and-light/sketches/sine-wave.sketch.ts") },
  "projection-and-perspective/sketches/accurate-circle": { loader: () => import("../projection-and-perspective/sketches/accurate-circle.sketch.ts") },
  "projection-and-perspective/sketches/circle-and-cube": { loader: () => import("../projection-and-perspective/sketches/circle-and-cube.sketch.ts") },
  "projection-and-perspective/sketches/circle-basic": { loader: () => import("../projection-and-perspective/sketches/circle-basic.sketch.ts") },
  "projection-and-perspective/sketches/circle-large-pov": { loader: () => import("../projection-and-perspective/sketches/circle-large-pov.sketch.ts") },
  "projection-and-perspective/sketches/circle-parallel-square": { loader: () => import("../projection-and-perspective/sketches/circle-parallel-square.sketch.ts") },
  "projection-and-perspective/sketches/concurrent": { loader: () => import("../projection-and-perspective/sketches/concurrent.sketch.ts") },
  "projection-and-perspective/sketches/eccentric-circle": { loader: () => import("../projection-and-perspective/sketches/eccentric-circle.sketch.ts") },
  "projection-and-perspective/sketches/ellipse-and-line": { loader: () => import("../projection-and-perspective/sketches/ellipse-and-line.sketch.ts") },
  "projection-and-perspective/sketches/ideal-camera-test": { loader: () => import("../projection-and-perspective/sketches/ideal-camera-test.sketch.ts") },
  "projection-and-perspective/sketches/ideal-camera1": { loader: () => import("../projection-and-perspective/sketches/ideal-camera1.sketch.ts") },
  "projection-and-perspective/sketches/ideal-camera2": { loader: () => import("../projection-and-perspective/sketches/ideal-camera2.sketch.ts") },
  "projection-and-perspective/sketches/image-of-circle-all": { loader: () => import("../projection-and-perspective/sketches/image-of-circle-all.sketch.ts") },
  "projection-and-perspective/sketches/image-of-line": { loader: () => import("../projection-and-perspective/sketches/image-of-line.sketch.ts") },
  "projection-and-perspective/sketches/image-of-point": { loader: () => import("../projection-and-perspective/sketches/image-of-point.sketch.ts") },
  "projection-and-perspective/sketches/image-of-segment": { loader: () => import("../projection-and-perspective/sketches/image-of-segment.sketch.ts") },
  "projection-and-perspective/sketches/image-of-shape": { loader: () => import("../projection-and-perspective/sketches/image-of-shape.sketch.ts") },
  "projection-and-perspective/sketches/orthodrome": { loader: () => import("../projection-and-perspective/sketches/orthodrome.sketch.ts") },
  "projection-and-perspective/sketches/projective-geometry": { loader: () => import("../projection-and-perspective/sketches/projective-geometry.sketch.ts") },
  "projection-and-perspective/sketches/symmetry-of-camera": { loader: () => import("../projection-and-perspective/sketches/symmetry-of-camera.sketch.ts") },
}
