---
layout: base.njk
title: 色と光
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]

## 色と波長の違い

光は電磁波の一種で、空間中を電場と磁場が交互に変化しながら伝わっていく波です。波ということは波長があります。理科の授業で習ったかもしれませんが、この波長が違うと色が違って見えるのでした。

虹の七色のように、赤が一番波長が長く、橙、黄、緑、青、藍、の順で波長が短くなり、紫が一番波長が短くなります。この範囲の光を可視光線と呼びます。赤より波長の長い光は赤外線、紫より波長の短い光は紫外線と呼ばれ、目には見えません。具体的には、おおよそ約700nm～400nmの範囲が可視光線にあります。1nm（ナノメートル）は1mmの100万分の一なので、数百nmというとだいだい髪の毛の太さの200分の一くらいです。

しかし、これらが人間に見える色すべてを表しているかというと、そうではありません。話はもう少し複雑です。

例えば、白は虹色の上にないですよね。「白はいろいろな色の光が混ざっている」と習うかもしれません。しかし、白だけが特別な色なのでしょうか。それはちょっと違和感がありますよね。

また、黄緑は黄色と緑の「中間の色」であるため、虹の上でも黄色と緑の間にあり、これはよく納得できます。しかし、赤紫は赤と紫の中間の色なのに、赤と紫は直接隣り合っていないため、これらの中間の波長の光は赤紫ではなく緑です。これはいったいどういうことでしょうか。

このページを読むことで、きっとこの疑問に対する答えを得られるはずです。

////
虹色によく似た概として、「色相環」というのがあります。色相環は、赤、橙、黄、緑、青、藍、紫の順で色が並んでいる円形の図です。色相環を見ると、赤と紫は隣り合っていて、間に赤紫があります。しかし、波長は短い方から長い方に一方向的に並べられるものであって、円形に並ぶものではありませんよね。なぜ色相環はこれを円形に並べてしまうのでしょうか。

実は、色相環は虹色と見た目は似ていますが、その背後にある原理は全く異なっています。このページを読むことで、これらの二つの違いを理解できるようになるはずです。
////

## 波の性質

色と光について知るには、まず波についてよく知る必要があります。波についてのいくつかの用語と性質をおさらいしておきましょう。

以下の波形は正弦波と呼ばれ、最も純粋な形の波とされています。

TODO:グラフないしアニメーションを入れる

sketch::sine-wave[]

* 変位：ある時点、ある箇所での波の高さ
* 振幅：最大の波の高さ
* 波長：波の形が繰り返すまでの距離
* 周期：波の形が繰り返すまでの時間
* 周波数：1秒間に波の形が繰り返す回数
* 位相：ある時点で（あるいは初期状態で））波の形がどれだけ進んでいるかを表す量

.補足：周期、波長、周波数の関係
[%collapsible]
====
変位と振幅については紛らわしいことは何もないのですが、波長、周期、周波数の間はいずれも「波の細かさ/粗さ」を表す指標で、密接な関係があり、しばしば混同されます。

周期、波長、周波数の関係は以下のようになります。
\[
波の進む速度 = 波長 × 周波数 \\
周期 = 1 / 周波数 \\
波長 = 波の進む速度 / 周波数 \\
\]

光の場合、波の進む速度は一定なので、周期、波長、周波数のどれかが決まれば自ずと他も決定するため、パラメーターとしては本質的に1つと考えて差し支えありません
====

.発展１：Y-XグラフとY-Tグラフ
[%collapsible]
====
先ほどは動いている正弦波のグラフをアニメーションで見ました。が、紙に書いたり印刷したりするグラフは動かないので、動かないグラフとして表現する必要があります。そのためのよく知られた方法が二つあり、ひとつはY-Xグラフ、もうひとつはY-Tグラフです。

Y-Xグラフは縦軸に変位(=Y)横軸に位置(=X)をとったグラフで、特定の時間での波の形を表します。一方、Y-Tグラフは縦軸に変位(=Y)横軸に時間(=T)をとったグラフで、特定の位置での波の形が時間的にどのように変化しているかを表します。

Y-Xグラフはある瞬間の波の形の写真を撮ったもの、Y-Tグラフはある点にセンサーを置いて動きをプロットしたもの、と言えます。

進行する正弦波はX-TグラフでもY-Tグラフでも同じ振幅の正弦波の形になりますが、Y-Xグラフでは横軸が位置なので、山と山の間隔が波長を表し、Y-Tグラフでは横軸が時間なので、山と山の間隔が周期を表します。
====

この時点で色についてわかることが一つあります。虹の七色には波の形を決定するパラメーターは波長だけではありません。特に、振幅は大きな影響があります。光の場合、振幅が変わると、光は強さ、明るさが変わります。「明るくしたり暗くしたりしても同じ色ではないか？」と思うかもしれませんが、色によっては明るさが違うだけで別の名前を持っていることがあるので、区別されると考えるのが自然です。例えば、オレンジ色を暗くしていくと、だんだん茶色と呼べる色になっていきます。

「茶色い光ってなんだ？」「それは暗いオレンジであって茶色ではないのでは？」「オレンジと茶色の境目ってどこだよ」と思うかもしれませんが、これは「光っている」という状況だったり

ともあれ、これで茶色など虹色の中には入っていなかった多くの色を表せるようになりました。

.コラム：光の振幅って何mmぐらい？
[%collapsible]
====
可視光の波長は数百nmだったけど、それでは振幅のほうは具体的に何mmくらいなの？という疑問が湧くかもしれません。しかし残念ながら、光の振幅は長さの単位で表すことはできません。

水面波や音は媒質が物理的に振動しているので、振幅はその媒質の振動の大きさを表す量であり、長さの単位（次元）で表すことができます。しかし、光は先に述べたように電磁波の一種であり、空間中を電場と磁場が交互に変化しながら伝わっていく波であり、何かが空間中を揺れ動いているわけではありません。

光の場合、振幅は長さではなく、この電場や磁場の最大の強さによって表されます。この振幅は光のエネルギー密度から求めることができます。
====

.コラム：光の位相は考えなくていいの？
[%collapsible]
====
波の要素の一つに、位相がありました。位相が違うと光はどのように見えるのでしょうか。

まず、自然界にある多くの光は、実は位相がバラバラな光として目に届いていますこれをインコヒーレントと言います。
位相が揃った光はコヒーレント光と呼ばれ、レーザー光線などがそれにあたります。光の干渉実験などでレーザーを使うのはこのためです。

それに、人間の目は位相を区別する力がありません。光の干渉が起きると位相の違いが強弱の違いとして現れるので、見えるようになりますが、そうでなければ区別できません。人間に区別できない違いに別の色の名前が付くことはないので、考えなくてよいことにしておきます。
====

## 波の重ね合わせ

光に限らない波の話をもう少し続けます。波は足し合わせることができます。（海の波とかをイメージするとそんな高い波は崩れるだろというようなグラフにもなりますが、光や音のスケールでは関係ありません）

TODO:インタラクティブなグラフを入れる

では、波長の異なる波を重ね合わせた時、波はどうなるでしょうか。
二つの波を重ね合わせた時、波の形は複雑な形になり、正弦波ではなくなります。さらに、三つの波を重ね合わせると、さらに複雑な形になります。音で例えるとわかりやすいかもしれません。ドとミの音を重ねてもレになるわけではなく、複雑な和音として聞こえるのと同じですね。訓練された人であればドとミを聞き分けられるかもしれませんが、レに聞こえる人はいません。

NOTE: 音も光と同じように波であり、低い音ほど波長が長く、高い音ほど波長が短いです。


.発展２：うなりの場合
[%collapsible]
===
TODO: うなりの場合と不確定性原理
===


次に、このようにしてできた複雑な波の波長について考えてみましょう。そもそも、波長を定義できるでしょうか。

もしかすると次のように考える人がいるかもしれません。「正弦波について『波の形が繰り返すまでの距離』が波長であったように、複雑な波もきっと同じ形が繰り返すのだから、その長さを『波長』とすることができるのではないか」と。
確かに、重ね合わせる二つの波長が1:2とか2:3といった整数比であれば、その最大公倍数で区切ると同じ形の繰り返しになるので、周期性があると言えそうです。しかし、これが17:19とか113:355みたいな中途半端な整数比であった場合、このように定義された「波長」は非常に長いものになってしまいます。これは、物理的な意味からはかけ離れてしまっている気がしませんか？　それに、重ね合わせる二つの波長が無理数の比であった場合、同じ形の繰り返しは一切起こらないため、周期性はありません。つまり、波長を定義できない、強いて言えば無限大になってしまいます。

ここで、先ほどの音の重ね合わせを思い出してみましょう。ドとミの重ね合わせた音は、耳が良い人であれば、二つの音に分解して聞き取れるのです。つまり、複雑な波形に無理に一つの波長を定義するのではなく、「二つの波を重ね合わせたもの」として理解するのが適切なようです。

実は、どのような複雑な波であっても、それらは単純な正弦波の重ね合わせとして分解して表すことができます。無数の正弦波を足し合わせたあとの波の形から、どんな波長をどれくらいの振幅・位相で足し合わせたのかが分かってしまうのです。これをフーリエ変換と呼び、縦軸に振幅、横軸に周波数をとったグラフのことを「周波数スペクトル」と呼びます。光について同様に周波数によって分けたものを「分光スペクトル」と言います。

NOTE: 分光スペクトルの場合、横軸は周波数ではなく波長とすることが多いです。が、これは単に慣習の問題で、周波数と波長は反比例の関係にあるので、どちらも本質的に同じことを表しています。

NOTE: 現実には分光スペクトルはフーリエ変換で計算するのではなく、プリズムなどを使って実験的に得ることが可能です。

.なぜ正弦波に分解するのか
[%collapsible]
====
フーリエ変換は、どのような複雑な波であっても単純な正弦波の重ね合わせとして分解して表すことができるというものでした。では、なぜわざわざ正弦波に分解するのでしょうか。それは正弦波が最も基本的で、純粋な波とされているからです。

ではなぜ正弦波が純粋な波とされているのでしょうか。それは正弦波には他の周波数が混ざていないから、つまりフーリエ変換しても別の周波数の成分が出てこないからです。

……あれ、話が一周してしまいました。これでは循環論法になっています。もしも、フーリエ変換がもっと別の形の、例えば尖った三角形の波に分解する操作であれば、三角波が純粋な波と言えてしまうかもしれません。つまり、「なぜ正弦波に分解するのか」の説明にも「正弦波の純粋さ」の説明にもなっていません。

これを納得してもらうには、別の方向からのアプローチが必要です。突き詰めると、正弦波に対する微積分の操作がしやすいから、と説明するしかないのかもしれません。

フーリエ変換は以下の積分を計算することで得られます。
\[
F(\omega) = \int_{-\infty}^{\infty} f(t) e^{-i\omega t} dt
\]
なぜこの式で正弦波に分解できるのかは割愛しますが、\(e^{-i\omega t}\) の部分が正弦波と関連した式の形になっています。もしも、フーリエ変換の式がもっと別の形であれば、別の波に分解できたかもしれません。が、それは積分の計算上の都合で、非常に厄介なものになるでしょう。正弦波というのは微積分との相性が良く、この形でならいろいろな関数のフーリエ変換が計算しやすいのです。

このようなことを言うと、正弦波は振り子やバネなどの単振動にも表れる基本的な波形じゃないか、と思う人もいるでしょう。が、これも実は計算上の都合でしかありません。バネは弾性力が変位に比例するという仮定の下でのみ正弦波の振動をしますし、振り子の振動も導出を思い出すと復元力が変位に対して比例するという近似をしていますが、これは小角近似（\(sin\theta \approx\theta\)）を含んでいるので、振幅が十分に小さい時にしか成り立ちません。

このような比例の関係を線形とよび、線形な微分方程式は比較的簡単に解くことができて、単振動の解を持ちます。一方、現実世界は非線形なことが多く、そんなに簡単に表せないものがほとんどです。線形性や正弦波の振動は現実世界の複雑さを計算しやすく落とし込んだ近似に過ぎません。
====

このことは、色の見え方を理解する上で非常に重要なポイントになります。

## 「中間の色」
「中間の色」の話に戻りましょう。そもそも「中間の色」とは何を指しているのでしょうか。
混色についてはまた別の機会に詳しく説明しますが、大きく分けてインクなどを近似する減法混色と、光の重ね合わせを表す加法混色の二種類があります。今は光の話をしているので、ここでは加法混色について考えてみましょう。

加法混色の図を見ると、赤の光と緑の光を混ぜると黄色になる、とされています。（信じられない人は暗い部屋で実験してみましょう）。で、虹色を見ると、ここでも赤と緑の中間の色は黄色になっています。しかし、赤と青の光を混ぜると赤紫になるとされていますが、この現象は虹色のどこにもありません。

実は、ここに混乱のもとがあります。先ほどのフーリエ変換、あるいは音の重ね合わせの例を思い出してみましょう。ドとミの音を重ねると、レにはならず、ドとミの両方が聞こえる和音になるのでしたね。実は光もこれと同様に、赤と緑の光を重ねてできる黄色い光と、「もともと黄色だった光」は別の光なのです。つまり、光を構成する波長の成分が異なるのです。
これは、プリズムで分光してみると顕著に分かります。赤と緑の光を重ねた黄色い光をプリズムで分光すると、赤と緑の二つの波長の成分が見えるのに対し、もともと黄色だった光をプリズムで分光すると、黄色の波長の成分が一本だけ見えるのです。

これで、赤と青の光を重ねると、中間の波長の緑になるのではなく、赤紫になる理由が分かりましたね。赤紫は少なくとも長短2種類の波の重ね合わせでのみ見ることができるのです。

一方で、虹の上に描かれるのは、それぞれ単一の波長の光で表される光です。このような光を「単色光」と言います。単色光は炎色反応やナトリウムランプなどで見ることができます。単色光は、フーリエ変換で表すと、ある特定の波長の成分が一本だけピークになっているスペクトルになります。

しかし、こんどは新たな疑問が生まれました。なぜ「黄色の単色光」と「赤と緑を混ぜた光」は別の周波数成分を持つにもかかわらず、なぜ同じ黄色として見えるのでしょうか。また、色相環はなぜ円形なのかという疑問にもまだ答えていません。これは人間の網膜の仕組みについて知る必要があります。

## 錐体細胞と視感度

人間の網膜には、錐体細胞と杆体細胞という二種類の細胞があり、これらが光を感じとっています。このうち杆体細胞は暗い場所でわずかな明るさを感じ取ることに特化した細胞で、色を感じ取ることはできません。

錐体細胞は明るい場所での明るさを感じ取るだけでなく、色も感じ取ります。錐体細胞は、さらにL錐体細胞、M錐体細胞、S錐体細胞の三種類があり、これらはそれぞれ異なる波長の光に対して最も敏感に反応します。L錐体細胞は赤い光に最も敏感で、M錐体細胞は緑の光に最も敏感で、S錐体細胞は青い光に最も敏感です。（Lはlong、Mはmedium、Sはshortの頭文字で、感じ取る波長の長さを表しています。）

ただし、これらの錐体細胞は、完全に赤、緑、青の光にだけ反応するわけではなく、あるていどの幅を持っています。この幅があることで中間的な黄色や水色の単色光についても感じることができるのですね。そして、どの錐体細胞も反応しない範囲はの光は目に見えない、つまり可視光でないということになります。

横軸に波長、縦軸に感度を取って、それぞれの錐体細胞がどの波長にどれほど反応するかをグラフにしたものを「視感度曲線」と呼びます。実際の視感度曲線は以下のようなものです。

網膜上にはこれらの三種類の錐体細胞が多数混ざった状態で存在しています。ある波長の光を受けると、それぞれの錐体細胞が異なる程度に反応します。その反応の具合を網膜につながっている神経回路や脳で処理することで、どんな波長の光が入ってきたのかを知ることができます。

視感度曲線をもとに、光が入ってきた時にそれぞれの錐体細胞がどれくらい反応するかを計算してみましょう。
現実の視感度曲線はちょっと複雑すぎるので、ここでは簡略化した以下のグラフを使ってみましょう。

TODO: 計算問題

では、このような光が入ってた時はどうでしょうか。

TODO: 計算問題

光の周波数成分は違うのに、同じ結果になりましたね。これらの二種類の光は錐体細胞の反応の具合が同じなので、人間の網膜では区別できないということになります。
この例は簡略化した例でしたが、実際の網膜でも原理は同じです。

光の周波数成分が違うのに、同じ錐体細胞の反応になることはよくあります。光の周波数成分は「どの周波数を」「どれくらい」という無数のパラメーターの情報を持っています。しかし、網膜は三種類の錐体細胞の反応の組み合わせという三次元の情報しか処理できないため、周波数成分が違うのに区別できない光というのがたくさん生まれるのです。

これが、黄色の単色光と赤と緑を混ぜた光が同じ黄色として見える理由です。

次は、最後の疑問、「色相環」とは何か、を探しに行きましょう。

## 色空間
前回、光の周波数成分は無数のパラメーターの情報を持っているのに対し、人間の網膜は3種類の錐体細胞の反応の組み合わせでしか光の色を知覚できないということを学びました。
逆に言えば、3種類の錐体細胞の反応の組み合わせで表せる色が人間に区別できる光の色すべてということになります。これを使って、色を規則的に並べる、体系的に表すことを考えます。

可視光を波長順に並べた虹のグラデーションは単色光の波長という1次元の情報しかなく、白や赤紫など表現しきれない色がありました。実際の光は多数の波長の光が混ざりっているため、その配合を表す周波数スペクトルが必要で、これを把握するのは少々困難です。3種類の錐体細胞の反応の組み合わせだけを記録すれば、含めたすべての色が表現できるわけです。デメリットは人間に区別できる精度に限られますが、たいていの場合、人間に区別できない色は同じ色と見做してしまってよいので、さほど問題になりません。これは魅力的ですね。

.ここまでに登場した 色の表し方の整理
| 色の表し方 | 記録する情報（次元） | 表せる範囲 |
|---|---|---|
| 虹色 | 一次元（波長） | 単色光のみ |
| 虹色+明るさ | 二次元（波長と振幅） | 単色光のみ |
| 周波数スペクトル | 無限次元（各波長について、その振幅） | 物理的に異なるすべての光 | 
| 錐体細胞の反応 | 三次元（L、M、Sの反応の組み合わせ） | 人間に区別できるすべての光 |

というわけで、色を表すためには、三次元の空間が必要かつ十分である、つまり三次元がちょうどいいということが分かりました。

TODO:自由度と次元の記事を書く

具体的にどんな方法がとれるでしょうか、それぞれの錐体細胞がどれほど反応したかを0～100%で表せるとします。三次元空間上に、L軸、M軸、S軸を取って、ある光の色に対応する座標にその色をプロットしてみます。すると以下のような三次元空間が生まれます。

sketch::3d-LSM-color[]

(L, M, S) = (0, 0, 0)の点は、どの錐体細胞も反応しない、つまり完全な黒を表します。(L, M, S) = (100, 100, 100)の点は、どの錐体細胞も最大限に反応する、つまり眩しいほどの完全な白を表します。これを繋ぐ対角線上には、LMSともに同程度に反応する、つまりグレーの色が並びます。そこから、離れるほどL、M、Sの反応の差が大きくなります。この反応の差が大きい光を、人間は「鮮やな色」と知覚するのです。

どんな色も、原点方向に近づけると暗くなり、遠ざけると明るくなります。虹色にはなかった「灰色の光」や「茶色の光」は白やオレンジを暗くした色であることが分かりますね。
三次元のものを図に書くのは少々難しいので、ある断面で切断した図がよく使われます。このとき、水平や垂直に切ってもいいのですが、明るさに違いがあると色の比較がしづらいので、ある断面には同じ明るさの色がすべて並んでいてほしいものです。そこで、対角線に対して垂直な、(100, 0, 0)、(0, 100, 0), (0, 0, 100)の三点を通る平面で切断します。すると以下のような三角気が生まれます。

TODO: この辺の説明本当か？　LSMの重みづけの話題はどう回収する？

## 純色線と純紫線
すべての色は先ほどの立方体の中に点を打つことができると分かりました。しかし、その立方体の空間すべてに対応する色があるでしょうか。つまり、色が取りうる範囲は立方体全体でしょうか、それとも、立方体の中の一部だけでしょうか。

例えば(0, 100, 0)に対応する色が存在するかを考えてみましょう。これはM細胞が100%反応しているのに対し、L細胞やS細胞は一切反応していないというような光を表します。そのような光を作れるでしょうか。ここで、以前やった計算問題を思い出してみましょう。L細胞とM細胞の視感度曲線が大きく重なっているので、どのように波長を配合してもM細胞だけを反応させることができず、L細胞がつられて反応してしまうのです。このような理由から、色が取りうる範囲は立方体全体ではなく、その中の一部だけになります。

具体的にどの範囲が「対応する色のある」領域となるでしょうか。
まず単色光が取りうる範囲を考えてみましょう。単色光は波長によって区別されていました。この曲面が断面上に現れたものを「純色線」と呼びます。単色光は波長順に一列に並んでいるものなので、この曲線も両端が繋がっていないU字型になります。

次に、複合的な色について考えてみましょう。二つの単色光色をある割合で混ぜた「中間の色」は、この色空間の中でも中間、つまり2点を繋ぐ線分を内分した範囲上に位置します。この操作では純色線の外側に出ることはできません。閉じていなかった純色線の両端である（ギリギリ見える）赤と（ギリギリ見える）紫をある割合で混合して得られる色は、純色線の両端を繋ぐ線分上に現れることになります。この線分は、純紫線と呼ばれます。

さらに、三つ以上の単色光を混ぜた色について考えても、この囲まれた領域の外側に出ることはできません。結局、この釣り鐘型の領域の中に、すべての色が収まることになります。

NOTE: このように、図形の内部を線分で埋め尽くすことで得られる図形を「凸包」と呼びます。

NOTE:　実は、ある「ずる」をすることによって、M細胞だけが反応してL細胞が反応しないような状況を作ることができます。錐体細胞は同じ色を見続けるとだんだん麻痺していき、感度が鈍くなｒ性質があり、これを利用します。赤い光をずっと見た後に急に緑に切り替えると赤に反応するL細胞は麻痺した状態で、M細胞を反応させることができます。、これは単色光の緑よりも鮮やかな『超緑』となります。が、これは「網膜の調子によってそう見える」というだけで、「超緑色の光がある」わけではないので、普通は色として考えません。

## 色の3要素
LSM色空間は三つの錐体細胞の反応具合によって直交座標系で表していました。これは網膜の原理からすると、自然な表し方ですが、「明るさ」「鮮やかさ」などを考えるには少々不便です。
そこで、LSM色空間のなかに別の座標軸を置き直して考えやすくします。まず、LSM色空間では、対角線方向に進むほど色が明るくなるのでした。これを一つ目の軸とし、「明度」と呼びます。次に、対角線からの距離が大きいほど色が鮮やかになるので、これを二つ目の軸「彩度」とします。明るさと鮮やかさを指定しても、対角線からどの方向に離れればいいのかがまだ分かりません。これを決定する角度を「色相」と呼びます。

NOTE: 「明度」は座標系によっては「輝度」と呼ばれることがあったり、「彩度」は「飽和度」と呼ばれることがあったりします。これは、基本的な概念は同じことを表しています。座標系によって基準をどこに置くか、何と呼ぶかといった違いがありますが、体系的な理解のためには、これらの違いはあまり重要ではありません。

これで、色を「色相」「彩度」「明度」の三要素で表すことができるようになりました。これらの三要素は、色空間の中の座標軸に対応しているので、色空間の中での位置を指定することで、色を表すことができます。そして、「色相環」は明度や彩度を保ったまま色相を変えた時に色がどのように変化するかを表した図なのです。LSM空間上で考えると、対角線を囲むように切り取った円形の図形ということが分かります。

これで、色相環がなぜ円形なのか、そして、なぜ虹色では繋がっていない赤と紫が色相環では繋がっているのかが分かりましたね。

## 色の再現度の限界
ディスプレイは赤、青、緑の三種類の光を混ぜて色を作り出します。これを「光の三原色」と言い、Red, Green, Blueの頭文字を取ってRGBと呼ばれることもあります。。
赤はL錐体細胞が最も反応する650nm付近、緑はM錐体細胞が最も反応する546nm付近、青はS錐体細胞が最も反応する436nm付近の光を表しています。

CAUTION: M細胞が最も反応する波長が緑だからと言って、緑色の光がM細胞だけを刺激するわけではないことに注意してください。赤、青についても同様、LSMとRGBは対応関係があるものの、完全に対応しているわけではありません。

これらの3色を混ぜることで、色空間の中のある程度の範囲の色を再現することができます。しかし、すべてではありません。前回確認したように、複数の色を混ぜて作れる色は、その両極端の色を繋いだ線分上にしか存在しません。RGBの三色を混ぜて作れる色は、
それに、ディスプレイに出せる明るさは上限があるので、R,G,Bそれぞれについて、0%～100%の明るさから選択できるとしても、色空間中の平行六面体（歪んだ立方体）の範囲しか表せません。
そもそも、ディスプレイの赤は理想的な単波長ではないので、純色線のさらに内側の狭い領域しか表せないのです。