---
layout: base.njk
title: 色と光
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]

## 色と波長の違い

光は電磁波の一種で、空間中を電場と磁場が交互に変化しながら伝わっていく波です。波ということは波長があります。理科の授業で習ったかもしれませんが、この波長が違うと色が違って見えるのでした。

虹の七色のように、赤が一番波長が長く、橙、黄、緑、青、藍、の順で波長が短くなり、紫が一番波長が短くなります。この範囲の光を可視光線と呼びます。赤より波長の長い光は赤外線、紫より波長の短い光は紫外線と呼ばれ、目には見えません。具体的には、おおよそ約400nm～700nmの範囲が可視光線にあります。1nm（ナノメートル）は1mmの100万分の一なので、数百nmというとだいだい髪の毛の太さの200分の一くらいです。

しかし、これらが人間に見える色すべてを表しているかというと、そうではありません。話はもう少し複雑です。

例えば、白は虹色の上にないですよね。「白はいろいろな色の光が混ざっている」と習うかもしれません。しかし、白だけが特別な色なのでしょうか。それはちょっと違和感がありますよね。

また、黄緑は黄色と緑の「中間の色」であるため、虹の上でも黄色と緑の間にあり、これはよく納得できます。しかし、赤紫は赤と紫の中間の色なのに、赤と紫は直接隣り合っていないため、これらの中間の波長の光は赤紫ではなく緑です。これはいったいどういうことでしょうか。

このページを読むことで、きっとこの疑問に対する答えを得られるはずです。

////
虹色によく似た概として、「色相環」というのがあります。色相環は、赤、橙、黄、緑、青、藍、紫の順で色が並んでいる円形の図です。色相環を見ると、赤と紫は隣り合っていて、間に赤紫があります。しかし、波長は短い方から長い方に一方向的に並べられるものであって、円形に並ぶものではありませんよね。なぜ色相環はこれを円形に並べてしまうのでしょうか。

実は、色相環は虹色と見た目は似ていますが、その背後にある原理は全く異なっています。このページを読むことで、これらの二つの違いを理解できるようになるはずです。
////

## 波の性質

色と光について知るには、まず波についてよく知る必要があります。波についてのいくつかの用語と性質をおさらいしておきましょう。

以下の波形は正弦波と呼ばれ、最も純粋な形の波とされています。

TODO:グラフないしアニメーションを入れる

{% sketch "sketches/sine-wave" %}

* 変位：ある時点、ある箇所での波の高さ
* 振幅：最大の波の高さ
* 波長：波の形が繰り返すまでの距離
* 周期：波の形が繰り返すまでの時間
* 周波数：1秒間に波の形が繰り返す回数
* 位相：ある時点で（あるいは初期状態で））波の形がどれだけ進んでいるかを表す量

.補足：周期、波長、周波数の関係
[%collapsible]
====
変位と振幅については紛らわしいことは何もないのですが、波長、周期、周波数の間はいずれも「波の細かさ/粗さ」を表す指標で、密接な関係があり、しばしば混同されます。

周期、波長、周波数の関係は以下のようになります。
\[
波の進む速度 = 波長 × 周波数 \\
周期 = 1 / 周波数 \\
波長 = 波の進む速度 / 周波数 \\
\]

光の場合、波の進む速度は一定なので、周期、波長、周波数のどれかが決まれば自ずと他も決定するため、パラメーターとしては本質的に1つと考えて差し支えありません
====

.発展１：Y-XグラフとY-Tグラフ
[%collapsible]
====
先ほどは動いている正弦波のグラフをアニメーションで見ました。が、紙に書いたり印刷したりするグラフは動かないので、動かないグラフとして表現する必要があります。そのためのよく知られた方法が二つあり、ひとつはY-Xグラフ、もうひとつはY-Tグラフです。

Y-Xグラフは縦軸に変位(=Y)横軸に位置(=X)をとったグラフで、特定の時間での波の形を表します。一方、Y-Tグラフは縦軸に変位(=Y)横軸に時間(=T)をとったグラフで、特定の位置での波の形が時間的にどのように変化しているかを表します。

Y-Xグラフはある瞬間の波の形の写真を撮ったもの、Y-Tグラフはある点にセンサーを置いて動きをプロットしたもの、と言えます。

進行する正弦波はX-TグラフでもY-Tグラフでも同じ振幅の正弦波の形になりますが、Y-Xグラフでは横軸が位置なので、山と山の間隔が波長を表し、Y-Tグラフでは横軸が時間なので、山と山の間隔が周期を表します。
====

### 輝度と色度
この時点で色についてわかることが一つあります。虹の七色は波長の違いから生まれるものでしたが、波の形を決定するパラメーターは波長だけではありません。特に、光の振幅の違いは視覚的に大きな影響があります。光の場合、振幅が変わると、強さ、明るさが変わります。

明るさが違う色は視覚的に異なって見えるので、とりあえず区別することにします。実際、色によっては明るさが違うだけで別の名前を持っていることもあるので、区別されると考えるのが自然です。例えば、オレンジ色を暗くしていくと、だんだん茶色と呼べる色になっていきます。

しかし、それでも「明るくしたり暗くしたりしても同じ色ではないか？」と思うかもしれません。これは鋭い指摘です。「光の明るさが変わる」や「光の強さが変わる」と、「光の色が変わる」は意味合いとして全く異なるようにも思えます。例えばオレンジ色を暗くしていくと茶色になるのは確かですが、

光の強さ、色の明るさのことを「輝度」と呼び、それ以外の光の色味を「色度」と呼ぶことにします。すると、オレンジと茶色は「色度は同じだが、輝度が違う」と表現することができます。ここでは輝度の違いも輝度と色度が両方一致した時に「色」が同じ、と呼ぶことにしましょう。「色度」と「色」は似て非なる概念なので注意してください。

ともあれ、これで茶色など虹色の中には入っていなかった多くの色を表現できるようになりました。
しかし、まだ「白」や「赤紫」は現れていません。色度についてもっと深く知る必要がありそうです。

.コラム：光の振幅って何mmぐらい？
[%collapsible]
====
可視光の波長は数百nmだったけど、それでは振幅のほうは具体的に何mmくらいなの？という疑問が湧くかもしれません。しかし残念ながら、光の振幅は長さの単位で表すことはできません。

水面波や音は媒質が物理的に振動しているので、振幅はその媒質の振動の大きさを表す量であり、長さの単位（次元）で表すことができます。しかし、光は先に述べたように電磁波の一種であり、空間中を電場と磁場が交互に変化しながら伝わっていく波であり、何かが空間中を揺れ動いているわけではありません。

光の場合、振幅は長さではなく、この電場や磁場の最大の強さによって表されます。この振幅は光のエネルギー密度から求めることができます。
====

.コラム：光の位相は考えなくていいの？
[%collapsible]
====
波の要素には、振幅と波長のほか、位相がありました。位相が違うと光はどのように見えるのでしょうか。

実は、自然界の光には定まった位相というのがありません。というのも、自然界にある多くの光は位相がバラバラな光として目に届いています。このような光をインコヒーレント光と言います。
位相が揃った光はコヒーレント光と呼ばれ、レーザー光線などがそれにあたります。コヒーレント光は波としての光の性質が如実に表れます。干渉実験などでレーザーを使うのはこのためです。

それに、人間の目は位相を区別する力がありません。光の干渉が起きると位相の違いが強弱の違いとして現れるので、見えるようになりますが、そうでなければ区別できません。人間に区別できない違いに別の色の名前が付くことはないので、考えなくてよいことにしておきます。
====

## 波の重ね合わせ

色についてより詳しく考えるために、光に限らない波の話をもう少し続けます。

波は足し合わせることができます。（海の波とかをイメージするとそんな高い波は崩れるだろというようなグラフにもなりますが、光や音のスケールでは関係ありません）

TODO:インタラクティブなグラフを入れる

では、波長の異なる波を重ね合わせた時、波はどうなるでしょうか。
二つの波を重ね合わせた時、波の形は複雑な形になり、正弦波ではなくなります。さらに、三つの波を重ね合わせると、さらに複雑な形になります。音で例えるとわかりやすいかもしれません。ドとミの音を重ねてもレになるわけではなく、複雑な和音として聞こえるのと同じですね。訓練された人であればドとミを聞き分けられるかもしれませんが、レに聞こえる人はいません。

NOTE: 音も光と同じように波であり、低い音ほど波長が長く、高い音ほど波長が短いです。


.発展２：うなりの場合
[%collapsible]
===
TODO: うなりの場合と不確定性原理
===


次に、このようにしてできた複雑な波の波長について考えてみましょう。そもそも、波長を定義できるでしょうか。

もしかすると次のように考える人がいるかもしれません。「正弦波について『波の形が繰り返すまでの距離』が波長であったように、複雑な波もきっと同じ形が繰り返すのだから、その長さを『波長』とすることができるのではないか」と。
確かに、重ね合わせる二つの波長が1:2とか2:3といった整数比であれば、その最大公倍数で区切ると同じ形の繰り返しになるので、周期性があると言えそうです。しかし、これが17:19とか113:355みたいな中途半端な整数比であった場合、このように定義された「波長」は非常に長いものになってしまいます。これは、物理的な意味からはかけ離れてしまっている気がしませんか？　それに、重ね合わせる二つの波長が無理数の比であった場合、同じ形の繰り返しは一切起こらないため、周期性はありません。つまり、波長を定義できない、強いて言えば無限大になってしまいます。

ここで、先ほどの音の重ね合わせを思い出してみましょう。ドとミの重ね合わせた音は、耳が良い人であれば、二つの音に分解して聞き取れるのです。つまり、複雑な波形に無理に一つの波長を定義するのではなく、「二つの波を重ね合わせたもの」として理解するのが適切なようです。

実は、どのような複雑な波であっても、それらは単純な正弦波の重ね合わせとして分解して表すことができます。無数の正弦波を足し合わせたあとの波の形から、どんな波長をどれくらいの振幅・位相で足し合わせたのかが分かってしまうのです。これをフーリエ変換と呼び、縦軸に振幅、横軸に周波数をとったグラフのことを「周波数スペクトル」と呼びます。光について同様に周波数によって分けたものを「分光スペクトル」と言います。

NOTE: 分光スペクトルの場合、横軸は周波数ではなく波長とすることが多いです。が、これは単に慣習の問題で、周波数と波長は反比例の関係にあるので、どちらも本質的に同じことを表しています。

NOTE: 現実には分光スペクトルはフーリエ変換で計算するのではなく、プリズムなどを使って実験的に得ることが可能です。

.なぜ正弦波に分解するのか
[%collapsible]
====
フーリエ変換は、どのような複雑な波であっても単純な正弦波の重ね合わせとして分解して表すことができるというものでした。では、なぜわざわざ正弦波に分解するのでしょうか。それは正弦波が最も基本的で、純粋な波とされているからです。

ではなぜ正弦波が純粋な波とされているのでしょうか。それは正弦波には他の周波数が混ざていないから、つまりフーリエ変換しても別の周波数の成分が出てこないからです。

……あれ、話が一周してしまいました。これでは循環論法になっています。もしも、フーリエ変換がもっと別の形の、例えば尖った三角形の波に分解する操作であれば、三角波が純粋な波と言えてしまうかもしれません。つまり、「なぜ正弦波に分解するのか」の説明にも「正弦波の純粋さ」の説明にもなっていません。

これを納得してもらうには、別の方向からのアプローチが必要です。突き詰めると、正弦波に対する微積分の操作がしやすいから、と説明するしかないのかもしれません。

フーリエ変換は以下の積分を計算することで得られます。
\[
F(\omega) = \int_{-\infty}^{\infty} f(t) e^{-i\omega t} dt
\]
なぜこの式で正弦波に分解できるのかは割愛しますが、\(e^{-i\omega t}\) の部分が正弦波と関連した式の形になっています。もしも、フーリエ変換の式がもっと別の形であれば、別の波に分解できたかもしれません。が、それは積分の計算上の都合で、非常に厄介なものになるでしょう。正弦波というのは微積分との相性が良く、この形でならいろいろな関数のフーリエ変換が計算しやすいのです。

このようなことを言うと、正弦波は振り子やバネなどの単振動にも表れる基本的な波形じゃないか、と思う人もいるでしょう。が、これも実は計算上の都合でしかありません。バネは弾性力が変位に比例するという仮定の下でのみ正弦波の振動をしますし、振り子の振動も導出を思い出すと復元力が変位に対して比例するという近似をしていますが、これは小角近似（\(sin\theta \approx\theta\)）を含んでいるので、振幅が十分に小さい時にしか成り立ちません。

このような比例の関係を線形とよび、線形な微分方程式は比較的簡単に解くことができて、単振動の解を持ちます。一方、現実世界は非線形なことが多く、そんなに簡単に表せないものがほとんどです。線形性や正弦波の振動は現実世界の複雑さを計算しやすく落とし込んだ近似に過ぎません。
====

このことは、色の見え方を理解する上で非常に重要なポイントになります。

## 「中間の色」
「中間の色」の話に戻りましょう。そもそも「中間の色」とは何を指しているのでしょうか。
混色についてはまた別の機会に詳しく説明しますが、大きく分けてインクなどを近似する減法混色と、光の重ね合わせを表す加法混色の二種類があります。今は光の話をしているので、ここでは加法混色について考えてみましょう。

加法混色の図を見ると、赤の光と緑の光を混ぜると黄色になる、とされています。（信じられない人は暗い部屋で実験してみましょう）。で、虹色を見ると、ここでも赤と緑の中間の色は黄色になっています。しかし、赤と青の光を混ぜると赤紫になるとされていますが、この現象は虹色のどこにもありません。

実は、ここに混乱のもとがあります。先ほどのフーリエ変換、あるいは音の重ね合わせの例を思い出してみましょう。ドとミの音を重ねると、レにはならず、ドとミの両方が聞こえる和音になるのでしたね。実は光もこれと同様に、赤と緑の光を重ねてできる黄色い光と、「もともと黄色だった光」は別の光なのです。つまり、光を構成する波長の成分が異なるのです。
これは、プリズムで分光してみると顕著に分かります。赤と緑の光を重ねた黄色い光をプリズムで分光すると、赤と緑の二つの波長の成分が見えるのに対し、もともと黄色だった光をプリズムで分光すると、黄色の波長の成分が一本だけ見えるのです。

これで、赤と青の光を重ねると、中間の波長の緑になるのではなく、赤紫になる理由が分かりましたね。赤紫は少なくとも長短2種類の波の重ね合わせでのみ見ることができるのです。

一方で、虹の上に描かれるのは、それぞれ単一の波長の光で表される光です。このような光を「単色光」と言います。単色光は炎色反応やナトリウムランプなどで見ることができます。単色光は、フーリエ変換で表すと、ある特定の波長の成分が一本だけピークになっているスペクトルになります。

しかし、こんどは新たな疑問が生まれました。なぜ「黄色の単色光」と「赤と緑を混ぜた光」は別の周波数成分を持つにもかかわらず、なぜ同じ黄色として見えるのでしょうか。また、色相環はなぜ円形なのかという疑問にもまだ答えていません。これは人間の網膜の仕組みについて知る必要があります。