---
layout: base.njk
title: 理想と理論
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]

== 美術を理論化するにあたって

物理学や数学的な視点から物事を語ろうとするときには、日常的な感覚とは異なる概念や用語が出てきます。その中でも「理想」という言葉は、極めて重要な概念でありながら、特に誤解を生みやすい言葉の一つです。あらゆるものを理論的に語るにあたって、「理想化」という概念を避けて通ることはできません。

物理学などを学んだことがある人であればこの概念はすでにインストールされていることがほとんどなのですが、芸術を学ぼうとする人の場合はそうとは限りません。そして、ここに理解の齟齬があると、テキスト全体を読み進めるにあたって大変な誤解を生む可能性があります。なので、ここでしっかりとこの概念を説明しておこうと思います。

== 『理想』とは

『理想』という言葉を聞いて、あなたは何を思い浮かべるでしょうか。
Wiktionaryによると、『理想』とは以下のように定義されています。

[quote, Wiktionary]
物事の最も望ましい状態。

多くの人は、非の打ちどころのない完璧な状態や、自分が最も求めていたもの、というような意味を思い浮かべるでしょう。例えば、「理想の仕事」や「理想の彼氏」「理想の物件」などといった表現があります。何を「理想」とするかは人それぞれでしょうが、何にせよそれが「良い」という価値判断を含んでいますよね。

しかし、物理学の文脈において、『理想』という言葉は全く異なった意味合いを持っています。

== ガリレオの実験

一つ有名な例を出しましょう。

物体が落ちる速さについて考えてみます。試しに、その辺にある紙と石を空中から落としてみると、紙のほうがゆっくり落ちるのが目視でも確認できます。この結果から類推すると、重い物体ほど速く落ちると考えるのは自然なことです。古代ギリシアのアリストテレスは、物体が落下する際の速度はその物体の重さに比例すると説明し、その説明が広く信じられていました。（信じていたのみで誰も検証していませんでしたが、ビデオや正確な時計がない時代です。仕方のないことでしょう）

しかし、ガリレオはこの考えに疑問を持ち、「どんな物体も同じ速度で落ちるのではないか」と仮定し、同じ大きさで重さの違う鉄球と木の球を同時に落とすという実験を行いました。すると、見事に二つの球は同時に地面に着地したのです。この実験は、物体の落下速度が重さに左右されないことを示し、物理学の理解を大きく変えるものでした。重力加速度の発見です。（この実験はガリレオ本人ががピサの斜塔で行ったという逸話がありますが、実際には弟子が各地で行っていたようです）

すると、「いやいや、紙が落ちるのはどう見ても石より遅いじゃないか」という反論が考えられます。（ガリレオの時代にそのような反論が起こったかは分かりませんが、起きても自然な話です）。現代の物理学では、これは空気抵抗の影響である、と説明されます。空気抵抗は物体の形状や速度によって異なりますが、一般的に軽い物体や断面積の大きい物体ほど空気抵抗の影響を受けやすく、結果として落下速度が遅くなります。実際、真空中で実験をすると羽と鉄球は同時に落ちることが確認できます。

== 二つの説明

「紙より石のほうが早く落ちる」という現象を説明するために、アリストテレスは「物体の落ちる速度は重さに比例する」と説明しましたが、現代の技術で実際に物体の速度を測ってみると、この説明は完全に間違いであったことが明らかです。これほど単純明快な説明で解決できたら良かったのですが、「空気抵抗を考慮した物体の落下」という複雑な現象を解き明かすには、残念ながらこの説明はシンプル過ぎたようです。

WARN: 「比例」というのは、重さが2倍の物体は落下速度も2倍、重さが3倍なら落下速度も3倍になるということで、単に「重いほど速い」というよりずっと具体的な主張です。

一方で、ガリレオ以降では「原則としてどんな重さでも同じ速さで落ちる」「空気抵抗によって軽い物体はブレーキがかかる」という二段構えの理解になりました。「原則としてどんな重さでも同じ速さで落ちる」という説明はシンプルでありながら、真空中での落下や、十分に重い物体の運動（物体が十分に重いと、空気抵抗の影響は相対的に無視できるようになります）について正確に記述できています。ただ、紙や羽根のような軽い物体の落下については、空気抵抗の影響が大きいため、あとから空気抵抗の影響を加える必要があります。

== 「理想的な」

このように、複雑な概念の理解を深めるために一度シンプルな状況を考えるという方法は、物理学では、いや、物理学に限らずあらゆる学問において、非常によく使われる方法です。このようなに単純化する方法を「理想化」と呼んだり、空気抵抗がないような状況を「理想的な」と呼んだりします。対義語は「実在」などが使われます。

最初から空気抵抗の影響を考えると現象が複雑すぎるため、一度、空気抵抗の影響を排除して考え、後から空気抵抗の影響を加えるのです。空気抵抗のない世界というのは身の回りには存在しないわけですが、そのような世界では様々な物事がシンプルになるため、より複雑な法則について考察できるようになります。例えば万有引力やエネルギー保存則などは、空気抵抗のない世界を前提にして考えられたものです。

理想化は、現実の複雑な現象を理解するための強力なツールです。

理論的に物事を語るうえで、理想化を避けて通ることはできません。なぜなら、現実はあまりに複雑であり、どんな理論も完璧にそれを説明しつくすことは難しいからです。だからと言って説明を放棄するわけにはいかないので、シンプルな状況から考えて、そこから徐々に複雑な状況を考えるという方法が必要になります。理想化は、現実の複雑な現象を理解するための重要なステップなのです。

理想：実在という二項対立も、じつは単純化した説明です。実際には、理論を複雑、具体的にしていくほど実在のものに近づいていくものの、現実は複雑すぎるため完璧のものに一致することは難しいです。どんな理論も実在のものとは多かれ少なかれ乖離した部分がありつつも、その理論に一致するような存在を「仮定」することで、話をより先へと進めることができるのです。

== その他の「理想」の例

ここまでは、物体の落下を考える時に空気抵抗を *一旦* 無視する、という例を見てきました。これは、「理想化」のほんの一例にすぎません。

例えば中学校の理科で「フックの法則」を習います。バネの伸び縮みは、バネにかかる力に比例する、という法則です。実際のバネは、縮み切った状態からそれ以上縮めることは難しいですし、ある程度伸ばすと伸び切ってしまって戻らなくなったり、無理に伸ばすと切れてしまったりします。このような挙動は「フックの法則」では説明できない、ある意味で反例とも言える例ですが、かといって「フックの法則」が間違っているわけではありません。ある範囲ではある程度「フックの法則」に近い挙動をすることと、このシンプルな法則によって物体の変形について様々なことが説明できることが重要なのです。連続体力学などの分野では、物体を無数の小さな点の集まりとみなすことで、物体の変形や応力を解析する方法が使われますが、これも一種の理想化です。

気体に熱や圧力を加えた時の膨張や圧縮を考える「熱力学」という分野では、気体の振る舞いを表す状態方程式という重要な数式が存在します。そして、この方程式に振舞う気体のことを「理想気体」と呼びます。「理想」という言葉が入っている通り、これも話をシンプルにするために仮定された理論上の存在で、現実には存在しません。例えば気体分子の体積や分子間力、気体分子同士の衝突、液化などの現象は無視されています。しかし、理想気体について考えることで様々な現象を説明し、問題を解くことができるため、非常に重要な概念なのです。もちろん、そこで捨象された現象をあとから考慮する場合もあり、そのような場合は「理想気体」の対義語として「実在気体」と呼ぶものを考えます。

物理以外の学問ではどうでしょうか。たとえば経済学では、完全競争市場や合理的経済人などの理想化された概念がよく使われます。これらの概念は単純化されたモデルですが、現実の極めて複雑な経済を説明するための重要なツールとなっています。

数学はある意味で最も理想化された学問です。哲学的な場では一切のゆがみのない「完璧な球体」が存在しないという例が挙げられますが、球体に限らず、大きさのない「点」、幅がなく無限にまっすぐ伸びる「直線」、完璧な線分と直角で囲まれた「長方形」、等の存在も、現実には存在しません。しかし、存在しないからと言って考えられないわけでも、考える意味がないわけでもありません。完璧な長方形が実在しないからと言って、長方形の面積を求める公式に意味がないわけではありませんし、コピー用紙が「完璧な長方形」ではないからと言って、コピー用紙の面積が求められないなんて話も馬鹿げています。

== よくある誤解

「理想」とか「理想的」といった言葉を出すと、あるいは暗黙に「理想化」をしているような複雑性を捨象したような説明をすると、的外れな誤解を生むことがよくあります。

=== 理想＝良いという誤解

日常語では「理想」は「完璧」とか「欠点がない」とか「願ったり叶ったりの」のような意味で使われているので、「理想的な状況」というと、どうしても「完璧な状況」や「欠点のない状況」をイメージしてしまうのは自然なことです。しかし、物理学における「理想的な状況」は、あくまで理解を深めるための単純化されたモデルであり、必ずしも「良い」や「悪い」といった価値判断を伴うものではありません。

例えば、物理学者は「空気抵抗のない理想的な状況」のような言い回しをよく使います。慣れていない人がこれを聞くと、「空気抵抗がないことを『良い』と考えているんだ」「空気抵抗を『悪い』と考えているんだ」のような誤解をしたり、「いやいや空気抵抗も悪気があるわけじゃないんですよ」みたいな擁護を始めたりしてしまうことがあります。そうではありません。物理学者は、空気抵抗のない状況が「理解しやすい」からそのような言い回しをしているだけであって、空気抵抗があることを「悪い」と考えているわけではありません。

物理学者が「理想の」と言っているときは、心の中で「理論上の」と置き換えて理解してください。きっと理解しやすくなります。

以下は私の推定ですが、日常語的な意味での「理想」は、哲学用語としての「理想」から発展したものでしょう。「理想」は、哲学的な意味でも物理学的な意味でも、イデアの翻訳です。イデアはプラトンが提唱した概念で、現実世界の上には形而上の完璧な世界があり、現実世界はその投影であるというものです。おそらくここに多義語の原因があり、イデアの「完璧さ」の意味を借りてくると、日常語のような「理想の彼氏」みたいな用法になり、「実在しない」という意味を借りてくると「理想気体」みたいな用法になる……のだと思います。

=== 理想＝誤っているという誤解

次にありがちなのが、「理想的な説明は、現実の複雑な現象を単純化しすぎているため、誤っている」という誤解です。確かに、理想化された説明は現実のすべての要素を考慮しているわけではないため、完全に正確な説明ではありません。しかし、理想化された説明は、現実の複雑な現象を理解するための重要なステップであり、その後に追加される要素を考慮することで、より正確な説明に近づくことができます。

例えば「_理想的な状況では_、 どんな物体も同じ速度で落ちる」という説明に対して「いやいや、紙が落ちるのはどう見ても石より遅いじゃないか。その説明は間違っている」などと反論してしまう、などがあります。わざわざ物理学者が「理想的な状況では」と言っているときは、言っている側も何らかの要素を削ぎ落していることを自覚しているわけです。この例で言えば、空気抵抗については後から考えるので、辛抱強く待っていてください、ということになります。

=== 理想＝役に立たないという誤解

理想化された説明は、現実の複雑な現象を単純化しすぎているため、役に立たないという誤解もあります。確かに、一旦要素を削ぎ落して考えてから、後で補うという考え方は一見するとまどろっこしいです。しかし、一旦話をシンプルにして現象の本質を理解しやすくするために必要であるから、理想化というステップを踏んでいるのです。

まどろっこしさを嫌って、短くてわかりやすい説明ばかりを求めてしまうと、「物体の落下する速度は重さに比例する」のような誤った説明に飛びついてしまいかねません。