
== 自然科学と美術の類似性

美術というと人文系の分野と見做されることが多いですが、私はむしろ自然科学との類似性が強いと考えています。

自然科学は、自然界の現象を観察し、そこから法則を見出し、論文として後世に記録し、さらにその法則をもとに新しい現象を予測したり、他の観察との整合性が取れるように擦り合わせたりすることの積み重ねです。美術も、目の前のモチーフや既存の作品を観察、分析し、それをもとに新しい作品を創造し、発表したり後世に残したりすることが目的です。違いはそこに主観が入り込むことを忌避するか歓迎するかです。

ここで共通項となるのが、いずれも視覚を介することです。人間は情報の大部分を視覚から得ていると言われています。自然科学のほぼすべての実験は、溶液の色を観察するとか、天体の動きを観察するとか、計器の目盛りを読み取るなどといった、視覚的な観察が不可欠です。一方で、美術は視覚芸術であり、視覚を使って表現することが目的です。つまり、自然科学も美術も、視覚を介して世界を理解し、表現するという点で共通しているのです。

つまり、自然科学での方法論を美術に応用することもできるし、逆に美術での方法論を自然科学に応用できる可能性もあると考えています。そのため、極端な話、美術やイラストに全く興味のない人でも、自然科学に興味がある人であれば、このテキストを読む価値は十分にあると思います。


TODO:

外延と内包
帰納と演繹
歴史と経験
反権威主義
反証/検証

教育、学習の至上命題
学習限界、人間に与えられた有限の時間で、学問の最先端に到達し、さらに切り開かないといけない。
膨大な外延的現象をインプットしてそこから学習者に帰納を見出させるのは非効率。
AI時代にどのようにして品質の高い知識を維持するか。権威主義の限界。

「愚者は経験に学び、賢者は歴史に学ぶ」経験を軽視すべきでない
「巨人の肩に乗る」一人で科学は作れないので重要だが、巨人を無批判に信用すべきではない
「教育は道路の舗装」学習者が効率よく真理にアクセスするためのサポートをするが、体験、検証は学習者の責任である

=== フラットアーサーの例

ところで、フラットアーサー達は、地動説を「そう教えられたから/多くの人がそう信じているからといって、信じるのは間違っている」「実際にその目で丸い地球を見たことがあるか」といった論法で否定しています。人から聞いただけの科学的な知識は実体験を伴わないものとして軽視して、実際に自分の目で見たことがあるかどうかを重視しているのです。

フラットアーサーの模型の一つを紹介します。まず、古典的な天動説の模型では、円盤状の地球の周りを太陽や月、星が回っているとしていますいました。しかし、これでは世界のどこでも同時に昼になり、同時に夜になるため、時差が説明できません（国際電話やインターネットが存在する現代では、時差の存在は簡単に「体感」できます）。そこで、フラットアーサーは、このモデルに修正を加え、太陽や月は常に地球の上空を回っていて、地球の一部だけを照らしていると説明しました。どうでしょう、説得力を感じるでしょうか。

一部の行動力があるフラットアーサーは地球が平らであることを示すために、レーザー測量などの大掛かりな実験をすることがあります（その多くは失敗、つまり地球が丸いという結論に終わっています）。逆に地球が丸いことを示すために、フラットアーサーを宇宙や南極に連れて行こうというプロジェクトが企画されたり実行されたりすることもあります。実際に検証しようという態度と行動力は称賛に値しますが、これらの方法は非常にハードルが高く、非効率的な方法です。

実は、地球が丸いこと、少なくともフラットアーサーが掲げている平面地球模型が間違っていることを示すのはそんなに難しくありません。まず光の直進性について机上スケールの実験で確かめたうえで、日没前後の太陽の動きを見るだけで十分です。もしフラットアーサーの模型のようであれば、太陽は夜の間も暗くなるか小さくなった状態で地平線より上に見えるはずで、実際に見える「日没」すら説明できないのです。

NOTE: しかし考えてみると、机上スケールの実験と同じことが宇宙スケールでも起きるということは、実に不思議なことです。これは宇宙の法則が並進対称性を持ち、宇宙の別の場所でも同じ現象が起きると考えることでほとんど矛盾が起きない世界に我々が生きていることを意味しています。ニュートンの万有引力の発見は、地球上のリンゴが落ちる現象と、月が地球の周りを回る現象が同じ法則で説明できることを示したものでした。これは、地上の現象が宇宙でも成り立っていると仮定した最初の例です。

さて、フラットアーサー達が至った結論は間違っていますが、彼らの懐疑的な態度、実体験を重視する態度は評価に値すると考えています。むしろフラットアーサーのように実体験を重視する態度は、自然科学の方法論と共通している部分もあるのです。彼らの根本的な誤解は、自然科学の根拠が「偉い人が言ったから」「みんなが信じているから」であると考え、体験を伴わない机上の空論であると断定してしまっている点です。これは大変な誤解です。実際の自然科学は宗教のように信じる信じないではなく、実験や観察を通じて積み重ねられた知識です。先人たちの膨大な努力による部分もありますが、その一部は簡単な実験、検証によって確認できるものも多いのです。

そして、フラットアーサーをバカにしている人は多くいますが、体験に基づいてフラットアーサーを否定しようとする人は驚くほど少ないように見えます。「地球は丸いと習ったから」「NASAの写真を疑うほど陰謀論に染まっていないから」というだけの理由でフラットアーサーを否定するのは、知識と体験が結びついていないという点で、フラットアーサーと同じ過ちを犯していると言えるでしょう。実体験と知識が結びついていない状態は、フラットアーサーだけでなく、一般の人々にも広く見られる現象なのです。

ここで再びキーワードになるのが、視覚です。人間は視覚を通じて世界を理解し、知識を得ることが多いです。
どのような科学的な知見も、実際に検証し、体感することが重要です。知識を視覚的な体験として確認するためのそこで、このテキストでは、視覚についての

=== 愚者は経験に学び、賢者は歴史に学ぶ

「愚者は経験に学び、賢者は歴史に学ぶ」という言葉がありますが、私はこれに部分的に反対です。この言葉の真意は、個人が一生涯に得られる経験は限られていて、先人の知恵を借りる必要があるという点だと思います。先人の知恵を学ぶことは重要ですが、その知識が正しいかどうかは常に疑いの目を持って、自分の経験として確認することが重要だと考えています。

== 経験偏重型の問題

一方で、先人の知恵を全く学ばないのも問題です。先人の知恵を学ぶことは、過去の経験から得られた知識を活用することであり、これもまた重要なことです。つまり、愚者は経験に学び、賢者は歴史に学ぶという言葉は、両方とも重要な要素を含んでいると考えています。

確かに、科学は一夜にしてできたものではありません。

「巨人の肩に乗る」という言葉もあります。
