---
layout: base.njk
title: なぜこのテキストを書くのか/なぜこのテキストを読むべきなのか
---

:stem: latexmath
:toc: macro
:toclevels: 3
:toc-title: 目次
toc::[]


ここでは、私がなぜこのテキストを書く理由と、そしてなぜこのテキストを読むべきなのかについて記述します。
従来の教材に対して私と同様の不満を抱えている場合、是非このテキストを読むべきです。

== 理論化の目標

個別のケースや小さな知見の積み重ねとしてではなく、より大きな枠組みのなかで体系的、理論的に説明することで、新しい場面における応用力を養い、現象を予測できるようにする。

== 典型的な『イラスト技法書』に対する不満

イラストの描き方について、「技法書」などとして販売されている本や、インターネット上に存在する情報のほとんどは、二種類の形態をとっています。
一つはメイキングを主体とするもの、もう一つは細かなTips集のようなものです。

メイキングを主体とする教材は、ある絵が完成するまでの過程を時系列に沿って追いながら、どのような色をどう重ねたかなどが詳しく書かれています。Youtubeなどの動画コンテンツとしてタイムラプスが公開されている場合もあればや、数枚の絵（しばしば、幅広い画風のイラストレーターから一枚ずつ集める形態がとられます）のメイキングをまとめた書籍として販売される場合もあります。推察するに、これはイラストレーターが本業としての作品制作の過程を記録し解説を添える形態であるため、負担が小さく制作しやすいのだろうと思われます。

これは初めてイラストを描きたいときに、具体的にどのような手順で描いていけばいいのかをイメージする上では非常に有用な情報です。しかし、いざ自分のイラストを描こうとしたときには、まったく同じ絵を描くわけではないので、応用が必要となります。この時に必要になるのは、作者がなぜその色を選んだのか、なぜそのような線を引いたのか、といった、もう一段階上にある情報なのですが、これらについてはほとんど語られないか、小さなコラムとして補足されるのみです。このような小さなコラムはメイキングの時系列で集積されているため体系的な順になっていないし、そうでなくとも読み落としやすく、理解を難しくしています。

もう一つ、細かなTips集のような形態をとっている教材は、「○○の描き方」のような形で様々な小さな知見が断片的に書かれているものです。これはそれぞれが小規模な形であるため、PixivやTwitter、Pinterestなどで発表、共有されやすいものです。ある個人が一定数のTipsをインターネット上に公開した後、これを紙媒体に再録する形で書籍や同人誌が販売されることも多くあります。
これは多少の「なぜ」について踏み込んだ言語化がされることもありますが、紹介される順番は乱雑にであり、それぞれが小さな情報なので体系的なまとまりになりません。また、それぞれの情報の真偽やわかりやすさ、重要度も玉石混交といった状態になっているため、どの情報を信じるべきか、どの情報を優先的に学ぶべきかがわからなくなってしまいます。

NOTE: 日本語圏以外での事情についてはあまり分かりません。

これらの教材は既に氾濫しているため、あえて新しく同じようなものを書くつもりはありません。ここでは多くの教材でカバーされていない部分を重視し、情報の正しさを担保するための「なぜそうなのか」から、具体的な「どのように描くべきか」までを順序、体系立てて、俯瞰して説明することを目指します。

== 典型的な美術教育に対する不満

学校の図工/美術の授業や、美大受験のための予備校の授業は、与えられた時間のほとんどを実技、つまり作品制作の時間に充てています。教師から情報を得られるタイミングは、制作の過程で教師がアドバイスしたり、場合によっては教師が代わりに筆をとって加筆をしたり、完成した絵に対して「講評」と呼ばれる時間を設けて、教師が生徒の絵を見ながら、どこが良いか、どこが悪いか、といったことをフィードバックするという形態が一般的です。この過程で、どのように鉛筆を持てばいいのか、どのように色を重ねればいいのか、などといった技術的なことを経験を通じて学ぶことに重きが置かれています。これは「練習」を通じて「能力」や「技術」を与えるための授業であり、「理論」や「知識」を与えるための授業ではありません。このような教育は、スポーツのコーチングに近いものがあります。

この方法のメリットとしては、生徒は実際に手を動かして技術を覚えながら、制作の過程で個別に突き当たった問題に対してピンポイントに適切なアドバイスが得られることがあります。

しかし、教師の手助けなく自力で良い絵を描くためには、過去に遭遇した多数の事例を新しい絵に応用する必要があります。そのために、過去に得られたそれぞれのアドバイスをまとめ直して体系的に理解しなおす必要がありますが、これは生徒が自力で担う必要があります。

このような場においては、指導者の頭の中に体系的な知識があろうとなかろうと、生徒が享受する場面では個別のアドバイスにとして分解された状態であり、体系的な形では得られなくなってしまいます。順序だてて体系的な理解を得るためには座学として体系的な理論を学ぶ時間が必要ですが、そのような時間はほとんど設けられません。これでは、個別の知見を新しい絵に応用することが難しくなります。

これはおそらく、二つの理由に起因するのだろうと推察しています。ひとつは、学校にしても予備校にしても、これは美術が他の教科と違って段階的な到達目標のようなものが定められていないため、生徒側の前提知識やレベルがまちまちであり、画一的な座学を提供できないことです。もうひとつは伝統的な問題で、指導者の側も同様のスポーツのコーチングのような教育を受けてきたために、そもそも理論を整理して伝えるという土壌がないのだろうと思われます。

このテキストでは、各自が好きなペースで読み進められるので、前提知識やレベルがまちまちな人でも、体系的な理論を学ぶことができます。また、「なぜ」にそこまで興味がない場合は興味のある所から読み始めて、疑問を抱いたら前に戻るというような読み方がおすすめです。。

== 科学的、反権威主義、低信用

絵の描き方について「こうするとよい」といった知見が生まれるとき、最初にそれを言った人は、（彼の経験知的なものかより科学的なものかはわかりませんが）「なぜそうすべきなのか」について、何らかの理論的背景を持っていたはずです。しかし、それが伝承される過程では、理由の部分は「この本にこう書いてあるからとか」「美術の先生がこう言ったから」「めちゃくちゃ絵が上手いイラストレーターがそう言ったから」などの形に置き換わっていき、最終的には「こうするとよい」というアドバイスだけが残ってしまうことが多いのです。さらに、「こうするとよい」の部分についても、電商の過程で誤解されたり解釈が変わったりして、本来の形を失うことがあります。これでは、どの知見が正しいのか、どれを信じるべきかわからなくなったり、情報の善し悪しについて不毛な議論が起きることになります。

そうならないように、情報の質を担保する仕組みが必要です。

学術論文やWikipediaなどでは、情報の品質を担保するために「信頼できる情報源」や「誰が言ったか」を重視する体系を採用しています。これを採用せざるを得ない事情も理解しますが、これにはいくつかの問題があるとわたしは考えています。まず、この出典をたどるネットワークは途切れやすいです。出典なくして語られることも多いですし、出典が明記されていても、実際にその出典には書いてなかったり、誤解した状態で伝わっていることも多いでしょう。さらに、「信頼できる情報源」というのは完璧な存在が仮定されていますが、間違うことも、嘘をつくこともあるでしょう。出典を重視する体系は、情報の品質を担保するための方法としては不十分であると言えるでしょう。

「良い」情報というのは、誰を信じるかに関係なく、「正しい」ものです。ここに複雑な人間関係、権力や政治、宗教などの問題が入り込むべきではありません。これは科学の理想像に一致します。

ここではより確実な方法として、情報の品質を担保するために「実際に自分の目で見て、体験、確認できること」を重視します。誰でも簡単に確認できる証拠が存在することと、証拠から一定の推理力を働かせることで合理的な結論を導き出すという過程を重視します。

幸い、絵やイラストに関わる知見の多くは、視覚と関連しているため、実際に自分の目で見て体験することが容易です。その体験のための図やインタラクションを提供することが、このテキストの重要な役割の一つだと考えています。